package filesystem

import (
	"bytes"
	"context"
	"encoding/hex"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	mpt "github.com/faustbrian/golib/pkg/merkle-patricia-trie"
)

func TestRetentionEncodingIdentifiersAndTemporaryRecovery(t *testing.T) {
	t.Parallel()

	var root mpt.Root
	root[0] = 0x42
	record := encodeRetentionRecord(root)
	if decoded, err := decodeRetentionRecord(record); err != nil || decoded != root {
		t.Fatalf("decodeRetentionRecord() = (%x, %v), want %x", decoded, err, root)
	}
	for _, mutation := range []func([]byte) []byte{
		func(encoded []byte) []byte { return encoded[:len(encoded)-1] },
		func(encoded []byte) []byte {
			encoded[0] ^= 0xff
			return encoded
		},
		func(encoded []byte) []byte {
			encoded[len(encoded)-1] ^= 0xff
			return encoded
		},
	} {
		malformed := mutation(append([]byte(nil), record...))
		if _, err := decodeRetentionRecord(malformed); !errors.Is(
			err,
			mpt.ErrCorruptNode,
		) {
			t.Fatalf("decodeRetentionRecord(malformed) error = %v", err)
		}
	}
	if !errors.Is(corruptRetentionError("test"), mpt.ErrCorruptNode) {
		t.Fatal("corruptRetentionError() lost corruption classification")
	}

	var generated byte
	id, err := newRetentionIDWith(
		nil,
		func(destination []byte) error {
			generated++
			for index := range destination {
				destination[index] = generated
			}
			return nil
		},
	)
	if err != nil || id[0] != 1 {
		t.Fatalf("newRetentionIDWith() = (%x, %v)", id, err)
	}
	failure := errors.New("injected random failure")
	if _, err := newRetentionIDWith(
		nil,
		func([]byte) error { return failure },
	); !errors.Is(err, failure) {
		t.Fatalf("newRetentionIDWith(random failure) error = %v", err)
	}
	var collision retentionID
	if _, err := newRetentionIDWith(
		map[retentionID]mpt.Root{collision: {}},
		func(destination []byte) error {
			clear(destination)
			return nil
		},
	); err == nil {
		t.Fatal("newRetentionIDWith(collisions) error = nil")
	}
	if _, err := newRetentionID(nil); err != nil {
		t.Fatalf("newRetentionID() error = %v", err)
	}

	encodedID := strings.Repeat("00", retentionIDBytes)
	for name, want := range map[string]bool{
		"." + encodedID + ".tmp-value": true,
		encodedID + ".tmp-value":       false,
		"." + encodedID + ".tmp-":      false,
		".short.tmp-value":             false,
		"." + strings.Repeat("z", retentionIDBytes*2) + ".tmp-value": false,
	} {
		if got := isTemporaryRetentionFile(name); got != want {
			t.Fatalf("isTemporaryRetentionFile(%q) = %t, want %t", name, got, want)
		}
	}

	path := t.TempDir()
	temporary := filepath.Join(path, "."+encodedID+".tmp-value")
	if err := os.WriteFile(temporary, []byte("temporary"), 0o600); err != nil {
		t.Fatalf("WriteFile(temporary) error = %v", err)
	}
	unrelated := filepath.Join(path, ".unrelated.tmp-value")
	if err := os.WriteFile(unrelated, []byte("unrelated"), 0o600); err != nil {
		t.Fatalf("WriteFile(unrelated) error = %v", err)
	}
	if err := recoverTemporaryRetentions(context.Background(), path, 2); err != nil {
		t.Fatalf("recoverTemporaryRetentions() error = %v", err)
	}
	if _, err := os.Lstat(temporary); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("temporary retention still exists: %v", err)
	}
	if _, err := os.Lstat(unrelated); err != nil {
		t.Fatalf("unrelated file was removed: %v", err)
	}
}

func TestRetentionInventoryRejectsCorruptState(t *testing.T) {
	t.Parallel()

	ctx := context.Background()
	var id retentionID
	id[0] = 0xab
	name := hex.EncodeToString(id[:])
	var root mpt.Root
	root[0] = 2

	validPath := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(validPath, name),
		encodeRetentionRecord(root),
		0o600,
	); err != nil {
		t.Fatalf("WriteFile(valid retention) error = %v", err)
	}
	retentions, err := readRetentions(ctx, validPath, 1)
	if err != nil || len(retentions) != 1 || retentions[id] != root {
		t.Fatalf("readRetentions() = (%v, %v)", retentions, err)
	}
	canceled, cancel := context.WithCancel(ctx)
	cancel()
	if _, err := readRetentions(
		canceled,
		validPath,
		1,
	); !errors.Is(err, mpt.ErrCanceled) {
		t.Fatalf("readRetentions(canceled) error = %v", err)
	}
	if _, err := readRetentions(
		ctx,
		validPath,
		0,
	); !errors.Is(err, mpt.ErrResourceLimit) {
		t.Fatalf("readRetentions(invalid bound) error = %v", err)
	}
	failure := errors.New("injected retention inventory failure")
	if _, err := readRetentionsWith(
		ctx,
		validPath,
		1,
		func(string, int) ([]os.DirEntry, error) {
			return nil, failure
		},
		readBoundedFile,
	); !errors.Is(err, mpt.ErrStorageRead) {
		t.Fatalf("readRetentionsWith(directory failure) error = %v", err)
	}
	if _, err := readRetentionsWith(
		ctx,
		validPath,
		1,
		readDirectoryBounded,
		func(string, int) ([]byte, error) {
			return nil, failure
		},
	); !errors.Is(err, mpt.ErrStorageRead) {
		t.Fatalf("readRetentionsWith(file failure) error = %v", err)
	}

	for _, test := range []struct {
		name    string
		entry   string
		content []byte
		dir     bool
	}{
		{name: "short name", entry: "short", content: recordForRoot(root)},
		{name: "uppercase name", entry: strings.ToUpper(name), content: recordForRoot(root)},
		{name: "invalid hex name", entry: "zz" + name[2:], content: recordForRoot(root)},
		{name: "directory", entry: name, dir: true},
		{name: "short record", entry: name, content: recordForRoot(root)[:1]},
	} {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			path := t.TempDir()
			target := filepath.Join(path, test.entry)
			var err error
			if test.dir {
				err = os.Mkdir(target, 0o700)
			} else {
				err = os.WriteFile(target, test.content, 0o600)
			}
			if err != nil {
				t.Fatalf("prepare corrupt retention error = %v", err)
			}
			if _, err := readRetentions(
				ctx,
				path,
				1,
			); !errors.Is(err, mpt.ErrCorruptNode) {
				t.Fatalf("readRetentions(corrupt) error = %v", err)
			}
		})
	}
}

func TestTemporaryRetentionRecoveryPropagatesFailures(t *testing.T) {
	t.Parallel()

	failure := errors.New("injected retention recovery failure")
	path := t.TempDir()
	operations := defaultRecoveryOperations()
	operations.readDirectory = func(string, int) ([]os.DirEntry, error) {
		return nil, failure
	}
	if err := recoverTemporaryRetentionsWith(
		context.Background(),
		path,
		1,
		operations,
	); !errors.Is(err, mpt.ErrStorageRead) {
		t.Fatalf("recoverTemporaryRetentionsWith(read failure) error = %v", err)
	}
	operations.readDirectory = func(string, int) ([]os.DirEntry, error) {
		return nil, mpt.ErrResourceLimit
	}
	if err := recoverTemporaryRetentionsWith(
		context.Background(),
		path,
		1,
		operations,
	); !errors.Is(err, mpt.ErrResourceLimit) {
		t.Fatalf("recoverTemporaryRetentionsWith(bound) error = %v", err)
	}

	encodedID := strings.Repeat("00", retentionIDBytes)
	temporary := filepath.Join(path, "."+encodedID+".tmp-value")
	if err := os.WriteFile(temporary, []byte("temporary"), 0o600); err != nil {
		t.Fatalf("WriteFile(temporary) error = %v", err)
	}
	operations = defaultRecoveryOperations()
	operations.syncDirectory = func(string) error { return failure }
	if err := recoverTemporaryRetentionsWith(
		context.Background(),
		path,
		1,
		operations,
	); !errors.Is(err, mpt.ErrStorageCommit) {
		t.Fatalf("recoverTemporaryRetentionsWith(sync failure) error = %v", err)
	}
}

func TestOpenRejectsCorruptRetentionAndPruneArtifacts(t *testing.T) {
	t.Parallel()

	ctx := context.Background()
	t.Run("prune artifact", func(t *testing.T) {
		t.Parallel()

		path := t.TempDir()
		if err := os.WriteFile(
			filepath.Join(path, prunePendingDirectory),
			[]byte("invalid"),
			0o600,
		); err != nil {
			t.Fatalf("WriteFile(prune artifact) error = %v", err)
		}
		if _, err := Open(
			ctx,
			path,
			DefaultLimits(),
		); !errors.Is(err, mpt.ErrStorageRead) {
			t.Fatalf("Open(prune artifact) error = %v", err)
		}
	})
	t.Run("retention symlink", func(t *testing.T) {
		t.Parallel()

		path := t.TempDir()
		if err := os.Symlink(
			path,
			filepath.Join(path, retentionDirectory),
		); err != nil {
			t.Fatalf("Symlink(retentions) error = %v", err)
		}
		if _, err := Open(
			ctx,
			path,
			DefaultLimits(),
		); !errors.Is(err, mpt.ErrInvalidStore) {
			t.Fatalf("Open(retention symlink) error = %v", err)
		}
	})
	t.Run("temporary retention directory", func(t *testing.T) {
		t.Parallel()

		path := t.TempDir()
		retentions := filepath.Join(path, retentionDirectory)
		if err := os.Mkdir(retentions, 0o700); err != nil {
			t.Fatalf("Mkdir(retentions) error = %v", err)
		}
		name := "." + strings.Repeat("00", retentionIDBytes) + ".tmp-value"
		if err := os.Mkdir(
			filepath.Join(retentions, name),
			0o700,
		); err != nil {
			t.Fatalf("Mkdir(temporary retention) error = %v", err)
		}
		if _, err := Open(
			ctx,
			path,
			DefaultLimits(),
		); !errors.Is(err, mpt.ErrCorruptNode) {
			t.Fatalf("Open(temporary retention directory) error = %v", err)
		}
	})
	t.Run("corrupt retention record", func(t *testing.T) {
		t.Parallel()

		path := t.TempDir()
		store, err := Open(ctx, path, DefaultLimits())
		if err != nil {
			t.Fatalf("Open() error = %v", err)
		}
		if err := store.Close(); err != nil {
			t.Fatalf("Close() error = %v", err)
		}
		name := strings.Repeat("00", retentionIDBytes)
		if err := os.WriteFile(
			filepath.Join(path, retentionDirectory, name),
			[]byte("invalid"),
			0o600,
		); err != nil {
			t.Fatalf("WriteFile(corrupt retention) error = %v", err)
		}
		if _, err := Open(
			ctx,
			path,
			DefaultLimits(),
		); !errors.Is(err, mpt.ErrCorruptNode) {
			t.Fatalf("Open(corrupt retention) error = %v", err)
		}
	})
}

func TestRetentionAndPruneValidateLifecycle(t *testing.T) {
	t.Parallel()

	ctx := context.Background()
	var nilStore *Store
	if _, err := nilStore.RetainRoot(
		ctx,
		mpt.EmptyRoot(),
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrInvalidStore) {
		t.Fatalf("nil RetainRoot() error = %v", err)
	}
	if _, err := nilStore.Retentions(
		ctx,
		1,
	); !errors.Is(err, mpt.ErrInvalidStore) {
		t.Fatalf("nil Retentions() error = %v", err)
	}
	if _, err := nilStore.Prune(
		ctx,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrInvalidStore) {
		t.Fatalf("nil Prune() error = %v", err)
	}
	zeroStore := &Store{}
	if _, err := zeroStore.RetainRoot(
		ctx,
		mpt.EmptyRoot(),
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrInvalidStore) {
		t.Fatalf("zero RetainRoot() error = %v", err)
	}
	if _, err := zeroStore.Retentions(
		ctx,
		1,
	); !errors.Is(err, mpt.ErrInvalidStore) {
		t.Fatalf("zero Retentions() error = %v", err)
	}
	if _, err := zeroStore.Prune(
		ctx,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrInvalidStore) {
		t.Fatalf("zero Prune() error = %v", err)
	}
	var nilRetention *rootRetention
	if nilRetention.Root() != (mpt.Root{}) {
		t.Fatalf("nil retention Root() = %x", nilRetention.Root())
	}
	if err := nilRetention.Release(ctx); !errors.Is(
		err,
		mpt.ErrReleasedRetention,
	) {
		t.Fatalf("nil retention Release() error = %v", err)
	}

	path := filepath.Join(t.TempDir(), "trie")
	store, err := Open(ctx, path, DefaultLimits())
	if err != nil {
		t.Fatalf("Open() error = %v", err)
	}
	trie := mustInternalFilesystemTrie(t)
	trie, err = trie.Commit(ctx, store)
	if err != nil {
		t.Fatalf("Commit() error = %v", err)
	}
	root, err := trie.Root()
	if err != nil {
		t.Fatalf("Root() error = %v", err)
	}
	if _, err := store.Retentions(ctx, 0); !errors.Is(
		err,
		mpt.ErrResourceLimit,
	) {
		t.Fatalf("Retentions(zero maximum, empty) error = %v", err)
	}
	busyNodePath := store.nodePath(root)
	hiddenBusyNodePath := busyNodePath + ".hidden"
	if err := os.Rename(busyNodePath, hiddenBusyNodePath); err != nil {
		t.Fatalf("Rename(busy node) error = %v", err)
	}
	store.committing = true
	if _, err := store.RetainRoot(
		ctx,
		root,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("RetainRoot(concurrent commit) error = %v", err)
	}
	store.committing = false
	store.retentionChanging = true
	if _, err := store.RetainRoot(
		ctx,
		root,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("RetainRoot(concurrent retention) error = %v", err)
	}
	store.retentionChanging = false
	store.pruning = true
	if _, err := store.RetainRoot(
		ctx,
		root,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("RetainRoot(concurrent prune) error = %v", err)
	}
	store.pruning = false
	if err := os.Rename(hiddenBusyNodePath, busyNodePath); err != nil {
		t.Fatalf("Restore(busy node) error = %v", err)
	}

	canceled, cancel := context.WithCancel(ctx)
	cancel()
	if _, err := store.RetainRoot(
		canceled,
		root,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrCanceled) {
		t.Fatalf("RetainRoot(canceled) error = %v", err)
	}
	if _, err := store.Retentions(
		canceled,
		1,
	); !errors.Is(err, mpt.ErrCanceled) {
		t.Fatalf("Retentions(canceled) error = %v", err)
	}
	if _, err := store.Prune(
		canceled,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrCanceled) {
		t.Fatalf("Prune(canceled) error = %v", err)
	}
	tooFewRetentions := mpt.DefaultReachabilityLimits()
	tooFewRetentions.MaxRetentions = 0
	store.retentions[retentionID{}] = root
	if _, err := store.Prune(
		ctx,
		tooFewRetentions,
	); !errors.Is(err, mpt.ErrResourceLimit) {
		t.Fatalf("Prune(retention bound) error = %v", err)
	}
	delete(store.retentions, retentionID{})

	originalRoot := store.root
	store.retentionCheckpoint = func(stage retentionStage) {
		if stage == retentionValidated {
			store.mutex.Lock()
			store.root = mpt.EmptyRoot()
			store.mutex.Unlock()
		}
	}
	if _, err := store.RetainRoot(
		ctx,
		root,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("RetainRoot(stale after validation) error = %v", err)
	}
	store.mutex.Lock()
	store.root = originalRoot
	store.mutex.Unlock()
	store.retentionCheckpoint = nil

	lease, err := store.RetainRoot(
		ctx,
		root,
		mpt.DefaultReachabilityLimits(),
	)
	if err != nil {
		t.Fatalf("RetainRoot() error = %v", err)
	}
	if _, err := store.Retentions(
		ctx,
		1,
	); err != nil {
		t.Fatalf("Retentions() error = %v", err)
	}
	exactRetentionLimit := mpt.DefaultReachabilityLimits()
	exactRetentionLimit.MaxRetentions = 1
	if _, err := store.Prune(ctx, exactRetentionLimit); err != nil {
		t.Fatalf("Prune(exact retention bound) error = %v", err)
	}
	retainedNodePath := store.nodePath(root)
	hiddenNodePath := retainedNodePath + ".hidden"
	if err := os.Rename(retainedNodePath, hiddenNodePath); err != nil {
		t.Fatalf("Rename(retained node) error = %v", err)
	}
	store.limits.MaxRetentions = 1
	if _, err := store.RetainRoot(
		ctx,
		root,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrResourceLimit) {
		t.Fatalf("RetainRoot(full before traversal) error = %v", err)
	}
	store.limits.MaxRetentions = DefaultLimits().MaxRetentions
	if err := os.Rename(hiddenNodePath, retainedNodePath); err != nil {
		t.Fatalf("Restore(retained node) error = %v", err)
	}
	if err := lease.Release(canceled); !errors.Is(err, mpt.ErrCanceled) {
		t.Fatalf("Release(canceled) error = %v", err)
	}
	store.committing = true
	if _, err := store.Prune(
		ctx,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("Prune(concurrent commit) error = %v", err)
	}
	if err := lease.Release(ctx); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("Release(concurrent commit) error = %v", err)
	}
	store.committing = false
	store.retentionChanging = true
	if _, err := store.Prune(
		ctx,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("Prune(concurrent retention) error = %v", err)
	}
	if err := lease.Release(ctx); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("Release(concurrent retention) error = %v", err)
	}
	store.retentionChanging = false
	store.pruning = true
	if err := lease.Release(ctx); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("Release(concurrent prune) error = %v", err)
	}
	store.pruning = false
	if err := lease.Release(ctx); err != nil {
		t.Fatalf("Release() error = %v", err)
	}
	if err := lease.Release(ctx); !errors.Is(
		err,
		mpt.ErrReleasedRetention,
	) {
		t.Fatalf("Release(second) error = %v", err)
	}

	store.pruning = true
	if _, err := store.RetainRoot(
		ctx,
		root,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("RetainRoot(pruning) error = %v", err)
	}
	if _, err := store.Prune(
		ctx,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("Prune(concurrent) error = %v", err)
	}
	if err := store.IterateNodes(
		ctx,
		DefaultLimits().MaxStoredNodes,
		func(mpt.Root, []byte) error { return nil },
	); !errors.Is(err, mpt.ErrStaleRoot) {
		t.Fatalf("IterateNodes(pruning) error = %v", err)
	}
	if err := store.Close(); !errors.Is(err, mpt.ErrStorageCommit) {
		t.Fatalf("Close(pruning) error = %v", err)
	}
	store.pruning = false

	if err := store.Close(); err != nil {
		t.Fatalf("Close() error = %v", err)
	}
	if _, err := store.RetainRoot(
		ctx,
		root,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrClosedStore) {
		t.Fatalf("RetainRoot(closed) error = %v", err)
	}
	if _, err := store.Retentions(
		ctx,
		1,
	); !errors.Is(err, mpt.ErrClosedStore) {
		t.Fatalf("Retentions(closed) error = %v", err)
	}
	if _, err := store.Prune(
		ctx,
		mpt.DefaultReachabilityLimits(),
	); !errors.Is(err, mpt.ErrClosedStore) {
		t.Fatalf("Prune(closed) error = %v", err)
	}
}

func TestRetentionPersistenceFailureBoundaries(t *testing.T) {
	t.Parallel()

	failure := errors.New("injected retention persistence failure")
	rollbackFailure := errors.New("injected retention rollback failure")
	for _, test := range []struct {
		name      string
		configure func(*Store)
		wantLease bool
		wantCause error
	}{
		{
			name: "identifier",
			configure: func(store *Store) {
				store.retentionOperations.newID = func(
					map[retentionID]mpt.Root,
				) (retentionID, error) {
					return retentionID{}, failure
				}
			},
		},
		{
			name: "write",
			configure: func(store *Store) {
				store.retentionOperations.writeAtomic = func(
					string,
					[]byte,
				) error {
					return failure
				}
			},
		},
		{
			name: "sync rollback",
			configure: func(store *Store) {
				calls := 0
				store.retentionOperations.syncDirectory = func(string) error {
					calls++
					if calls == 1 {
						return failure
					}
					return nil
				}
			},
		},
		{
			name: "sync rollback sync",
			configure: func(store *Store) {
				calls := 0
				store.retentionOperations.syncDirectory = func(string) error {
					calls++
					if calls == 1 {
						return failure
					}
					return rollbackFailure
				}
			},
			wantCause: rollbackFailure,
		},
		{
			name:      "sync rollback remove",
			wantLease: true,
			configure: func(store *Store) {
				store.retentionOperations.syncDirectory = func(string) error {
					return failure
				}
				store.retentionOperations.remove = func(string) error {
					return failure
				}
			},
		},
	} {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			store, root := openCommittedRetentionStore(t)
			defer func() {
				if closeErr := store.Close(); closeErr != nil {
					t.Errorf("Close() error = %v", closeErr)
				}
			}()
			test.configure(store)
			lease, err := store.RetainRoot(
				context.Background(),
				root,
				mpt.DefaultReachabilityLimits(),
			)
			if !errors.Is(err, mpt.ErrStorageCommit) {
				t.Fatalf("RetainRoot() error = %v", err)
			}
			if test.wantCause != nil && !errors.Is(err, test.wantCause) {
				t.Fatalf(
					"RetainRoot() error = %v, want cause %v",
					err,
					test.wantCause,
				)
			}
			if (lease != nil) != test.wantLease {
				t.Fatalf("RetainRoot() lease = %v, want non-nil %t", lease, test.wantLease)
			}
		})
	}

	t.Run("post-validation state", func(t *testing.T) {
		t.Parallel()

		for _, state := range []string{
			"closed",
			"committing",
			"retention",
			"pruning",
			"capacity",
			"canceled",
		} {
			state := state
			t.Run(state, func(t *testing.T) {
				t.Parallel()

				store, root := openCommittedRetentionStore(t)
				defer func() {
					store.closed = false
					store.committing = false
					store.retentionChanging = false
					store.pruning = false
					if closeErr := store.Close(); closeErr != nil {
						t.Errorf("Close() error = %v", closeErr)
					}
				}()
				ctx, cancel := context.WithCancel(context.Background())
				store.retentionCheckpoint = func(stage retentionStage) {
					if stage != retentionValidated {
						return
					}
					store.mutex.Lock()
					switch state {
					case "closed":
						store.closed = true
					case "committing":
						store.committing = true
					case "retention":
						store.retentionChanging = true
					case "pruning":
						store.pruning = true
					case "capacity":
						store.retentions[retentionID{}] = root
						store.limits.MaxRetentions = 1
					case "canceled":
						cancel()
					}
					store.mutex.Unlock()
				}
				_, err := store.RetainRoot(
					ctx,
					root,
					mpt.DefaultReachabilityLimits(),
				)
				switch state {
				case "closed":
					if !errors.Is(err, mpt.ErrClosedStore) {
						t.Fatalf("RetainRoot() error = %v", err)
					}
				case "committing", "retention", "pruning":
					if !errors.Is(err, mpt.ErrStaleRoot) {
						t.Fatalf("RetainRoot() error = %v", err)
					}
				case "capacity":
					if !errors.Is(err, mpt.ErrResourceLimit) {
						t.Fatalf("RetainRoot() error = %v", err)
					}
				case "canceled":
					if !errors.Is(err, mpt.ErrCanceled) {
						t.Fatalf("RetainRoot() error = %v", err)
					}
				}
			})
		}
	})

	t.Run("release failures", func(t *testing.T) {
		t.Parallel()

		for _, state := range []string{"missing", "remove", "sync"} {
			state := state
			t.Run(state, func(t *testing.T) {
				t.Parallel()

				store, root := openCommittedRetentionStore(t)
				lease, err := store.RetainRoot(
					context.Background(),
					root,
					mpt.DefaultReachabilityLimits(),
				)
				if err != nil {
					t.Fatalf("RetainRoot() error = %v", err)
				}
				store.retentionOperations = defaultRetentionOperations()
				switch state {
				case "missing":
					store.retentionOperations.remove = func(string) error {
						return os.ErrNotExist
					}
				case "remove":
					store.retentionOperations.remove = func(string) error {
						return failure
					}
				case "sync":
					store.retentionOperations.syncDirectory = func(string) error {
						return failure
					}
				}
				err = lease.Release(context.Background())
				if state == "missing" {
					if !errors.Is(err, mpt.ErrReleasedRetention) {
						t.Fatalf("Release() error = %v", err)
					}
				} else if !errors.Is(err, mpt.ErrStorageCommit) {
					t.Fatalf("Release() error = %v", err)
				}
				store.retentionOperations = defaultRetentionOperations()
				if closeErr := store.Close(); closeErr != nil {
					t.Fatalf("Close() error = %v", closeErr)
				}
			})
		}
	})
}

func TestPruneRecoveryRejectsConflictsAndRestoresPendingNodes(t *testing.T) {
	t.Parallel()

	ctx := context.Background()
	base := t.TempDir()
	nodes := filepath.Join(base, nodeDirectory)
	if err := os.Mkdir(nodes, 0o700); err != nil {
		t.Fatalf("Mkdir(nodes) error = %v", err)
	}
	pending := filepath.Join(base, prunePendingDirectory)
	committed := filepath.Join(base, pruneCommittedDirectory)
	if err := os.Mkdir(pending, 0o700); err != nil {
		t.Fatalf("Mkdir(pending) error = %v", err)
	}
	if err := os.Mkdir(committed, 0o700); err != nil {
		t.Fatalf("Mkdir(committed) error = %v", err)
	}
	if err := recoverPruneArtifacts(
		ctx,
		base,
		nodes,
		DefaultLimits(),
	); !errors.Is(err, mpt.ErrCorruptNode) {
		t.Fatalf("recoverPruneArtifacts(conflict) error = %v", err)
	}
	if err := os.Remove(committed); err != nil {
		t.Fatalf("Remove(committed) error = %v", err)
	}

	commit := captureCommit(t)
	node := commit.Nodes()[0]
	hash := node.Hash()
	name := hex.EncodeToString(hash[:])
	if err := os.WriteFile(
		filepath.Join(pending, name),
		node.Encoded(),
		0o600,
	); err != nil {
		t.Fatalf("WriteFile(pending node) error = %v", err)
	}
	if err := recoverPruneArtifacts(
		ctx,
		base,
		nodes,
		DefaultLimits(),
	); err != nil {
		t.Fatalf("recoverPruneArtifacts(pending) error = %v", err)
	}
	if encoded, err := os.ReadFile(filepath.Join(nodes, name)); err != nil ||
		!bytes.Equal(encoded, node.Encoded()) {
		t.Fatalf("restored node = (%x, %v)", encoded, err)
	}

	if exists, err := directoryExists(filepath.Join(base, "missing")); err != nil || exists {
		t.Fatalf("directoryExists(missing) = (%t, %v)", exists, err)
	}
	if exists, err := directoryExists(nodes); err != nil || !exists {
		t.Fatalf("directoryExists(nodes) = (%t, %v)", exists, err)
	}
	regular := filepath.Join(base, "regular")
	if err := os.WriteFile(regular, []byte("x"), 0o600); err != nil {
		t.Fatalf("WriteFile(regular) error = %v", err)
	}
	if _, err := directoryExists(regular); err == nil {
		t.Fatal("directoryExists(regular) error = nil")
	}
	link := filepath.Join(base, "link")
	if err := os.Symlink(nodes, link); err != nil {
		t.Fatalf("Symlink() error = %v", err)
	}
	if _, err := directoryExists(link); err == nil {
		t.Fatal("directoryExists(symlink) error = nil")
	}

	source := filepath.Join(base, "source")
	target := filepath.Join(base, "target")
	if err := os.WriteFile(source, []byte("same"), 0o600); err != nil {
		t.Fatalf("WriteFile(source) error = %v", err)
	}
	if err := os.WriteFile(target, []byte("same"), 0o600); err != nil {
		t.Fatalf("WriteFile(target) error = %v", err)
	}
	if err := restorePrunedNode(source, target, 4); err != nil {
		t.Fatalf("restorePrunedNode(equal) error = %v", err)
	}
	if _, err := os.Lstat(source); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("equal source still exists: %v", err)
	}
	if err := os.WriteFile(source, []byte("left"), 0o600); err != nil {
		t.Fatalf("WriteFile(conflicting source) error = %v", err)
	}
	if err := os.WriteFile(target, []byte("right"), 0o600); err != nil {
		t.Fatalf("WriteFile(conflicting target) error = %v", err)
	}
	if err := restorePrunedNode(source, target, 5); err == nil {
		t.Fatal("restorePrunedNode(conflict) error = nil")
	}
	if err := restorePrunedNode(
		filepath.Join(base, "missing-source"),
		filepath.Join(base, "missing-target"),
		1,
	); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("restorePrunedNode(missing) error = %v", err)
	}
	if _, err := readPruneEntries(
		filepath.Join(base, "missing-prune"),
		1,
	); err == nil {
		t.Fatal("readPruneEntries(missing) error = nil")
	}
	invalidPrune := filepath.Join(base, "invalid-prune")
	if err := os.Mkdir(invalidPrune, 0o700); err != nil {
		t.Fatalf("Mkdir(invalid prune) error = %v", err)
	}
	if err := os.WriteFile(
		filepath.Join(invalidPrune, "invalid"),
		[]byte("x"),
		0o600,
	); err != nil {
		t.Fatalf("WriteFile(invalid prune) error = %v", err)
	}
	if _, err := readPruneEntries(
		invalidPrune,
		1,
	); !errors.Is(err, mpt.ErrCorruptNode) {
		t.Fatalf("readPruneEntries(invalid) error = %v", err)
	}
	if err := removeCommittedPrune(
		filepath.Join(base, "missing-prune"),
		1,
	); err == nil {
		t.Fatal("removeCommittedPrune(missing) error = nil")
	}

	operations := defaultPruneOperations()
	failure := errors.New("injected restore failure")
	operations.lstat = func(string) (os.FileInfo, error) {
		return nil, failure
	}
	if err := restorePrunedNodeWith(
		source,
		target,
		5,
		operations,
	); !errors.Is(err, failure) {
		t.Fatalf("restorePrunedNodeWith(stat failure) error = %v", err)
	}
	operations = defaultPruneOperations()
	readCalls := 0
	operations.readFile = func(path string, maximum int) ([]byte, error) {
		readCalls++
		if readCalls == 1 {
			return nil, failure
		}
		return readBoundedFile(path, maximum)
	}
	if err := restorePrunedNodeWith(
		source,
		target,
		5,
		operations,
	); !errors.Is(err, failure) {
		t.Fatalf("restorePrunedNodeWith(source read failure) error = %v", err)
	}
	operations = defaultPruneOperations()
	readCalls = 0
	operations.readFile = func(path string, maximum int) ([]byte, error) {
		readCalls++
		if readCalls == 2 {
			return nil, failure
		}
		return readBoundedFile(path, maximum)
	}
	if err := restorePrunedNodeWith(
		source,
		target,
		5,
		operations,
	); !errors.Is(err, failure) {
		t.Fatalf("restorePrunedNodeWith(target read failure) error = %v", err)
	}

	restoreBase, restoreNodes, restoreHash := preparePruneStage(t)
	restorePending := filepath.Join(restoreBase, prunePendingDirectory)
	if err := os.Mkdir(restorePending, 0o700); err != nil {
		t.Fatalf("Mkdir(restore pending) error = %v", err)
	}
	restoreName := hex.EncodeToString(restoreHash[:])
	if err := os.Rename(
		filepath.Join(restoreNodes, restoreName),
		filepath.Join(restorePending, restoreName),
	); err != nil {
		t.Fatalf("Rename(restore node) error = %v", err)
	}
	operations = defaultPruneOperations()
	operations.rename = func(string, string) error { return failure }
	if err := restorePendingPrune(
		restoreNodes,
		restorePending,
		1,
		DefaultLimits().MaxNodeBytes,
		operations,
	); !errors.Is(err, failure) {
		t.Fatalf("restorePendingPrune(rename failure) error = %v", err)
	}
}

func TestStagePruneRollsBackCancellationAndMoveFailures(t *testing.T) {
	t.Parallel()

	ctx := context.Background()
	base := t.TempDir()
	nodes := filepath.Join(base, nodeDirectory)
	if err := os.Mkdir(nodes, 0o700); err != nil {
		t.Fatalf("Mkdir(nodes) error = %v", err)
	}
	commit := captureCommit(t)
	node := commit.Nodes()[0]
	hash := node.Hash()
	name := hex.EncodeToString(hash[:])
	nodePath := filepath.Join(nodes, name)
	if err := os.WriteFile(nodePath, node.Encoded(), 0o600); err != nil {
		t.Fatalf("WriteFile(node) error = %v", err)
	}

	canceled, cancel := context.WithCancel(ctx)
	cancel()
	committed, err := stagePrune(
		canceled,
		base,
		nodes,
		[]mpt.Root{hash},
		2,
		DefaultLimits().MaxNodeBytes,
		func(pruneStage) {},
		defaultPruneOperations(),
	)
	if committed || !errors.Is(err, mpt.ErrCanceled) {
		t.Fatalf("stagePrune(canceled) = (%t, %v)", committed, err)
	}
	if errors.Is(err, mpt.ErrStorageCommit) {
		t.Fatalf("stagePrune(canceled) added storage failure: %v", err)
	}
	if _, err := os.Lstat(nodePath); err != nil {
		t.Fatalf("canceled prune lost node: %v", err)
	}

	cancelAfterStage, cancel := context.WithCancel(ctx)
	committed, err = stagePrune(
		cancelAfterStage,
		base,
		nodes,
		[]mpt.Root{hash},
		2,
		DefaultLimits().MaxNodeBytes,
		func(stage pruneStage) {
			if stage == pruneNodesStaged {
				cancel()
			}
		},
		defaultPruneOperations(),
	)
	if committed || !errors.Is(err, mpt.ErrCanceled) {
		t.Fatalf("stagePrune(cancel after stage) = (%t, %v)", committed, err)
	}
	if errors.Is(err, mpt.ErrStorageCommit) {
		t.Fatalf("stagePrune(cancel after stage) added storage failure: %v", err)
	}
	if _, err := os.Lstat(nodePath); err != nil {
		t.Fatalf("staged canceled prune lost node: %v", err)
	}

	var missing mpt.Root
	missing[0] = 1
	if committed, err := stagePrune(
		ctx,
		base,
		nodes,
		[]mpt.Root{missing},
		2,
		DefaultLimits().MaxNodeBytes,
		func(pruneStage) {},
		defaultPruneOperations(),
	); committed || !errors.Is(err, mpt.ErrStorageCommit) {
		t.Fatalf("stagePrune(missing node) = (%t, %v)", committed, err)
	}
	if err := os.Mkdir(
		filepath.Join(base, prunePendingDirectory),
		0o700,
	); err != nil {
		t.Fatalf("Mkdir(existing pending) error = %v", err)
	}
	if committed, err := stagePrune(
		ctx,
		base,
		nodes,
		[]mpt.Root{hash},
		2,
		DefaultLimits().MaxNodeBytes,
		func(pruneStage) {},
		defaultPruneOperations(),
	); committed || !errors.Is(err, mpt.ErrStorageCommit) {
		t.Fatalf("stagePrune(existing pending) = (%t, %v)", committed, err)
	}
}

func TestStagePrunePropagatesEveryFilesystemFailure(t *testing.T) {
	t.Parallel()

	failure := errors.New("injected prune filesystem failure")
	for _, stage := range []string{
		"mkdir",
		"initial sync",
		"initial sync rollback",
		"node rename",
		"node sync",
		"pending sync",
		"commit rename",
		"committed sync",
		"cleanup read",
		"cleanup remove",
		"final sync",
	} {
		stage := stage
		t.Run(stage, func(t *testing.T) {
			t.Parallel()

			base, nodes, hash := preparePruneStage(t)
			operations := defaultPruneOperations()
			syncCalls := 0
			switch stage {
			case "mkdir":
				operations.mkdir = func(string, os.FileMode) error {
					return failure
				}
			case "initial sync":
				operations.syncDirectory = func(path string) error {
					syncCalls++
					if syncCalls == 1 {
						return failure
					}
					return syncDirectory(path)
				}
			case "initial sync rollback":
				operations.syncDirectory = func(string) error {
					return failure
				}
			case "node rename":
				operations.rename = func(source, target string) error {
					if filepath.Dir(source) == nodes {
						return failure
					}
					return os.Rename(source, target)
				}
			case "node sync":
				operations.syncDirectory = func(path string) error {
					syncCalls++
					if syncCalls == 2 {
						return failure
					}
					return syncDirectory(path)
				}
			case "pending sync":
				operations.syncDirectory = func(path string) error {
					syncCalls++
					if syncCalls == 3 {
						return failure
					}
					return syncDirectory(path)
				}
			case "commit rename":
				operations.rename = func(source, target string) error {
					if filepath.Base(source) == prunePendingDirectory {
						return failure
					}
					return os.Rename(source, target)
				}
			case "committed sync":
				operations.syncDirectory = func(path string) error {
					syncCalls++
					if syncCalls == 4 {
						return failure
					}
					return syncDirectory(path)
				}
			case "cleanup read":
				operations.readDirectory = func(path string, maximum int) (
					[]os.DirEntry,
					error,
				) {
					if filepath.Base(path) == pruneCommittedDirectory {
						return nil, failure
					}
					return readDirectoryBounded(path, maximum)
				}
			case "cleanup remove":
				operations.remove = func(path string) error {
					if filepath.Dir(path) != base {
						return failure
					}
					return os.Remove(path)
				}
			case "final sync":
				operations.syncDirectory = func(path string) error {
					syncCalls++
					if syncCalls == 5 {
						return failure
					}
					return syncDirectory(path)
				}
			}
			committed, err := stagePrune(
				context.Background(),
				base,
				nodes,
				[]mpt.Root{hash},
				2,
				DefaultLimits().MaxNodeBytes,
				func(pruneStage) {},
				operations,
			)
			wantCommitted := stage == "committed sync" ||
				stage == "cleanup read" ||
				stage == "cleanup remove" ||
				stage == "final sync"
			if committed != wantCommitted ||
				!errors.Is(err, mpt.ErrStorageCommit) {
				t.Fatalf(
					"stagePrune() = (%t, %v), want (%t, storage error)",
					committed,
					err,
					wantCommitted,
				)
			}
		})
	}
}

func TestPruneReportsPreAndPostCommitFailures(t *testing.T) {
	t.Parallel()

	failure := errors.New("injected prune failure")
	for _, postCommit := range []bool{false, true} {
		postCommit := postCommit
		t.Run(map[bool]string{false: "pre-commit", true: "post-commit"}[postCommit], func(t *testing.T) {
			t.Parallel()

			store, oldRoot, currentRoot := openStoreWithUnreachableRoot(t)
			defer func() {
				store.pruneOperations = defaultPruneOperations()
				if closeErr := store.Close(); closeErr != nil {
					t.Errorf("Close() error = %v", closeErr)
				}
			}()
			if postCommit {
				syncCalls := 0
				store.pruneOperations.syncDirectory = func(path string) error {
					syncCalls++
					if syncCalls == 4 {
						return failure
					}
					return syncDirectory(path)
				}
			} else {
				store.pruneOperations.mkdir = func(string, os.FileMode) error {
					return failure
				}
			}
			result, err := store.Prune(
				context.Background(),
				mpt.DefaultReachabilityLimits(),
			)
			if !errors.Is(err, mpt.ErrStorageCommit) {
				t.Fatalf("Prune() error = %v", err)
			}
			if postCommit {
				if result.RemovedNodes() == 0 {
					t.Fatal("post-commit Prune() did not report removed nodes")
				}
				if _, err := store.GetNode(
					context.Background(),
					oldRoot,
				); !errors.Is(err, mpt.ErrMissingNode) {
					t.Fatalf("GetNode(pruned old root) error = %v", err)
				}
			} else {
				if result.RemovedNodes() != 0 {
					t.Fatalf("pre-commit Prune() removed %d nodes", result.RemovedNodes())
				}
				if _, err := store.GetNode(
					context.Background(),
					oldRoot,
				); err != nil {
					t.Fatalf("GetNode(preserved old root) error = %v", err)
				}
			}
			if _, err := store.GetNode(
				context.Background(),
				currentRoot,
			); err != nil {
				t.Fatalf("GetNode(current root) error = %v", err)
			}
		})
	}
}

func TestPruneRejectsRecoveryReachabilityAndInventoryFailures(t *testing.T) {
	t.Parallel()

	failure := errors.New("injected prune boundary failure")
	t.Run("recovery", func(t *testing.T) {
		t.Parallel()

		store, _ := openCommittedRetentionStore(t)
		defer func() {
			store.pruneOperations = defaultPruneOperations()
			if closeErr := store.Close(); closeErr != nil {
				t.Errorf("Close() error = %v", closeErr)
			}
		}()
		store.pruneOperations.lstat = func(path string) (os.FileInfo, error) {
			if filepath.Base(path) == prunePendingDirectory {
				return nil, failure
			}
			return os.Lstat(path)
		}
		if _, err := store.Prune(
			context.Background(),
			mpt.DefaultReachabilityLimits(),
		); !errors.Is(err, mpt.ErrStorageRead) {
			t.Fatalf("Prune(recovery failure) error = %v", err)
		}
	})
	t.Run("missing published root", func(t *testing.T) {
		t.Parallel()

		store, err := Open(
			context.Background(),
			filepath.Join(t.TempDir(), "trie"),
			DefaultLimits(),
		)
		if err != nil {
			t.Fatalf("Open() error = %v", err)
		}
		defer func() {
			if closeErr := store.Close(); closeErr != nil {
				t.Errorf("Close() error = %v", closeErr)
			}
		}()
		store.root[0] = 1
		if _, err := store.Prune(
			context.Background(),
			mpt.DefaultReachabilityLimits(),
		); !errors.Is(err, mpt.ErrMissingNode) {
			t.Fatalf("Prune(missing root) error = %v", err)
		}
	})
	t.Run("inventory", func(t *testing.T) {
		t.Parallel()

		store, _ := openCommittedRetentionStore(t)
		defer func() {
			store.pruneOperations = defaultPruneOperations()
			if closeErr := store.Close(); closeErr != nil {
				t.Errorf("Close() error = %v", closeErr)
			}
		}()
		store.pruneOperations.readDirectory = func(string, int) (
			[]os.DirEntry,
			error,
		) {
			return nil, failure
		}
		if _, err := store.Prune(
			context.Background(),
			mpt.DefaultReachabilityLimits(),
		); !errors.Is(err, mpt.ErrStorageRead) {
			t.Fatalf("Prune(inventory failure) error = %v", err)
		}
	})
}

func TestUnreachableNodeInventoryRejectsEveryHostileBoundary(t *testing.T) {
	t.Parallel()

	failure := errors.New("injected unreachable inventory failure")
	for _, state := range []string{
		"resource",
		"read directory",
		"canceled",
		"invalid name",
		"read node",
		"hash mismatch",
		"count mismatch",
	} {
		state := state
		t.Run(state, func(t *testing.T) {
			t.Parallel()

			nodes := t.TempDir()
			store := &Store{
				nodesPath:       nodes,
				limits:          DefaultLimits(),
				pruneOperations: defaultPruneOperations(),
			}
			ctx := context.Background()
			node := captureCommit(t).Nodes()[0]
			hash := node.Hash()
			name := hex.EncodeToString(hash[:])
			content := node.Encoded()
			switch state {
			case "resource":
				store.pruneOperations.readDirectory = func(string, int) (
					[]os.DirEntry,
					error,
				) {
					return nil, mpt.ErrResourceLimit
				}
			case "read directory":
				store.pruneOperations.readDirectory = func(string, int) (
					[]os.DirEntry,
					error,
				) {
					return nil, failure
				}
			case "canceled":
				canceled, cancel := context.WithCancel(ctx)
				cancel()
				ctx = canceled
			case "invalid name":
				name = "invalid"
			case "read node":
				store.pruneOperations.readFile = func(string, int) ([]byte, error) {
					return nil, failure
				}
			case "hash mismatch":
				content = append([]byte(nil), content...)
				content[0] ^= 0xff
			case "count mismatch":
				store.storedNodes = 2
			}
			if state != "resource" && state != "read directory" {
				if err := os.WriteFile(
					filepath.Join(nodes, name),
					content,
					0o600,
				); err != nil {
					t.Fatalf("WriteFile(node) error = %v", err)
				}
				if state != "count mismatch" {
					store.storedNodes = 1
				}
			}
			_, _, err := store.unreachableNodes(
				ctx,
				map[mpt.Root]struct{}{},
			)
			switch state {
			case "resource":
				if !errors.Is(err, mpt.ErrResourceLimit) {
					t.Fatalf("unreachableNodes() error = %v", err)
				}
			case "read directory", "read node":
				if !errors.Is(err, mpt.ErrStorageRead) {
					t.Fatalf("unreachableNodes() error = %v", err)
				}
			case "canceled":
				if !errors.Is(err, mpt.ErrCanceled) {
					t.Fatalf("unreachableNodes() error = %v", err)
				}
			default:
				if !errors.Is(err, mpt.ErrCorruptNode) {
					t.Fatalf("unreachableNodes() error = %v", err)
				}
			}
		})
	}
}

func TestUnreachableNodeInventoryReportsExactBytes(t *testing.T) {
	t.Parallel()

	nodes := t.TempDir()
	stored := captureCommit(t).Nodes()
	if len(stored) < 2 {
		t.Fatalf("captureCommit() nodes = %d, want at least 2", len(stored))
	}
	expected := make(map[mpt.Root]struct{}, 2)
	var expectedBytes uint64
	for _, node := range stored[:2] {
		hash := node.Hash()
		encoded := node.Encoded()
		if err := os.WriteFile(
			filepath.Join(nodes, hex.EncodeToString(hash[:])),
			encoded,
			0o600,
		); err != nil {
			t.Fatalf("WriteFile(node) error = %v", err)
		}
		expected[hash] = struct{}{}
		expectedBytes += uint64(len(encoded))
	}
	store := &Store{
		nodesPath:       nodes,
		limits:          DefaultLimits(),
		storedNodes:     2,
		pruneOperations: defaultPruneOperations(),
	}
	unreachable, removedBytes, err := store.unreachableNodes(
		context.Background(),
		map[mpt.Root]struct{}{},
	)
	if err != nil {
		t.Fatalf("unreachableNodes() error = %v", err)
	}
	if len(unreachable) != len(expected) {
		t.Fatalf(
			"unreachableNodes() hashes = %x, want %d",
			unreachable,
			len(expected),
		)
	}
	for _, hash := range unreachable {
		if _, exists := expected[hash]; !exists {
			t.Fatalf("unreachableNodes() unexpected hash = %x", hash)
		}
	}
	if removedBytes != expectedBytes {
		t.Fatalf(
			"unreachableNodes() removed bytes = %d, want %d",
			removedBytes,
			expectedBytes,
		)
	}
}

func TestRecoverPruneArtifactsPropagatesEveryFailure(t *testing.T) {
	t.Parallel()

	failure := errors.New("injected prune recovery failure")
	for _, stage := range []string{
		"pending stat",
		"committed stat",
		"canceled",
		"pending restore",
		"pending sync",
		"committed remove",
		"committed sync",
	} {
		stage := stage
		t.Run(stage, func(t *testing.T) {
			t.Parallel()

			base := t.TempDir()
			nodes := filepath.Join(base, nodeDirectory)
			if err := os.Mkdir(nodes, 0o700); err != nil {
				t.Fatalf("Mkdir(nodes) error = %v", err)
			}
			operations := defaultPruneOperations()
			ctx := context.Background()
			switch stage {
			case "pending stat":
				operations.lstat = func(path string) (os.FileInfo, error) {
					if filepath.Base(path) == prunePendingDirectory {
						return nil, failure
					}
					return os.Lstat(path)
				}
			case "committed stat":
				operations.lstat = func(path string) (os.FileInfo, error) {
					if filepath.Base(path) == pruneCommittedDirectory {
						return nil, failure
					}
					return os.Lstat(path)
				}
			case "canceled":
				canceled, cancel := context.WithCancel(ctx)
				cancel()
				ctx = canceled
			case "pending restore", "pending sync":
				pending := filepath.Join(base, prunePendingDirectory)
				if err := os.Mkdir(pending, 0o700); err != nil {
					t.Fatalf("Mkdir(pending) error = %v", err)
				}
				if stage == "pending restore" {
					operations.readDirectory = func(string, int) (
						[]os.DirEntry,
						error,
					) {
						return nil, failure
					}
				} else {
					syncCalls := 0
					operations.syncDirectory = func(path string) error {
						syncCalls++
						if syncCalls == 2 {
							return failure
						}
						return syncDirectory(path)
					}
				}
			case "committed remove", "committed sync":
				committed := filepath.Join(base, pruneCommittedDirectory)
				if err := os.Mkdir(committed, 0o700); err != nil {
					t.Fatalf("Mkdir(committed) error = %v", err)
				}
				if stage == "committed remove" {
					operations.remove = func(string) error {
						return failure
					}
				} else {
					operations.syncDirectory = func(string) error {
						return failure
					}
				}
			}
			err := recoverPruneArtifacts(
				ctx,
				base,
				nodes,
				DefaultLimits(),
				operations,
			)
			if stage == "canceled" {
				if !errors.Is(err, mpt.ErrCanceled) {
					t.Fatalf("recoverPruneArtifacts() error = %v", err)
				}
			} else if !errors.Is(err, mpt.ErrStorageRead) &&
				!errors.Is(err, mpt.ErrStorageCommit) {
				t.Fatalf("recoverPruneArtifacts() error = %v", err)
			}
		})
	}
}

func recordForRoot(root mpt.Root) []byte {
	return encodeRetentionRecord(root)
}

func mustInternalFilesystemTrie(t *testing.T) mpt.RawTrie {
	t.Helper()

	trie, err := mpt.NewRawTrie(mpt.DefaultLimits())
	if err != nil {
		t.Fatalf("NewRawTrie() error = %v", err)
	}
	trie, err = trie.Update(
		context.Background(),
		[]byte("key"),
		[]byte("persistent value long enough to store"),
	)
	if err != nil {
		t.Fatalf("Update() error = %v", err)
	}
	return trie
}

func openCommittedRetentionStore(t *testing.T) (*Store, mpt.Root) {
	t.Helper()

	store, err := Open(
		context.Background(),
		filepath.Join(t.TempDir(), "trie"),
		DefaultLimits(),
	)
	if err != nil {
		t.Fatalf("Open() error = %v", err)
	}
	trie := mustInternalFilesystemTrie(t)
	trie, err = trie.Commit(context.Background(), store)
	if err != nil {
		t.Fatalf("Commit() error = %v", err)
	}
	root, err := trie.Root()
	if err != nil {
		t.Fatalf("Root() error = %v", err)
	}
	return store, root
}

func preparePruneStage(t *testing.T) (string, string, mpt.Root) {
	t.Helper()

	base := t.TempDir()
	nodes := filepath.Join(base, nodeDirectory)
	if err := os.Mkdir(nodes, 0o700); err != nil {
		t.Fatalf("Mkdir(nodes) error = %v", err)
	}
	node := captureCommit(t).Nodes()[0]
	hash := node.Hash()
	if err := os.WriteFile(
		filepath.Join(nodes, hex.EncodeToString(hash[:])),
		node.Encoded(),
		0o600,
	); err != nil {
		t.Fatalf("WriteFile(node) error = %v", err)
	}
	return base, nodes, hash
}

func openStoreWithUnreachableRoot(t *testing.T) (*Store, mpt.Root, mpt.Root) {
	t.Helper()

	ctx := context.Background()
	store, err := Open(
		ctx,
		filepath.Join(t.TempDir(), "trie"),
		DefaultLimits(),
	)
	if err != nil {
		t.Fatalf("Open() error = %v", err)
	}
	trie, err := mpt.NewRawTrie(mpt.DefaultLimits())
	if err != nil {
		t.Fatalf("NewRawTrie() error = %v", err)
	}
	trie, err = trie.Update(
		ctx,
		[]byte("old"),
		[]byte("old persistent value long enough to store"),
	)
	if err != nil {
		t.Fatalf("Update(old) error = %v", err)
	}
	trie, err = trie.Commit(ctx, store)
	if err != nil {
		t.Fatalf("Commit(old) error = %v", err)
	}
	oldRoot, err := trie.Root()
	if err != nil {
		t.Fatalf("Root(old) error = %v", err)
	}
	trie, err = trie.Delete(ctx, []byte("old"))
	if err != nil {
		t.Fatalf("Delete(old) error = %v", err)
	}
	trie, err = trie.Update(
		ctx,
		[]byte("current"),
		[]byte("current persistent value long enough to store"),
	)
	if err != nil {
		t.Fatalf("Update(current) error = %v", err)
	}
	trie, err = trie.Commit(ctx, store)
	if err != nil {
		t.Fatalf("Commit(current) error = %v", err)
	}
	currentRoot, err := trie.Root()
	if err != nil {
		t.Fatalf("Root(current) error = %v", err)
	}
	return store, oldRoot, currentRoot
}
