// Code generated by backend error fixture. DO NOT EDIT.

package boundary

import "backend"

func Generated() (string, error) {
	return backend.Load() // want `api/backend-error-boundary: backend.Load result 2 crosses exported boundary boundary.Generated`
}
