// Package business provides immutable, versioned, and bounded business
// calendars supplied by applications.
package business

import (
	"errors"
	"fmt"
	"time"
	"unicode/utf8"

	calendar "github.com/faustbrian/golib/pkg/calendar"
)

const (
	// MaxHolidays bounds holidays accepted by one calendar.
	MaxHolidays = 10_000
	// MaxHolidayNameBytes bounds a holiday name.
	MaxHolidayNameBytes = 256
	// MaxMetadataEntries bounds metadata attached to one holiday.
	MaxMetadataEntries = 32
	// MaxProvenanceFieldBytes bounds each provenance identity field.
	MaxProvenanceFieldBytes = 1024
	maxRevisionBytes        = 128
	maxMetadataKey          = 128
	maxMetadataValue        = 1024
)

var (
	// ErrInvalidCalendar identifies missing identity or malformed configuration.
	ErrInvalidCalendar = errors.New("calendar/business: invalid calendar")
	// ErrInvalidHoliday identifies malformed holiday data.
	ErrInvalidHoliday = errors.New("calendar/business: invalid holiday")
	// ErrResourceLimit identifies bounded input that exceeds its limit.
	ErrResourceLimit = errors.New("calendar/business: resource limit exceeded")
	// ErrSearchLimit identifies a business-day operation that exhausted its
	// explicit iteration budget.
	ErrSearchLimit = errors.New("calendar/business: search limit exceeded")
)

// Holiday is immutable named holiday data. Metadata access returns a copy.
type Holiday struct {
	date       calendar.Date
	name       string
	metadata   map[string]string
	sourceDate calendar.Date
	observed   bool
}

// NewHoliday validates and copies holiday data.
func NewHoliday(date calendar.Date, name string, metadata map[string]string) (Holiday, error) {
	if !date.IsValid() || name == "" || len(name) > MaxHolidayNameBytes || !utf8.ValidString(name) {
		return Holiday{}, ErrInvalidHoliday
	}
	copyMetadata, err := cloneMetadata(metadata)
	if err != nil {
		return Holiday{}, err
	}
	return Holiday{date: date, name: name, metadata: copyMetadata}, nil
}

// MustHoliday is NewHoliday but panics for invalid data.
func MustHoliday(date calendar.Date, name string, metadata map[string]string) Holiday {
	holiday, err := NewHoliday(date, name, metadata)
	if err != nil {
		panic(err)
	}
	return holiday
}

// Date returns the holiday's effective date.
func (h Holiday) Date() calendar.Date { return h.date }

// Name returns the bounded display name.
func (h Holiday) Name() string { return h.name }

// Metadata returns a caller-owned copy of partial application metadata.
func (h Holiday) Metadata() map[string]string {
	result := make(map[string]string, len(h.metadata))
	for key, value := range h.metadata {
		result[key] = value
	}
	return result
}

// IsObserved reports whether this entry was generated by an observance policy.
func (h Holiday) IsObserved() bool { return h.observed }

// SourceDate returns the original holiday date for an observed entry.
func (h Holiday) SourceDate() (calendar.Date, bool) { return h.sourceDate, h.observed }

// Provenance records optional origin and licensing data for supplied datasets.
type Provenance struct {
	Provider         string
	Source           string
	License          string
	EffectiveVersion string
	Checksum         string
}

// Config constructs an immutable Calendar.
type Config struct {
	Revision   string
	Weekends   []time.Weekday
	Holidays   []Holiday
	Provenance Provenance
}

// Calendar is an immutable weekend and holiday policy with revision identity.
// It is safe for concurrent reads after construction.
type Calendar struct {
	revision   string
	weekends   [7]bool
	holidays   map[calendar.Date][]Holiday
	provenance Provenance
}

// NewCalendar validates and deeply copies config.
func NewCalendar(config Config) (Calendar, error) {
	if config.Revision == "" || len(config.Revision) > maxRevisionBytes || !utf8.ValidString(config.Revision) {
		return Calendar{}, ErrInvalidCalendar
	}
	if len(config.Holidays) > MaxHolidays {
		return Calendar{}, ErrResourceLimit
	}
	for _, field := range []string{config.Provenance.Provider, config.Provenance.Source, config.Provenance.License, config.Provenance.EffectiveVersion, config.Provenance.Checksum} {
		if len(field) > MaxProvenanceFieldBytes {
			return Calendar{}, ErrResourceLimit
		}
		if !utf8.ValidString(field) {
			return Calendar{}, ErrInvalidCalendar
		}
	}
	result := Calendar{
		revision:   config.Revision,
		holidays:   make(map[calendar.Date][]Holiday, len(config.Holidays)),
		provenance: config.Provenance,
	}
	for _, weekday := range config.Weekends {
		if weekday < time.Sunday || weekday > time.Saturday {
			return Calendar{}, ErrInvalidCalendar
		}
		result.weekends[weekday] = true
	}
	for _, holiday := range config.Holidays {
		copyHoliday, err := NewHoliday(holiday.date, holiday.name, holiday.metadata)
		if err != nil {
			return Calendar{}, err
		}
		copyHoliday.sourceDate = holiday.sourceDate
		copyHoliday.observed = holiday.observed
		result.holidays[copyHoliday.date] = append(result.holidays[copyHoliday.date], copyHoliday)
	}
	return result, nil
}

// Revision returns the application-supplied version identity.
func (c Calendar) Revision() string { return c.revision }

// IsValid reports whether c was constructed by NewCalendar.
func (c Calendar) IsValid() bool { return c.revision != "" && c.holidays != nil }

// Provenance returns the dataset provenance value.
func (c Calendar) Provenance() Provenance { return c.provenance }

// IsWeekend reports whether d's weekday is configured as a weekend.
func (c Calendar) IsWeekend(d calendar.Date) bool {
	return c.IsValid() && d.IsValid() && c.weekends[d.Weekday()]
}

// IsHoliday reports whether one or more holidays occur on d.
func (c Calendar) IsHoliday(d calendar.Date) bool {
	return c.IsValid() && d.IsValid() && len(c.holidays[d]) != 0
}

// IsBusinessDay reports whether d is valid and is neither weekend nor holiday.
func (c Calendar) IsBusinessDay(d calendar.Date) bool {
	return c.IsValid() && d.IsValid() && !c.IsWeekend(d) && !c.IsHoliday(d)
}

// Holidays returns immutable copies of all holidays on d, preserving overlaps.
func (c Calendar) Holidays(d calendar.Date) []Holiday {
	source := c.holidays[d]
	result := make([]Holiday, len(source))
	for i, holiday := range source {
		result[i], _ = NewHoliday(holiday.date, holiday.name, holiday.metadata)
		result[i].sourceDate = holiday.sourceDate
		result[i].observed = holiday.observed
	}
	return result
}

// NextBusinessDay returns the first business date strictly after d.
func (c Calendar) NextBusinessDay(d calendar.Date, searchLimit int) (calendar.Date, error) {
	return c.search(d, 1, searchLimit)
}

// PreviousBusinessDay returns the first business date strictly before d.
func (c Calendar) PreviousBusinessDay(d calendar.Date, searchLimit int) (calendar.Date, error) {
	return c.search(d, -1, searchLimit)
}

// AddBusinessDays moves by count admitted dates, excluding the starting date.
func (c Calendar) AddBusinessDays(d calendar.Date, count, searchLimit int) (calendar.Date, error) {
	if !d.IsValid() {
		return calendar.Date{}, calendar.ErrInvalidDate
	}
	if searchLimit <= 0 {
		return calendar.Date{}, ErrSearchLimit
	}
	if count == 0 {
		return d, nil
	}
	direction := 1
	if count < 0 {
		if count == -int(^uint(0)>>1)-1 {
			return calendar.Date{}, ErrSearchLimit
		}
		direction = -1
		count = -count
	}
	current := d
	visited := 0
	for admitted := 0; admitted < count; {
		if visited >= searchLimit {
			return calendar.Date{}, ErrSearchLimit
		}
		next, err := current.AddDays(direction)
		if err != nil {
			return calendar.Date{}, err
		}
		current = next
		visited++
		if c.IsBusinessDay(current) {
			admitted++
		}
	}
	return current, nil
}

// CountBusinessDays counts admitted dates in the half-open range [start,end).
// Reversed ranges return the negated count. searchLimit bounds examined dates.
func (c Calendar) CountBusinessDays(start, end calendar.Date, searchLimit int) (int, error) {
	if !start.IsValid() || !end.IsValid() {
		return 0, calendar.ErrInvalidDate
	}
	if searchLimit <= 0 {
		return 0, ErrSearchLimit
	}
	if start == end {
		return 0, nil
	}
	direction := 1
	if start.DaysUntil(end) < 0 {
		direction = -1
		start, end = end, start
	}
	span := start.DaysUntil(end)
	if span > searchLimit {
		return 0, ErrSearchLimit
	}
	count := 0
	current := start
	for i := 0; i < span; i++ {
		if c.IsBusinessDay(current) {
			count++
		}
		current, _ = current.AddDays(1)
	}
	return count * direction, nil
}

func (c Calendar) search(d calendar.Date, direction, searchLimit int) (calendar.Date, error) {
	if !d.IsValid() {
		return calendar.Date{}, calendar.ErrInvalidDate
	}
	if searchLimit <= 0 {
		return calendar.Date{}, ErrSearchLimit
	}
	current := d
	for range searchLimit {
		next, err := current.AddDays(direction)
		if err != nil {
			return calendar.Date{}, err
		}
		current = next
		if c.IsBusinessDay(current) {
			return current, nil
		}
	}
	return calendar.Date{}, ErrSearchLimit
}

// Observance selects an explicit source-to-observed-date policy.
type Observance uint8

const (
	// NoObservance leaves source holidays unchanged.
	NoObservance Observance = iota + 1
	// NextWeekday moves Saturday and Sunday holidays to the following Monday.
	NextWeekday
	// NearestWeekday moves Saturday to Friday and Sunday to Monday.
	NearestWeekday
)

// Observe returns source holidays plus separately marked observed entries.
func Observe(source []Holiday, policy Observance) ([]Holiday, error) {
	if len(source) > MaxHolidays {
		return nil, ErrResourceLimit
	}
	if policy < NoObservance || policy > NearestWeekday {
		return nil, ErrInvalidCalendar
	}
	result := make([]Holiday, 0, len(source)*2)
	for _, holiday := range source {
		copyHoliday, err := NewHoliday(holiday.date, holiday.name, holiday.metadata)
		if err != nil {
			return nil, err
		}
		result = append(result, copyHoliday)
		observedDate := holiday.date
		switch policy {
		case NoObservance:
			// Source dates remain unchanged.
		case NextWeekday:
			if holiday.date.Weekday() == time.Saturday {
				observedDate, _ = holiday.date.AddDays(2)
			} else if holiday.date.Weekday() == time.Sunday {
				observedDate, _ = holiday.date.AddDays(1)
			}
		case NearestWeekday:
			if holiday.date.Weekday() == time.Saturday {
				observedDate, _ = holiday.date.AddDays(-1)
			} else if holiday.date.Weekday() == time.Sunday {
				observedDate, _ = holiday.date.AddDays(1)
			}
		}
		if observedDate != holiday.date {
			observed, err := NewHoliday(observedDate, holiday.name+" (observed)", holiday.metadata)
			if err != nil {
				return nil, err
			}
			observed.observed = true
			observed.sourceDate = holiday.date
			result = append(result, observed)
		}
	}
	if len(result) > MaxHolidays {
		return nil, fmt.Errorf("%w: observed holidays", ErrResourceLimit)
	}
	return result, nil
}

func cloneMetadata(metadata map[string]string) (map[string]string, error) {
	if len(metadata) > MaxMetadataEntries {
		return nil, ErrResourceLimit
	}
	result := make(map[string]string, len(metadata))
	for key, value := range metadata {
		if key == "" || len(key) > maxMetadataKey || len(value) > maxMetadataValue || !utf8.ValidString(key) || !utf8.ValidString(value) {
			return nil, ErrInvalidHoliday
		}
		result[key] = value
	}
	return result, nil
}
