// Code generated by nodefaulthttp fixture. DO NOT EDIT.

package httpdefaults

import "net/http"

func GeneratedDefault() http.RoundTripper {
	return http.DefaultTransport // want `http/no-default-client: http.DefaultTransport has shared implicit lifecycle and timeout policy`
}
