// Code generated by nobackground fixture. DO NOT EDIT.

package contextuse

import "context"

func GeneratedDetached(parent context.Context) context.Context {
	return context.WithoutCancel(parent) // want `context/no-background: context.WithoutCancel is restricted to approved roots`
}
