// Code generated by metric fixture. DO NOT EDIT.

package metricconsumer

import (
	"labelmodel"
	"metricsink"
)

func RecordGenerated(user labelmodel.UserID) {
	metricsink.Label(string(user)) // want `observability/high-cardinality-label: labelmodel.UserID flows to metric label metricsink.Label argument 1`
}
