// Code generated by transaction fixture. DO NOT EDIT.

package txconsumer

import "txapi"

func Generated() {
	tx, _ := txapi.Begin() // want `lifecycle/transaction-rollback: transaction from txapi.Begin must immediately establish deferred Rollback ownership`
	_ = tx
}
