// Code generated by modelgen; DO NOT EDIT.

package oas32

import (
	"reflect"
	"testing"

	"github.com/faustbrian/golib/pkg/openapi/jsonvalue"
)

func TestGeneratedModelSurface(t *testing.T) {
	t.Parallel()

	object := generatedObject(t, true)
	plain := generatedObject(t, false)
	var values []any
	if value, ok := wrapDocument(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapDocument rejected an object")
	}
	if value, ok := wrapDocument(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapDocument(jsonvalue.Null()); ok {
		t.Fatal("wrapDocument accepted null")
	}
	if value, ok := wrapCallback(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapCallback rejected an object")
	}
	if value, ok := wrapCallback(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapCallback(jsonvalue.Null()); ok {
		t.Fatal("wrapCallback accepted null")
	}
	if value, ok := wrapComponents(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapComponents rejected an object")
	}
	if value, ok := wrapComponents(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapComponents(jsonvalue.Null()); ok {
		t.Fatal("wrapComponents accepted null")
	}
	if value, ok := wrapContact(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapContact rejected an object")
	}
	if value, ok := wrapContact(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapContact(jsonvalue.Null()); ok {
		t.Fatal("wrapContact accepted null")
	}
	if value, ok := wrapDiscriminator(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapDiscriminator rejected an object")
	}
	if value, ok := wrapDiscriminator(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapDiscriminator(jsonvalue.Null()); ok {
		t.Fatal("wrapDiscriminator accepted null")
	}
	if value, ok := wrapEncoding(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapEncoding rejected an object")
	}
	if value, ok := wrapEncoding(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapEncoding(jsonvalue.Null()); ok {
		t.Fatal("wrapEncoding accepted null")
	}
	if value, ok := wrapExample(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapExample rejected an object")
	}
	if value, ok := wrapExample(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapExample(jsonvalue.Null()); ok {
		t.Fatal("wrapExample accepted null")
	}
	if value, ok := wrapExternalDocumentation(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapExternalDocumentation rejected an object")
	}
	if value, ok := wrapExternalDocumentation(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapExternalDocumentation(jsonvalue.Null()); ok {
		t.Fatal("wrapExternalDocumentation accepted null")
	}
	if value, ok := wrapHeader(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapHeader rejected an object")
	}
	if value, ok := wrapHeader(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapHeader(jsonvalue.Null()); ok {
		t.Fatal("wrapHeader accepted null")
	}
	if value, ok := wrapInfo(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapInfo rejected an object")
	}
	if value, ok := wrapInfo(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapInfo(jsonvalue.Null()); ok {
		t.Fatal("wrapInfo accepted null")
	}
	if value, ok := wrapLicense(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapLicense rejected an object")
	}
	if value, ok := wrapLicense(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapLicense(jsonvalue.Null()); ok {
		t.Fatal("wrapLicense accepted null")
	}
	if value, ok := wrapLink(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapLink rejected an object")
	}
	if value, ok := wrapLink(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapLink(jsonvalue.Null()); ok {
		t.Fatal("wrapLink accepted null")
	}
	if value, ok := wrapMediaType(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapMediaType rejected an object")
	}
	if value, ok := wrapMediaType(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapMediaType(jsonvalue.Null()); ok {
		t.Fatal("wrapMediaType accepted null")
	}
	if value, ok := wrapOAuthFlow(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapOAuthFlow rejected an object")
	}
	if value, ok := wrapOAuthFlow(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapOAuthFlow(jsonvalue.Null()); ok {
		t.Fatal("wrapOAuthFlow accepted null")
	}
	if value, ok := wrapOAuthFlows(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapOAuthFlows rejected an object")
	}
	if value, ok := wrapOAuthFlows(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapOAuthFlows(jsonvalue.Null()); ok {
		t.Fatal("wrapOAuthFlows accepted null")
	}
	if value, ok := wrapOperation(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapOperation rejected an object")
	}
	if value, ok := wrapOperation(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapOperation(jsonvalue.Null()); ok {
		t.Fatal("wrapOperation accepted null")
	}
	if value, ok := wrapParameter(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapParameter rejected an object")
	}
	if value, ok := wrapParameter(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapParameter(jsonvalue.Null()); ok {
		t.Fatal("wrapParameter accepted null")
	}
	if value, ok := wrapPathItem(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapPathItem rejected an object")
	}
	if value, ok := wrapPathItem(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapPathItem(jsonvalue.Null()); ok {
		t.Fatal("wrapPathItem accepted null")
	}
	if value, ok := wrapPaths(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapPaths rejected an object")
	}
	if value, ok := wrapPaths(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapPaths(jsonvalue.Null()); ok {
		t.Fatal("wrapPaths accepted null")
	}
	if value, ok := wrapReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapReference rejected an object")
	}
	if value, ok := wrapReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapReference(jsonvalue.Null()); ok {
		t.Fatal("wrapReference accepted null")
	}
	if value, ok := wrapRequestBody(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapRequestBody rejected an object")
	}
	if value, ok := wrapRequestBody(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapRequestBody(jsonvalue.Null()); ok {
		t.Fatal("wrapRequestBody accepted null")
	}
	if value, ok := wrapResponse(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapResponse rejected an object")
	}
	if value, ok := wrapResponse(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapResponse(jsonvalue.Null()); ok {
		t.Fatal("wrapResponse accepted null")
	}
	if value, ok := wrapResponses(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapResponses rejected an object")
	}
	if value, ok := wrapResponses(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapResponses(jsonvalue.Null()); ok {
		t.Fatal("wrapResponses accepted null")
	}
	if value, ok := wrapSchema(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapSchema rejected an object")
	}
	if value, ok := wrapSchema(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapSchema(jsonvalue.Null()); ok {
		t.Fatal("wrapSchema accepted null")
	}
	if value, ok := wrapSecurityRequirement(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapSecurityRequirement rejected an object")
	}
	if value, ok := wrapSecurityRequirement(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapSecurityRequirement(jsonvalue.Null()); ok {
		t.Fatal("wrapSecurityRequirement accepted null")
	}
	if value, ok := wrapSecurityScheme(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapSecurityScheme rejected an object")
	}
	if value, ok := wrapSecurityScheme(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapSecurityScheme(jsonvalue.Null()); ok {
		t.Fatal("wrapSecurityScheme accepted null")
	}
	if value, ok := wrapServer(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapServer rejected an object")
	}
	if value, ok := wrapServer(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapServer(jsonvalue.Null()); ok {
		t.Fatal("wrapServer accepted null")
	}
	if value, ok := wrapServerVariable(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapServerVariable rejected an object")
	}
	if value, ok := wrapServerVariable(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapServerVariable(jsonvalue.Null()); ok {
		t.Fatal("wrapServerVariable accepted null")
	}
	if value, ok := wrapTag(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapTag rejected an object")
	}
	if value, ok := wrapTag(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapTag(jsonvalue.Null()); ok {
		t.Fatal("wrapTag accepted null")
	}
	if value, ok := wrapXML(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapXML rejected an object")
	}
	if value, ok := wrapXML(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapXML(jsonvalue.Null()); ok {
		t.Fatal("wrapXML accepted null")
	}
	if value, ok := wrapCallbackOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapCallbackOrReference rejected an object")
	}
	if value, ok := wrapCallbackOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapCallbackOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapCallbackOrReference accepted null")
	}
	if value, ok := wrapExampleOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapExampleOrReference rejected an object")
	}
	if value, ok := wrapExampleOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapExampleOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapExampleOrReference accepted null")
	}
	if value, ok := wrapHeaderOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapHeaderOrReference rejected an object")
	}
	if value, ok := wrapHeaderOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapHeaderOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapHeaderOrReference accepted null")
	}
	if value, ok := wrapLinkOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapLinkOrReference rejected an object")
	}
	if value, ok := wrapLinkOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapLinkOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapLinkOrReference accepted null")
	}
	if value, ok := wrapMediaTypeOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapMediaTypeOrReference rejected an object")
	}
	if value, ok := wrapMediaTypeOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapMediaTypeOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapMediaTypeOrReference accepted null")
	}
	if value, ok := wrapParameterOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapParameterOrReference rejected an object")
	}
	if value, ok := wrapParameterOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapParameterOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapParameterOrReference accepted null")
	}
	if value, ok := wrapRequestBodyOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapRequestBodyOrReference rejected an object")
	}
	if value, ok := wrapRequestBodyOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapRequestBodyOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapRequestBodyOrReference accepted null")
	}
	if value, ok := wrapResponseOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapResponseOrReference rejected an object")
	}
	if value, ok := wrapResponseOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapResponseOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapResponseOrReference accepted null")
	}
	if value, ok := wrapSecuritySchemeOrReference(object); ok {
		values = append(values, value)
	} else {
		t.Fatal("wrapSecuritySchemeOrReference rejected an object")
	}
	if value, ok := wrapSecuritySchemeOrReference(plain); ok {
		values = append(values, value)
	}
	if _, ok := wrapSecuritySchemeOrReference(jsonvalue.Null()); ok {
		t.Fatal("wrapSecuritySchemeOrReference accepted null")
	}

	for _, value := range values {
		exerciseGeneratedMethods(t, value)
	}
	exerciseGeneratedHelpers(t)

	if value, ok := wrapSchema(jsonvalue.Boolean(true)); ok {
		exerciseGeneratedMethods(t, value)
	} else {
		t.Fatal("wrapSchema rejected a boolean schema")
	}

	if _, err := Decode(jsonvalue.Null()); err == nil {
		t.Fatal("Decode accepted a non-object root")
	}
	if _, err := Decode(plain); err == nil {
		t.Fatal("Decode accepted a missing version")
	}
	if _, err := Decode(versionObject(t, "invalid")); err == nil {
		t.Fatal("Decode accepted an invalid version")
	}
	if _, err := Decode(versionObject(t, "2.0")); err == nil {
		t.Fatal("Decode accepted the wrong dialect")
	}
	if _, err := Decode(versionObject(t, Version)); err != nil {
		t.Fatalf("Decode rejected Version: %v", err)
	}
}

func generatedObject(t *testing.T, reference bool) jsonvalue.Value {
	t.Helper()
	text, err := jsonvalue.String("value")
	if err != nil {
		t.Fatal(err)
	}
	members := []jsonvalue.Member{
		{Name: "x-generated", Value: jsonvalue.Null()},
		{Name: "/generated", Value: jsonvalue.Null()},
		{Name: "generated", Value: jsonvalue.Null()},
	}
	if reference {
		members = append(members, jsonvalue.Member{Name: "$ref", Value: text})
	}
	value, err := jsonvalue.Object(members)
	if err != nil {
		t.Fatal(err)
	}
	return value
}

func versionObject(t *testing.T, version string) jsonvalue.Value {
	t.Helper()
	value, err := jsonvalue.String(version)
	if err != nil {
		t.Fatal(err)
	}
	object, err := jsonvalue.Object([]jsonvalue.Member{{Name: "openapi", Value: value}})
	if err != nil {
		t.Fatal(err)
	}
	return object
}

func exerciseGeneratedMethods(t *testing.T, value any) {
	t.Helper()
	reflected := reflect.ValueOf(value)
	typeOf := reflected.Type()
	for index := 0; index < typeOf.NumMethod(); index++ {
		methodType := typeOf.Method(index)
		method := reflected.Method(index)
		if method.Type().NumIn() != 0 {
			continue
		}
		results := method.Call(nil)
		if methodType.Name != "Extensions" {
			continue
		}
		names := results[0].MethodByName("Names").Call(nil)[0].Interface().([]string)
		raw := reflected.MethodByName("Raw").Call(nil)[0].Interface().(jsonvalue.Value)
		if raw.Kind() == jsonvalue.BooleanKind && len(names) == 0 {
			continue
		}
		if !reflect.DeepEqual(names, []string{"x-generated"}) {
			t.Fatalf("%s.Extensions().Names() = %#v", typeOf.Name(), names)
		}
		extension := results[0].MethodByName("Lookup").Call(
			[]reflect.Value{reflect.ValueOf("x-generated")},
		)
		if !extension[1].Bool() ||
			extension[0].Interface().(jsonvalue.Value).Kind() != jsonvalue.NullKind {
			t.Fatalf("%s.Extensions() did not retain its value", typeOf.Name())
		}
	}
}

func exerciseGeneratedHelpers(t *testing.T) {
	t.Helper()
	text, _ := jsonvalue.String("text")
	number, _ := jsonvalue.Number("1")
	decimal, _ := jsonvalue.Number("1.5")
	if _, ok := stringValue(text); !ok {
		t.Fatal("stringValue")
	}
	if _, ok := booleanValue(jsonvalue.Boolean(true)); !ok {
		t.Fatal("booleanValue")
	}
	if _, ok := rawValue(jsonvalue.Null()); !ok {
		t.Fatal("rawValue")
	}
	if _, ok := rawValue(jsonvalue.Value{}); ok {
		t.Fatal("rawValue invalid")
	}
	if _, ok := integerValue(number); !ok {
		t.Fatal("integerValue")
	}
	if _, ok := integerValue(decimal); ok {
		t.Fatal("integerValue decimal")
	}
	if _, ok := numberValue(decimal); !ok {
		t.Fatal("numberValue")
	}
	if !anyPatternName("anything") {
		t.Fatal("anyPatternName")
	}
	if extensionAwarePatternName("x-test") || !extensionAwarePatternName("value") {
		t.Fatal("extensionAwarePatternName")
	}
	if !pathPatternName("/path") || pathPatternName("path") {
		t.Fatal("pathPatternName")
	}
}
