package driver_test

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	shared "github.com/faustbrian/golib/pkg/analysis/analysis"
	"github.com/faustbrian/golib/pkg/analysis/internal/driver"
)

func TestRunHonorsBlockingAndDisabledStatus(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		status          string
		wantDiagnostics int
		wantBlocking    bool
	}{
		"blocking": {status: "blocking", wantDiagnostics: 1, wantBlocking: true},
		"advisory": {status: "advisory", wantDiagnostics: 1},
		"disabled": {status: "disabled"},
	}
	for name, test := range tests {
		test := test
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			root := writeModule(t, map[string]string{
				"sample/sample.go": "package sample\nimport _ \"unsafe\"\n",
			})
			config := writePolicy(t, root, "version: 1\nrules:\n"+
				"  security/no-unsafe:\n    status: "+test.status+"\n")
			result, err := driver.Run(context.Background(), driver.Options{
				ConfigPath: config,
				Patterns:   []string{"./..."},
				Sequential: true,
			})
			if err != nil {
				t.Fatalf("Run() error = %v", err)
			}
			if len(result.Report.Diagnostics) != test.wantDiagnostics ||
				result.Blocking != test.wantBlocking {
				t.Fatalf("Run() diagnostics = %d, blocking = %t",
					len(result.Report.Diagnostics), result.Blocking)
			}
			if len(result.Report.Diagnostics) > 0 &&
				filepath.IsAbs(result.Report.Diagnostics[0].Filename) {
				t.Fatal("Run() exposed an absolute diagnostic path")
			}
		})
	}
}

func TestRunAppliesAndInventoriesExactSuppressions(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/sample.go": `package sample
//analysis:ignore security/no-unsafe -- reviewed migration; issue=SEC-1
import _ "unsafe"
`,
	})
	config := writePolicy(t, root, "version: 1\nrules:\n"+
		"  security/no-unsafe:\n    status: blocking\n")
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if result.Blocking || len(result.Report.Diagnostics) != 0 ||
		len(result.Report.Suppressions) != 1 || !result.Report.Suppressions[0].Used {
		t.Fatalf("Run() result = %#v", result)
	}
}

func TestRunRejectsStaleSuppression(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/sample.go": `package sample
//analysis:ignore security/no-unsafe -- no longer needed
var Value int
`,
	})
	config := writePolicy(t, root, "version: 1\n")
	_, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err == nil || !strings.Contains(err.Error(), "stale suppression") {
		t.Fatalf("Run() error = %v, want stale suppression", err)
	}
}

func TestRunExcludesOnlyRecognizedGeneratedFilesWhenConfigured(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/generated.go": `// Code generated by fixture. DO NOT EDIT.

package sample

//analysis:ignore security/not-real -- generated directive is excluded
import _ "unsafe"
`,
		"sample/manual.go": `package sample
import _ "unsafe"
`,
	})
	config := writePolicy(t, root, `version: 1
generated:
  exclude: true
  paths:
    - sample/generated.go
rules:
  security/no-unsafe:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Filename != "sample/manual.go" ||
		len(result.Report.Suppressions) != 0 {
		t.Fatalf("Run() = %#v", result)
	}
}

func TestRunRequiresGeneratedHeaderPolicyAndExactPath(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		contents string
		policy   string
	}{
		"header without policy": {
			contents: "// Code generated by fixture. DO NOT EDIT.\n\n" +
				"package sample\nimport _ \"unsafe\"\n",
			policy: "version: 1\n",
		},
		"filename without header": {
			contents: "package sample\nimport _ \"unsafe\"\n",
			policy: "version: 1\ngenerated:\n  exclude: true\n" +
				"  paths: [sample/generated.go]\n",
		},
		"header without exact path": {
			contents: "// Code generated by fixture. DO NOT EDIT.\n\n" +
				"package sample\nimport _ \"unsafe\"\n",
			policy: "version: 1\ngenerated:\n  exclude: true\n" +
				"  paths: [sample/trusted.go]\n",
		},
	}
	for name, test := range tests {
		test := test
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			root := writeModule(t, map[string]string{
				"sample/generated.go": test.contents,
			})
			result, err := driver.Run(context.Background(), driver.Options{
				ConfigPath: writePolicy(t, root, test.policy),
				Patterns:   []string{"./..."},
				Sequential: true,
			})
			if err != nil {
				t.Fatalf("Run() error = %v", err)
			}
			if len(result.Report.Diagnostics) != 1 ||
				result.Report.Diagnostics[0].Filename != "sample/generated.go" {
				t.Fatalf("diagnostics = %#v", result.Report.Diagnostics)
			}
		})
	}
}

func TestRunRejectsSuppressionBehindForgedGeneratedHeader(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/generated.go": `// Code generated by attacker. DO NOT EDIT.

package sample

//analysis:ignore security/not-real -- forged generated suppression
import _ "unsafe"
`,
	})
	config := writePolicy(t, root, `version: 1
generated:
  exclude: true
  paths:
    - sample/trusted.go
rules:
  security/no-unsafe:
    status: blocking
`)
	_, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err == nil || !strings.Contains(err.Error(), "unknown rule") {
		t.Fatalf("Run() error = %v, want forged suppression rejection", err)
	}
}

func TestRunWiresLifecycleAndBlockingPolicies(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/sample.go": `package sample
import "context"
func init() {}
type service struct { ctx context.Context }
func Fetch() error { return nil }
`,
	})
	config := writePolicy(t, root, `version: 1
packages:
  - pattern: example.com/fixture/sample
    blocking_functions: [Fetch]
rules:
  context/blocking-api-context:
    status: blocking
  context/no-stored-context:
    status: blocking
  lifecycle/no-init:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 3 {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunReportsMutablePackageState(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/sample.go": "package sample\nvar Shared = map[string]int{}\n",
	})
	config := writePolicy(t, root, `version: 1
mutable_globals:
  - package: example.com/fixture/sample
rules:
  safety/no-mutable-global:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "safety/no-mutable-global" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunEnforcesConsumerOwnedInterfaces(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"provider/provider.go": "package provider\ntype Client interface { Call() }\n",
		"consumer/consumer.go": "package consumer\ntype Client interface { Call() }\n",
	})
	config := writePolicy(t, root, `version: 1
interface_provider_packages:
  - example.com/fixture/provider/...
rules:
  api/interface-placement:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Package != "example.com/fixture/provider" ||
		result.Report.Diagnostics[0].Rule != "api/interface-placement" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunReportsTypedHighCardinalityMetricLabels(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"model/model.go":     "package model\ntype UserID string\n",
		"metrics/metrics.go": "package metrics\nfunc Label(string) {}\n",
		"consumer/consumer.go": `package consumer
import (
    "example.com/fixture/metrics"
    "example.com/fixture/model"
)
func Record(user model.UserID) { metrics.Label(string(user)) }
`,
	})
	config := writePolicy(t, root, `version: 1
metric_label_types:
  - package: example.com/fixture/model
    name: UserID
metric_label_sinks:
  - package: example.com/fixture/metrics
    symbol: Label
    arguments: [0]
rules:
  observability/high-cardinality-label:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "observability/high-cardinality-label" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunReportsAttackerControlledMetricLabelNames(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"model/model.go":     "package model\ntype LabelName string\n",
		"metrics/metrics.go": "package metrics\nfunc Label(string, string) {}\n",
		"consumer/consumer.go": `package consumer
import (
    "example.com/fixture/metrics"
    "example.com/fixture/model"
)
func Record(name model.LabelName) { metrics.Label(string(name), "value") }
`,
	})
	config := writePolicy(t, root, `version: 1
metric_label_name_types:
  - package: example.com/fixture/model
    name: LabelName
metric_label_name_sinks:
  - package: example.com/fixture/metrics
    symbol: Label
    arguments: [0]
rules:
  observability/dynamic-label-name:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "observability/dynamic-label-name" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunRejectsBackendErrorsAtExportedBoundaries(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"backend/backend.go": "package backend\nimport \"errors\"\nfunc Load() error { return errors.New(\"backend\") }\n",
		"api/api.go": `package api
import "example.com/fixture/backend"
func Load() error { return backend.Load() }
`,
	})
	config := writePolicy(t, root, `version: 1
backend_error_boundaries:
  - example.com/fixture/api/...
backend_error_sources:
  - package: example.com/fixture/backend
    symbol: Load
    result: 0
rules:
  api/backend-error-boundary:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "api/backend-error-boundary" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunReportsUnboundedGoroutineFanout(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"worker/worker.go": `package worker
func Run(values []int) {
    for range values { go func() {}() }
}
`,
	})
	config := writePolicy(t, root, `version: 1
goroutine_fanout:
  - package: example.com/fixture/worker/...
    max_static: 8
rules:
  lifecycle/unbounded-goroutine-fanout:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "lifecycle/unbounded-goroutine-fanout" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunEnforcesLayerAndBoundedContextDirections(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"application/application.go": `package application
import (
    _ "example.com/fixture/catalog"
    _ "example.com/fixture/infra"
    _ "example.com/fixture/shared"
)
`,
		"catalog/catalog.go": "package catalog\n",
		"infra/infra.go":     "package infra\n",
		"shared/shared.go":   "package shared\n",
	})
	config := writePolicy(t, root, `version: 1
layers:
  - name: application
    may_import: [domain, shared]
  - name: domain
    may_import: [shared]
  - name: infrastructure
    may_import: [application, domain, shared]
  - name: shared
contexts:
  - name: orders
    may_import: [shared]
  - name: catalog
    may_import: [shared]
  - name: shared
packages:
  - pattern: example.com/fixture/application/...
    layer: application
    context: orders
  - pattern: example.com/fixture/catalog/...
    layer: domain
    context: catalog
  - pattern: example.com/fixture/infra/...
    layer: infrastructure
    context: orders
  - pattern: example.com/fixture/shared/...
    layer: shared
    context: shared
rules:
  architecture/import-boundary:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 2 ||
		!strings.Contains(result.Report.Diagnostics[0].Message, "context") ||
		!strings.Contains(result.Report.Diagnostics[1].Message, "layer") {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunRestrictsBackendClientsToApprovedAdapters(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"backend/client.go": "package backend\n",
		"adapter/adapter.go": `package adapter
import _ "example.com/fixture/backend"
`,
		"consumer/consumer.go": `package consumer
import _ "example.com/fixture/backend"
`,
	})
	config := writePolicy(t, root, `version: 1
backend_clients:
  - package: example.com/fixture/backend/...
    allowed_packages:
      - example.com/fixture/adapter/...
rules:
  architecture/import-boundary:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Package != "example.com/fixture/consumer" ||
		!strings.Contains(result.Report.Diagnostics[0].Message, "approved adapter") {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunWiresForbiddenAPIMigrations(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"legacy/legacy.go": "package legacy\nfunc Old() {}\n",
		"sample/sample.go": `package sample
import "example.com/fixture/legacy"
func Call() { legacy.Old() }
`,
	})
	config := writePolicy(t, root, `version: 1
forbidden_apis:
  - package: example.com/fixture/legacy
    symbol: Old
    replacement: example.com/fixture/modern.New
rules:
  api/forbidden-call:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		!strings.Contains(result.Report.Diagnostics[0].Message, "modern.New") {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunWiresConstructorLifecyclePolicy(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"worker/worker.go": `package worker
func work() {}
func New() int {
    go work()
    return 1
}
`,
	})
	config := writePolicy(t, root, `version: 1
constructors:
  - package: example.com/fixture/worker
    symbols: [New]
rules:
  lifecycle/no-constructor-goroutine:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunWiresCleanupOwnershipPolicy(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"resource/resource.go": `package resource
func Open() (int, func(), error) { return 0, func() {}, nil }
`,
		"consumer/consumer.go": `package consumer
import "example.com/fixture/resource"
func Open() { _, _, _ = resource.Open() }
`,
	})
	config := writePolicy(t, root, `version: 1
resource_constructors:
  - package: example.com/fixture/resource
    symbol: Open
    cleanup_result: 1
rules:
  lifecycle/cleanup-ownership:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "lifecycle/cleanup-ownership" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunWiresTransactionRollbackPolicy(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"txapi/txapi.go": `package txapi
type Tx struct{}
func (*Tx) Rollback() error { return nil }
func Begin() (*Tx, error) { return &Tx{}, nil }
`,
		"consumer/consumer.go": `package consumer
import "example.com/fixture/txapi"
func Use() {
    tx, _ := txapi.Begin()
    _ = tx
}
`,
	})
	config := writePolicy(t, root, `version: 1
transactions:
  - package: example.com/fixture/txapi
    symbol: Begin
    result: 0
    rollback_method: Rollback
rules:
  lifecycle/transaction-rollback:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "lifecycle/transaction-rollback" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunWiresHTTPClientTimeoutPolicy(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"client/client.go": `package client
import "net/http"
func New() *http.Client { return &http.Client{} }
`,
	})
	config := writePolicy(t, root, `version: 1
rules:
  http/client-timeout:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "http/client-timeout" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunWiresLockSensitiveCallPolicy(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"backend/backend.go": "package backend\nfunc Call() {}\n",
		"consumer/consumer.go": `package consumer
import (
    "example.com/fixture/backend"
    "sync"
)
func Call() {
    var mutex sync.Mutex
    mutex.Lock()
    backend.Call()
    mutex.Unlock()
}
`,
	})
	config := writePolicy(t, root, `version: 1
lock_sensitive_calls:
  - package: example.com/fixture/backend
    symbol: Call
rules:
  lifecycle/lock-across-call:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 ||
		result.Report.Diagnostics[0].Rule != "lifecycle/lock-across-call" {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunWiresSensitiveSinkPolicy(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"secret/secret.go": "package secret\ntype Token string\n",
		"sink/sink.go":     "package sink\nfunc Record(any) {}\n",
		"sample/sample.go": `package sample
import (
    "example.com/fixture/secret"
    "example.com/fixture/sink"
)
func Log(token secret.Token) { sink.Record(token) }
`,
	})
	config := writePolicy(t, root, `version: 1
sensitive_types:
  - package: example.com/fixture/secret
    name: Token
sensitive_sinks:
  - package: example.com/fixture/sink
    symbol: Record
    arguments: [0]
rules:
  security/sensitive-sink:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if !result.Blocking || len(result.Report.Diagnostics) != 1 {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
}

func TestRunAppliesExactPolicyExceptionAndReportsInventory(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/sample.go": "package sample\nimport _ \"unsafe\"\n",
	})
	config := writePolicy(t, root, `version: 1
exceptions:
  - rule: security/no-unsafe
    package: example.com/fixture/sample
    path: sample/sample.go
    reason: reviewed ABI bridge
    expires: 2027-01-31
    issue: SEC-42
rules:
  security/no-unsafe:
    status: blocking
`)
	result, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
		Now:        time.Date(2026, 7, 16, 12, 0, 0, 0, time.UTC),
	})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if result.Blocking || len(result.Report.Diagnostics) != 0 {
		t.Fatalf("Run() = blocking %t, diagnostics %#v",
			result.Blocking, result.Report.Diagnostics)
	}
	if len(result.Report.Exceptions) != 1 ||
		!result.Report.Exceptions[0].Used {
		t.Fatalf("exception inventory = %#v", result.Report.Exceptions)
	}
}

func TestRunRejectsStalePolicyException(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/sample.go": "package sample\n",
	})
	config := writePolicy(t, root, `version: 1
exceptions:
  - rule: security/no-unsafe
    package: example.com/fixture/sample
    reason: reviewed ABI bridge
`)
	_, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
		Now:        time.Date(2026, 7, 16, 12, 0, 0, 0, time.UTC),
	})
	if err == nil || !strings.Contains(err.Error(), "stale policy exception") {
		t.Fatalf("Run() error = %v", err)
	}
}

func TestRunRejectsSourceSuppressionHiddenByPolicyException(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/sample.go": `package sample
//analysis:ignore security/no-unsafe -- duplicate local exception
import _ "unsafe"
`,
	})
	config := writePolicy(t, root, `version: 1
exceptions:
  - rule: security/no-unsafe
    package: example.com/fixture/sample
    path: sample/sample.go
    reason: centrally reviewed ABI bridge
`)
	_, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
		Now:        time.Date(2026, 7, 16, 12, 0, 0, 0, time.UTC),
	})
	if err == nil || !strings.Contains(err.Error(), "stale suppression") {
		t.Fatalf("Run() error = %v", err)
	}
}

func TestRunIsDeterministicAcrossConcurrency(t *testing.T) {
	t.Parallel()

	root := writeModule(t, map[string]string{
		"sample/sample.go": `package sample
import (
    "context"
    _ "unsafe"
)
var Root = context.Background()
`,
	})
	config := writePolicy(t, root, `version: 1
exceptions:
  - rule: security/no-unsafe
    package: example.com/fixture/sample
    path: sample/sample.go
    reason: deterministic reviewed exception
`)
	now := time.Date(2026, 7, 16, 12, 0, 0, 0, time.UTC)
	baseline, err := driver.Run(context.Background(), driver.Options{
		ConfigPath: config,
		Patterns:   []string{"./..."},
		Sequential: true,
		Now:        now,
	})
	if err != nil {
		t.Fatalf("Run(sequential) error = %v", err)
	}
	want := reportJSON(t, baseline.Report)
	for iteration := 0; iteration < 5; iteration++ {
		result, err := driver.Run(context.Background(), driver.Options{
			ConfigPath: config,
			Patterns:   []string{"./..."},
			Now:        now,
		})
		if err != nil {
			t.Fatalf("Run(concurrent %d) error = %v", iteration, err)
		}
		if got := reportJSON(t, result.Report); !bytes.Equal(got, want) {
			t.Fatalf("concurrent report %d differs\n got: %s\nwant: %s",
				iteration, got, want)
		}
	}
}

func reportJSON(t *testing.T, report shared.Report) []byte {
	t.Helper()

	var output bytes.Buffer
	if err := shared.WriteJSON(&output, report); err != nil {
		t.Fatalf("WriteJSON() error = %v", err)
	}
	return output.Bytes()
}

func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()

	root := t.TempDir()
	files["go.mod"] = "module example.com/fixture\n\ngo 1.26.0\n"
	for name, contents := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatalf("MkdirAll() error = %v", err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
			t.Fatalf("WriteFile() error = %v", err)
		}
	}

	return root
}

func writePolicy(t *testing.T, root, contents string) string {
	t.Helper()

	contents = strings.ReplaceAll(
		contents,
		"    status: blocking\n",
		"    status: blocking\n"+
			"    promotion:\n"+
			"      version: 0.1.0\n"+
			"      evidence: driver integration fixture\n",
	)
	path := filepath.Join(root, "analysis.yml")
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	return path
}
