// Code generated by lockacrosscall fixture. DO NOT EDIT.

package consumer

import (
	"ioapi"
	"sync"
)

func generatedLockedCall() {
	var mutex sync.Mutex
	mutex.Lock()
	ioapi.Call() // want `lifecycle/lock-across-call: ioapi.Call is called while a lock is definitely held`
	mutex.Unlock()
}
