// Code generated by sensitivesink fixture. DO NOT EDIT.

package consumer

import (
	"secretmodel"
	"sinkapi"
)

func GeneratedSensitive(token secretmodel.Token) {
	sinkapi.Record(token) // want `security/sensitive-sink: secretmodel.Token flows to sinkapi.Record argument 1`
}
