version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - errorlint
    - errcheck
    - gomodguard_v2
    - gosec
    - govet
    - ineffassign
    - interfacebloat
    - ireturn
    - noctx
    - promlinter
    - sqlclosecheck
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
