// Code generated by httpclienttimeout fixture. DO NOT EDIT.

package httptimeout

import "net/http"

func generatedClient() *http.Client {
	return &http.Client{} // want `http/client-timeout: http.Client must declare a positive Timeout`
}
