// Package modelgen generates immutable version-specific OpenAPI model
// accessors from the reviewed prose-derived object and field inventory.
package modelgen

import (
	"errors"
	"fmt"
	"go/format"
	"regexp"
	"slices"
	"strings"
	"unicode"

	"github.com/faustbrian/golib/pkg/openapi/internal/specification"
)

var wrapperPattern = regexp.MustCompile(`func wrap([A-Za-z0-9]+)\(`)

// Config selects one generated version-line package.
type Config struct {
	Package       string
	Version       string
	RootObject    string
	VersionField  string
	Dialect       string
	BooleanSchema bool
}

type generatedObject struct {
	rawName string
	name    string
	fields  []generatedField
	pattern *generatedField
}

type generatedField struct {
	rawName    string
	methodName string
	typeNode   fieldType
}

type union struct {
	name       string
	targetName string
}

type typeKind uint8

const (
	kindString typeKind = iota
	kindBoolean
	kindInteger
	kindNumber
	kindRaw
	kindObject
	kindList
	kindMap
	kindReferenceUnion
)

type fieldType struct {
	kind   typeKind
	name   string
	elem   *fieldType
	target string
}

// Generate creates one gofmt-formatted model source file. It fails on every
// unmapped prose type so new specification fields cannot silently disappear.
func Generate(config Config, fields []specification.ObjectField) ([]byte, error) {
	if config.Package == "" || config.Version == "" || config.RootObject == "" {
		return nil, errors.New("modelgen: package, version, and root object are required")
	}
	if (config.VersionField == "") != (config.Dialect == "") {
		return nil, errors.New("modelgen: version field and dialect must be configured together")
	}

	objectFields := make(map[string][]generatedField)
	objectPatterns := make(map[string]generatedField)
	objectNames := make(map[string]struct{})
	goToRaw := make(map[string]string)
	unions := make(map[string]union)
	seenFields := make(map[string]struct{})
	for _, field := range fields {
		objectNames[field.Object] = struct{}{}
		goToRaw[goObjectName(field.Object, config.RootObject)] = field.Object
	}
	goToRaw["Document"] = config.RootObject
	for _, field := range fields {
		if field.Pattern {
			objectNames[field.Object] = struct{}{}
			if strings.HasPrefix(field.Name, "^x-") {
				continue
			}
			typeNode, err := parseFieldType(field.Type, config.RootObject)
			if err != nil {
				return nil, fmt.Errorf("modelgen: %s pattern %s: %w", field.Object, field.Name, err)
			}
			collectTypeObjects(typeNode, objectNames, goToRaw, unions)
			if _, exists := objectPatterns[field.Object]; !exists {
				objectPatterns[field.Object] = generatedField{
					rawName:    field.Name,
					methodName: "Entries",
					typeNode:   typeNode,
				}
			}
			continue
		}
		if strings.HasPrefix(field.Name, "^") || strings.ContainsAny(field.Name, "{}") {
			objectNames[field.Object] = struct{}{}
			continue
		}
		key := field.Object + "\x00" + field.Name
		if _, duplicate := seenFields[key]; duplicate {
			continue
		}
		seenFields[key] = struct{}{}

		typeNode, err := parseFieldType(field.Type, config.RootObject)
		if err != nil {
			return nil, fmt.Errorf("modelgen: %s.%s: %w", field.Object, field.Name, err)
		}
		collectTypeObjects(typeNode, objectNames, goToRaw, unions)
		objectNames[field.Object] = struct{}{}
		objectFields[field.Object] = append(objectFields[field.Object], generatedField{
			rawName:    field.Name,
			methodName: goFieldName(field.Name),
			typeNode:   typeNode,
		})
	}
	objectNames[config.RootObject] = struct{}{}

	objects := make([]generatedObject, 0, len(objectNames))
	for rawName := range objectNames {
		objects = append(objects, generatedObject{
			rawName: rawName,
			name:    goObjectName(rawName, config.RootObject),
			fields:  objectFields[rawName],
			pattern: patternPointer(objectPatterns, rawName),
		})
	}
	slices.SortFunc(objects, func(left generatedObject, right generatedObject) int {
		return strings.Compare(objectSortKey(left), objectSortKey(right))
	})

	unionList := make([]union, 0, len(unions))
	for _, item := range unions {
		unionList = append(unionList, item)
	}
	slices.SortFunc(unionList, func(left union, right union) int {
		return strings.Compare(left.name, right.name)
	})

	var output strings.Builder
	fmt.Fprintf(&output, "// Code generated by modelgen; DO NOT EDIT.\n\npackage %s\n\n", config.Package)
	output.WriteString(`import (
	"errors"
	"fmt"
	"strings"

	"github.com/faustbrian/golib/pkg/openapi/internal/modelaccess"
	"github.com/faustbrian/golib/pkg/openapi/jsonvalue"
	"github.com/faustbrian/golib/pkg/openapi/model"
	"github.com/faustbrian/golib/pkg/openapi/specversion"
)

`)
	output.WriteString("// ErrInvalidDocument reports a root value that cannot select this OpenAPI dialect.\n")
	output.WriteString("var ErrInvalidDocument = errors.New(\"invalid OpenAPI document\")\n\n")
	fmt.Fprintf(&output, "// Version is the latest pinned patch used to generate this package.\nconst Version = %q\n\n", config.Version)
	writeDecode(&output, config)
	writeValueDecoders(&output)

	for _, object := range objects {
		writeObject(&output, config, object)
	}
	for _, item := range unionList {
		writeUnion(&output, item)
	}

	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("modelgen: format generated source: %w\n%s", err, output.String())
	}
	return formatted, nil
}

func objectSortKey(object generatedObject) string {
	if object.name == "Document" {
		return ""
	}

	return object.name
}

// GenerateTests creates exhaustive generated-surface smoke tests. The tests
// execute every wrapper and exported zero-argument method so additions to the
// prose-derived inventory gain executable coverage automatically.
func GenerateTests(config Config, fields []specification.ObjectField) ([]byte, error) {
	production, err := Generate(config, fields)
	if err != nil {
		return nil, err
	}
	matches := wrapperPattern.FindAllSubmatch(production, -1)
	seen := make(map[string]struct{}, len(matches))
	wrappers := make([]string, 0, len(matches))
	for _, match := range matches {
		name := string(match[1])
		seen[name] = struct{}{}
		wrappers = append(wrappers, name)
	}

	var output strings.Builder
	fmt.Fprintf(
		&output,
		"// Code generated by modelgen; DO NOT EDIT.\n\npackage %s\n\n",
		config.Package,
	)
	output.WriteString(`import (
	"reflect"
	"testing"

	"github.com/faustbrian/golib/pkg/openapi/jsonvalue"
)

func TestGeneratedModelSurface(t *testing.T) {
	t.Parallel()

	object := generatedObject(t, true)
	plain := generatedObject(t, false)
	var values []any
`)
	for _, name := range wrappers {
		fmt.Fprintf(
			&output,
			"\tif value, ok := wrap%s(object); ok { values = append(values, value) } else { t.Fatal(%q) }\n",
			name,
			"wrap"+name+" rejected an object",
		)
		fmt.Fprintf(
			&output,
			"\tif value, ok := wrap%s(plain); ok { values = append(values, value) }\n",
			name,
		)
		fmt.Fprintf(
			&output,
			"\tif _, ok := wrap%s(jsonvalue.Null()); ok { t.Fatal(%q) }\n",
			name,
			"wrap"+name+" accepted null",
		)
	}
	output.WriteString(`
	for _, value := range values {
		exerciseGeneratedMethods(t, value)
	}
	exerciseGeneratedHelpers(t)
`)
	if config.BooleanSchema {
		if _, exists := seen["Schema"]; exists {
			output.WriteString(`
	if value, ok := wrapSchema(jsonvalue.Boolean(true)); ok {
		exerciseGeneratedMethods(t, value)
	} else {
		t.Fatal("wrapSchema rejected a boolean schema")
	}
`)
		}
	}
	if config.VersionField != "" {
		wrongVersion := "2.0"
		if config.Version == "2.0" {
			wrongVersion = "3.2.0"
		}
		fmt.Fprintf(&output, `
	if _, err := Decode(jsonvalue.Null()); err == nil {
		t.Fatal("Decode accepted a non-object root")
	}
	if _, err := Decode(plain); err == nil {
		t.Fatal("Decode accepted a missing version")
	}
	if _, err := Decode(versionObject(t, "invalid")); err == nil {
		t.Fatal("Decode accepted an invalid version")
	}
	if _, err := Decode(versionObject(t, %q)); err == nil {
		t.Fatal("Decode accepted the wrong dialect")
	}
	if _, err := Decode(versionObject(t, Version)); err != nil {
		t.Fatalf("Decode rejected Version: %%v", err)
	}
`, wrongVersion)
	}
	output.WriteString("}\n\n")
	output.WriteString(`func generatedObject(t *testing.T, reference bool) jsonvalue.Value {
	t.Helper()
	text, err := jsonvalue.String("value")
	if err != nil {
		t.Fatal(err)
	}
	members := []jsonvalue.Member{
		{Name: "x-generated", Value: jsonvalue.Null()},
		{Name: "/generated", Value: jsonvalue.Null()},
		{Name: "generated", Value: jsonvalue.Null()},
	}
	if reference {
		members = append(members, jsonvalue.Member{Name: "$ref", Value: text})
	}
	value, err := jsonvalue.Object(members)
	if err != nil {
		t.Fatal(err)
	}
	return value
}

func versionObject(t *testing.T, version string) jsonvalue.Value {
	t.Helper()
	value, err := jsonvalue.String(version)
	if err != nil {
		t.Fatal(err)
	}
`)
	fmt.Fprintf(
		&output,
		"\tobject, err := jsonvalue.Object([]jsonvalue.Member{{Name: %q, Value: value}})\n",
		config.VersionField,
	)
	output.WriteString(`	if err != nil {
		t.Fatal(err)
	}
	return object
}

func exerciseGeneratedMethods(t *testing.T, value any) {
	t.Helper()
	reflected := reflect.ValueOf(value)
	typeOf := reflected.Type()
	for index := 0; index < typeOf.NumMethod(); index++ {
		methodType := typeOf.Method(index)
		method := reflected.Method(index)
		if method.Type().NumIn() != 0 {
			continue
		}
		results := method.Call(nil)
		if methodType.Name != "Extensions" {
			continue
		}
		names := results[0].MethodByName("Names").Call(nil)[0].Interface().([]string)
		raw := reflected.MethodByName("Raw").Call(nil)[0].Interface().(jsonvalue.Value)
		if raw.Kind() == jsonvalue.BooleanKind && len(names) == 0 {
			continue
		}
		if !reflect.DeepEqual(names, []string{"x-generated"}) {
			t.Fatalf("%s.Extensions().Names() = %#v", typeOf.Name(), names)
		}
		extension := results[0].MethodByName("Lookup").Call(
			[]reflect.Value{reflect.ValueOf("x-generated")},
		)
		if !extension[1].Bool() ||
			extension[0].Interface().(jsonvalue.Value).Kind() != jsonvalue.NullKind {
			t.Fatalf("%s.Extensions() did not retain its value", typeOf.Name())
		}
	}
}

func exerciseGeneratedHelpers(t *testing.T) {
	t.Helper()
	text, _ := jsonvalue.String("text")
	number, _ := jsonvalue.Number("1")
	decimal, _ := jsonvalue.Number("1.5")
	if _, ok := stringValue(text); !ok { t.Fatal("stringValue") }
	if _, ok := booleanValue(jsonvalue.Boolean(true)); !ok { t.Fatal("booleanValue") }
	if _, ok := rawValue(jsonvalue.Null()); !ok { t.Fatal("rawValue") }
	if _, ok := rawValue(jsonvalue.Value{}); ok { t.Fatal("rawValue invalid") }
	if _, ok := integerValue(number); !ok { t.Fatal("integerValue") }
	if _, ok := integerValue(decimal); ok { t.Fatal("integerValue decimal") }
	if _, ok := numberValue(decimal); !ok { t.Fatal("numberValue") }
	if !anyPatternName("anything") { t.Fatal("anyPatternName") }
	if extensionAwarePatternName("x-test") || !extensionAwarePatternName("value") {
		t.Fatal("extensionAwarePatternName")
	}
	if !pathPatternName("/path") || pathPatternName("path") {
		t.Fatal("pathPatternName")
	}
}
`)

	return format.Source([]byte(output.String()))
}

func writeDecode(output *strings.Builder, config Config) {
	output.WriteString("// Decode selects this version-line model without discarding unknown or invalid nested fields.\n")
	output.WriteString("func Decode(raw jsonvalue.Value) (Document, error) {\n")
	output.WriteString("\tdocument, ok := wrapDocument(raw)\n")
	output.WriteString("\tif !ok {\n\t\treturn Document{}, fmt.Errorf(\"%w: root is not an object\", ErrInvalidDocument)\n\t}\n")
	if config.VersionField == "" {
		output.WriteString("\treturn document, nil\n}\n\n")
		return
	}
	fmt.Fprintf(output, "\tselected, ok := modelaccess.String(raw, %q).Value()\n", config.VersionField)
	output.WriteString("\tif !ok {\n\t\treturn Document{}, fmt.Errorf(\"%w: specification version is missing or not a string\", ErrInvalidDocument)\n\t}\n")
	output.WriteString("\tversion, err := specversion.Parse(selected)\n")
	output.WriteString("\tif err != nil {\n\t\treturn Document{}, fmt.Errorf(\"%w: %w\", ErrInvalidDocument, err)\n\t}\n")
	fmt.Fprintf(output, "\tif version.Dialect() != specversion.%s {\n", config.Dialect)
	output.WriteString("\t\treturn Document{}, fmt.Errorf(\"%w: wrong specification dialect\", ErrInvalidDocument)\n\t}\n")
	output.WriteString("\treturn document, nil\n}\n\n")
}

func writeValueDecoders(output *strings.Builder) {
	output.WriteString(`func stringValue(raw jsonvalue.Value) (string, bool) {
	return raw.Text()
}

func booleanValue(raw jsonvalue.Value) (bool, bool) {
	return raw.Bool()
}

func rawValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	return raw, raw.Kind() != jsonvalue.InvalidKind
}

func integerValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	text, ok := raw.NumberText()
	return raw, ok && !strings.ContainsAny(text, ".eE")
}

func numberValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	_, ok := raw.NumberText()
	return raw, ok
}

func anyPatternName(string) bool {
	return true
}

func extensionAwarePatternName(name string) bool {
	return !strings.HasPrefix(name, "x-")
}

func pathPatternName(name string) bool {
	return strings.HasPrefix(name, "/")
}

`)
}

func writeObject(output *strings.Builder, config Config, object generatedObject) {
	fmt.Fprintf(output, "// %s is an immutable typed view of the %s.\n", object.name, object.rawName)
	fmt.Fprintf(output, "type %s struct {\n\traw jsonvalue.Value\n}\n\n", object.name)
	fmt.Fprintf(output, "func wrap%s(raw jsonvalue.Value) (%s, bool) {\n", object.name, object.name)
	if config.BooleanSchema && object.name == "Schema" {
		output.WriteString("\tif raw.Kind() != jsonvalue.ObjectKind && raw.Kind() != jsonvalue.BooleanKind {\n")
	} else {
		output.WriteString("\tif raw.Kind() != jsonvalue.ObjectKind {\n")
	}
	fmt.Fprintf(output, "\t\treturn %s{}, false\n\t}\n\treturn %s{raw: raw}, true\n}\n\n", object.name, object.name)
	fmt.Fprintf(output, "// Raw returns the complete immutable semantic representation.\nfunc (value %s) Raw() jsonvalue.Value {\n\treturn value.raw\n}\n\n", object.name)
	if object.name == "Document" && config.VersionField != "" {
		output.WriteString("// SpecificationVersion returns the exact selected patch revision.\n")
		output.WriteString("func (value Document) SpecificationVersion() specversion.Version {\n")
		fmt.Fprintf(output, "\tselected, _ := modelaccess.String(value.raw, %q).Value()\n", config.VersionField)
		output.WriteString("\tversion, _ := specversion.Parse(selected)\n")
		output.WriteString("\treturn version\n}\n\n")
	}
	fmt.Fprintf(output, "// Extensions returns x- fields in source order.\nfunc (value %s) Extensions() model.Map[jsonvalue.Value] {\n\treturn modelaccess.Extensions(value.raw)\n}\n\n", object.name)
	for _, field := range object.fields {
		returnType := goType(field.typeNode)
		fmt.Fprintf(output, "// %s returns the %q field with exact presence semantics.\n", field.methodName, field.rawName)
		fmt.Fprintf(output, "func (value %s) %s() model.Field[%s] {\n", object.name, field.methodName, returnType)
		fmt.Fprintf(output, "\t%s\n}\n\n", fieldAccessor(field.typeNode, field.rawName))
	}
	if object.pattern != nil {
		returnType := goType(object.pattern.typeNode)
		fmt.Fprintf(output, "// Entries returns typed patterned fields in source order.\n")
		fmt.Fprintf(output, "func (value %s) Entries() model.Map[model.Field[%s]] {\n", object.name, returnType)
		fmt.Fprintf(
			output,
			"\treturn modelaccess.PatternEntries(value.raw, %#v, %s, %s)\n}\n\n",
			fixedFieldNames(object.fields),
			patternPredicate(object),
			decoderExpression(object.pattern.typeNode),
		)
	}
}

func patternPointer(patterns map[string]generatedField, rawName string) *generatedField {
	pattern, exists := patterns[rawName]
	if !exists {
		return nil
	}
	return &pattern
}

func fixedFieldNames(fields []generatedField) []string {
	names := make([]string, len(fields))
	for index, field := range fields {
		names[index] = field.rawName
	}
	return names
}

func patternPredicate(object generatedObject) string {
	if object.pattern != nil && object.pattern.rawName == "/{path}" {
		return "pathPatternName"
	}
	switch object.rawName {
	case "Paths Object", "Responses Object", "Callback Object":
		return "extensionAwarePatternName"
	default:
		return "anyPatternName"
	}
}

func writeUnion(output *strings.Builder, item union) {
	fmt.Fprintf(output, "// %s preserves either a %s or Reference Object.\n", item.name, item.targetName)
	fmt.Fprintf(output, "type %s struct {\n\traw jsonvalue.Value\n}\n\n", item.name)
	fmt.Fprintf(output, "func wrap%s(raw jsonvalue.Value) (%s, bool) {\n", item.name, item.name)
	fmt.Fprintf(output, "\tif raw.Kind() != jsonvalue.ObjectKind {\n\t\treturn %s{}, false\n\t}\n\treturn %s{raw: raw}, true\n}\n\n", item.name, item.name)
	fmt.Fprintf(output, "// Raw returns the complete union representation.\nfunc (value %s) Raw() jsonvalue.Value { return value.raw }\n\n", item.name)
	fmt.Fprintf(output, "// IsReference reports whether $ref selects the Reference Object.\nfunc (value %s) IsReference() bool {\n\t_, ok := modelaccess.String(value.raw, \"$ref\").Value()\n\treturn ok\n}\n\n", item.name)
	fmt.Fprintf(output, "// Reference returns the selected Reference Object.\nfunc (value %s) Reference() (Reference, bool) {\n\tif !value.IsReference() { return Reference{}, false }\n\treturn wrapReference(value.raw)\n}\n\n", item.name)
	fmt.Fprintf(output, "// %s returns the selected target object.\nfunc (value %s) %s() (%s, bool) {\n\tif value.IsReference() { return %s{}, false }\n\treturn wrap%s(value.raw)\n}\n\n", item.targetName, item.name, item.targetName, item.targetName, item.targetName, item.targetName)
}

func fieldAccessor(node fieldType, rawName string) string {
	quoted := fmt.Sprintf("%q", rawName)
	switch node.kind {
	case kindString:
		return fmt.Sprintf("return modelaccess.String(value.raw, %s)", quoted)
	case kindBoolean:
		return fmt.Sprintf("return modelaccess.Boolean(value.raw, %s)", quoted)
	case kindInteger:
		return fmt.Sprintf("return modelaccess.Scalar(value.raw, %s, integerValue)", quoted)
	case kindNumber:
		return fmt.Sprintf("return modelaccess.Scalar(value.raw, %s, numberValue)", quoted)
	case kindRaw:
		return fmt.Sprintf("return modelaccess.Raw(value.raw, %s)", quoted)
	case kindObject:
		return fmt.Sprintf("return modelaccess.Scalar(value.raw, %s, wrap%s)", quoted, node.name)
	case kindReferenceUnion:
		return fmt.Sprintf("return modelaccess.Scalar(value.raw, %s, wrap%s)", quoted, node.name)
	case kindList:
		return fmt.Sprintf("return modelaccess.List(value.raw, %s, %s)", quoted, decoderName(*node.elem))
	case kindMap:
		return fmt.Sprintf("return modelaccess.Map(value.raw, %s, %s)", quoted, decoderName(*node.elem))
	default:
		panic("unreachable field type")
	}
}

func decoderName(node fieldType) string {
	switch node.kind {
	case kindString:
		return "stringValue"
	case kindBoolean:
		return "booleanValue"
	case kindInteger:
		return "integerValue"
	case kindNumber:
		return "numberValue"
	case kindRaw:
		return "rawValue"
	case kindObject:
		return "wrap" + node.name
	case kindReferenceUnion:
		return "wrap" + node.name
	default:
		panic("nested composite decoder is not supported")
	}
}

func decoderExpression(node fieldType) string {
	switch node.kind {
	case kindList:
		return fmt.Sprintf(
			"func(raw jsonvalue.Value) (model.List[%s], bool) { return modelaccess.ListValue(raw, %s) }",
			goType(*node.elem),
			decoderExpression(*node.elem),
		)
	case kindMap:
		return fmt.Sprintf(
			"func(raw jsonvalue.Value) (model.Map[%s], bool) { return modelaccess.MapValue(raw, %s) }",
			goType(*node.elem),
			decoderExpression(*node.elem),
		)
	default:
		return decoderName(node)
	}
}

func goType(node fieldType) string {
	switch node.kind {
	case kindString:
		return "string"
	case kindBoolean:
		return "bool"
	case kindInteger, kindNumber, kindRaw:
		return "jsonvalue.Value"
	case kindObject, kindReferenceUnion:
		return node.name
	case kindList:
		return "model.List[" + goType(*node.elem) + "]"
	case kindMap:
		return "model.Map[" + goType(*node.elem) + "]"
	default:
		panic("unreachable field type")
	}
}

func parseFieldType(raw string, rootObject string) (fieldType, error) {
	raw = strings.TrimSpace(raw)
	raw = strings.Replace(raw, "Map[ string", "Map[string", 1)
	if raw == "Any" || raw == "*" || raw == "Any | {expression}" {
		return fieldType{kind: kindRaw}, nil
	}
	if raw == "string" {
		return fieldType{kind: kindString}, nil
	}
	if raw == "boolean" {
		return fieldType{kind: kindBoolean}, nil
	}
	if raw == "integer" {
		return fieldType{kind: kindInteger}, nil
	}
	if raw == "number" {
		return fieldType{kind: kindNumber}, nil
	}
	if raw == "[*]" {
		elem := fieldType{kind: kindRaw}
		return fieldType{kind: kindList, elem: &elem}, nil
	}
	if strings.HasPrefix(raw, "Map[") && strings.HasSuffix(raw, "]") {
		inside := strings.TrimSpace(raw[len("Map[") : len(raw)-1])
		comma := strings.Index(inside, ",")
		if comma == -1 {
			return fieldType{}, fmt.Errorf("unsupported map type %q", raw)
		}
		if strings.TrimSpace(inside[:comma]) != "string" {
			return fieldType{}, fmt.Errorf("unsupported map type %q", raw)
		}
		elem, err := parseFieldType(strings.TrimSpace(inside[comma+1:]), rootObject)
		if err != nil {
			return fieldType{}, err
		}
		return fieldType{kind: kindMap, elem: &elem}, nil
	}
	if strings.HasPrefix(raw, "[") && strings.HasSuffix(raw, "]") {
		elem, err := parseFieldType(strings.TrimSpace(raw[1:len(raw)-1]), rootObject)
		if err != nil {
			return fieldType{}, err
		}
		return fieldType{kind: kindList, elem: &elem}, nil
	}
	if strings.Contains(raw, " | ") {
		parts := strings.Split(raw, " | ")
		if len(parts) == 2 && parts[1] == "Reference Object" && strings.HasSuffix(parts[0], " Object") {
			target := goObjectName(parts[0], rootObject)
			return fieldType{
				kind:   kindReferenceUnion,
				name:   target + "OrReference",
				target: target,
			}, nil
		}
		return fieldType{}, fmt.Errorf("unsupported union type %q", raw)
	}
	if strings.HasSuffix(raw, " Object") {
		return fieldType{kind: kindObject, name: goObjectName(raw, rootObject)}, nil
	}
	return fieldType{}, fmt.Errorf("unsupported field type %q", raw)
}

func collectTypeObjects(
	node fieldType,
	objects map[string]struct{},
	goToRaw map[string]string,
	unions map[string]union,
) {
	switch node.kind {
	case kindObject:
		rawName, exists := goToRaw[node.name]
		if !exists {
			rawName = objectRawName(node.name)
			goToRaw[node.name] = rawName
		}
		objects[rawName] = struct{}{}
	case kindReferenceUnion:
		targetRaw, exists := goToRaw[node.target]
		if !exists {
			targetRaw = objectRawName(node.target)
			goToRaw[node.target] = targetRaw
		}
		objects[targetRaw] = struct{}{}
		objects["Reference Object"] = struct{}{}
		unions[node.name] = union{name: node.name, targetName: node.target}
	case kindList, kindMap:
		collectTypeObjects(*node.elem, objects, goToRaw, unions)
	}
}

func objectRawName(name string) string {
	known := map[string]string{
		"Document":              "OpenAPI Object",
		"ExternalDocumentation": "External Documentation Object",
		"MediaType":             "Media Type Object",
		"OAuthFlow":             "OAuth Flow Object",
		"OAuthFlows":            "OAuth Flows Object",
		"PathItem":              "Path Item Object",
		"RequestBody":           "Request Body Object",
		"SecurityRequirement":   "Security Requirement Object",
		"SecurityScheme":        "Security Scheme Object",
		"ServerVariable":        "Server Variable Object",
		"XML":                   "XML Object",
	}
	if raw, ok := known[name]; ok {
		return raw
	}
	return name + " Object"
}

func goObjectName(raw string, rootObject string) string {
	if raw == rootObject {
		return "Document"
	}
	base := strings.TrimSuffix(raw, " Object")
	words := strings.Fields(base)
	for index, word := range words {
		words[index] = exportedWord(word)
	}
	return strings.Join(words, "")
}

func goFieldName(raw string) string {
	known := map[string]string{
		"$ref":                   "Ref",
		"$self":                  "Self",
		"openapi":                "OpenAPI",
		"operationId":            "OperationID",
		"openIdConnectUrl":       "OpenIDConnectURL",
		"oauth2MetadataUrl":      "OAuth2MetadataURL",
		"authorizationUrl":       "AuthorizationURL",
		"deviceAuthorizationUrl": "DeviceAuthorizationURL",
		"tokenUrl":               "TokenURL",
		"refreshUrl":             "RefreshURL",
		"url":                    "URL",
		"xml":                    "XML",
	}
	if name, ok := known[raw]; ok {
		return name
	}
	runes := []rune(raw)
	if len(runes) == 0 {
		return "Field"
	}
	runes[0] = unicode.ToUpper(runes[0])
	name := string(runes)
	name = strings.ReplaceAll(name, "Id", "ID")
	name = strings.ReplaceAll(name, "Url", "URL")
	return name
}

func exportedWord(word string) string {
	switch strings.ToUpper(word) {
	case "OAUTH":
		return "OAuth"
	case "OPENAPI":
		return "OpenAPI"
	case "XML":
		return "XML"
	}
	runes := []rune(word)
	if len(runes) == 0 {
		return ""
	}
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}
