package main

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestDiscoverSourceDocumentationCatalogFindsObjectiveGaps(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	mustWriteFile(t, filepath.Join(root, "pkg", "clock", "clock.go"), `// Package clock controls time.
package clock

// Clock reports time.
type Clock interface {
	Now() int
}

func New() Clock { return nil }
`)
	mustWriteFile(t, filepath.Join(root, "pkg", "clock", "generated.go"), `// Code generated by clockgen; DO NOT EDIT.
package clock

type Generated struct{}
`)

	current := catalog{
		GoVersion: "1.26.6",
		Modules: []module{{
			Directory: "pkg/clock",
			Path:      "example.com/clock",
		}},
	}
	got, err := discoverSourceDocumentationCatalog(root, current)
	if err != nil {
		t.Fatalf("discoverSourceDocumentationCatalog() error = %v", err)
	}
	if len(got.Modules) != 1 {
		t.Fatalf("modules = %d, want 1", len(got.Modules))
	}
	module := got.Modules[0]
	if module.Packages != 1 || module.DocumentedPackages != 1 || module.MissingPackageComments != 0 {
		t.Fatalf("package summary = %#v", module)
	}
	if module.ExportedDeclarations != 4 || module.DocumentedDeclarations != 1 || module.MissingDeclarationComments != 2 {
		t.Fatalf("declaration summary = %#v", module)
	}
	if module.GeneratedFiles != 1 || module.GeneratedMissingComments != 1 {
		t.Fatalf("generated summary = %#v", module)
	}
	if len(module.Issues) != 3 {
		t.Fatalf("issues = %#v", module.Issues)
	}
}

func TestSourceDocumentationReportSeparatesMissingAndGeneratedGaps(t *testing.T) {
	t.Parallel()

	report := sourceDocumentationReport(sourceDocumentationCatalog{Modules: []sourceDocumentationModule{{
		Directory:                  "pkg/clock",
		Packages:                   1,
		MissingDeclarationComments: 2,
		GeneratedMissingComments:   1,
	}}})
	for _, expected := range []string{"# Source Documentation Audit", "`pkg/clock`", "2", "1"} {
		if !strings.Contains(report, expected) {
			t.Fatalf("report does not contain %q:\n%s", expected, report)
		}
	}
}

func TestDiscoverSourceDocumentationCatalogAcceptsGroupedDeclarationComments(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	mustWriteFile(t, filepath.Join(root, "pkg", "status", "status.go"), `// Package status defines states.
package status

// Status values describe lifecycle states.
const (
	Pending = "pending"
	Ready = "ready"
)
`)
	got, err := discoverSourceDocumentationCatalog(root, catalog{Modules: []module{{
		Directory: "pkg/status",
		Path:      "example.com/status",
	}}})
	if err != nil {
		t.Fatalf("discoverSourceDocumentationCatalog() error = %v", err)
	}
	module := got.Modules[0]
	if module.DocumentedDeclarations != 2 || module.MalformedComments != 0 {
		t.Fatalf("grouped declaration summary = %#v", module)
	}
}
