// Code generated by interface fixture. DO NOT EDIT.

package provider

// GeneratedClient proves generated code remains analyzed without driver policy.
type GeneratedClient interface { // want `api/interface-placement: exported interface GeneratedClient is declared in a configured provider package`
	GeneratedCall()
}
