stream.listeners.tcp = none
stream.listeners.ssl.1 = 5551
ssl_options.cacertfile = /certs/ca.pem
ssl_options.certfile = /certs/server.pem
ssl_options.keyfile = /certs/server-key.pem
ssl_options.verify = verify_peer
ssl_options.fail_if_no_peer_cert = true
ssl_options.versions.1 = tlsv1.3
ssl_options.versions.2 = tlsv1.2
stream.advertised_tls_host = localhost
stream.advertised_tls_port = 15571
