version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
