// Code generated by interfacenaming fixture. DO NOT EDIT.

package provider

type GeneratedClient interface { // want `api/interface-naming: exported interface GeneratedClient must start with Order and end with Port`
	Generate()
}
