// Code generated by blockingcontext fixture. DO NOT EDIT.

package blockingapi

func Generated(value string) error { // want `context/blocking-api-context: configured blocking API Generated requires context.Context`
	return nil
}
