// Code generated by modelgen; DO NOT EDIT.

package swagger20

import (
	"errors"
	"fmt"
	"strings"

	"github.com/faustbrian/golib/pkg/openapi/internal/modelaccess"
	"github.com/faustbrian/golib/pkg/openapi/jsonvalue"
	"github.com/faustbrian/golib/pkg/openapi/model"
	"github.com/faustbrian/golib/pkg/openapi/specversion"
)

// ErrInvalidDocument reports a root value that cannot select this OpenAPI dialect.
var ErrInvalidDocument = errors.New("invalid OpenAPI document")

// Version is the latest pinned patch used to generate this package.
const Version = "2.0"

// Decode selects this version-line model without discarding unknown or invalid nested fields.
func Decode(raw jsonvalue.Value) (Document, error) {
	document, ok := wrapDocument(raw)
	if !ok {
		return Document{}, fmt.Errorf("%w: root is not an object", ErrInvalidDocument)
	}
	selected, ok := modelaccess.String(raw, "swagger").Value()
	if !ok {
		return Document{}, fmt.Errorf("%w: specification version is missing or not a string", ErrInvalidDocument)
	}
	version, err := specversion.Parse(selected)
	if err != nil {
		return Document{}, fmt.Errorf("%w: %w", ErrInvalidDocument, err)
	}
	if version.Dialect() != specversion.DialectSwagger20 {
		return Document{}, fmt.Errorf("%w: wrong specification dialect", ErrInvalidDocument)
	}
	return document, nil
}

func stringValue(raw jsonvalue.Value) (string, bool) {
	return raw.Text()
}

func booleanValue(raw jsonvalue.Value) (bool, bool) {
	return raw.Bool()
}

func rawValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	return raw, raw.Kind() != jsonvalue.InvalidKind
}

func integerValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	text, ok := raw.NumberText()
	return raw, ok && !strings.ContainsAny(text, ".eE")
}

func numberValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	_, ok := raw.NumberText()
	return raw, ok
}

func anyPatternName(string) bool {
	return true
}

func extensionAwarePatternName(name string) bool {
	return !strings.HasPrefix(name, "x-")
}

func pathPatternName(name string) bool {
	return strings.HasPrefix(name, "/")
}

// Document is an immutable typed view of the Swagger Object.
type Document struct {
	raw jsonvalue.Value
}

func wrapDocument(raw jsonvalue.Value) (Document, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Document{}, false
	}
	return Document{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Document) Raw() jsonvalue.Value {
	return value.raw
}

// SpecificationVersion returns the exact selected patch revision.
func (value Document) SpecificationVersion() specversion.Version {
	selected, _ := modelaccess.String(value.raw, "swagger").Value()
	version, _ := specversion.Parse(selected)
	return version
}

// Extensions returns x- fields in source order.
func (value Document) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Swagger returns the "swagger" field with exact presence semantics.
func (value Document) Swagger() model.Field[string] {
	return modelaccess.String(value.raw, "swagger")
}

// Info returns the "info" field with exact presence semantics.
func (value Document) Info() model.Field[Info] {
	return modelaccess.Scalar(value.raw, "info", wrapInfo)
}

// Host returns the "host" field with exact presence semantics.
func (value Document) Host() model.Field[string] {
	return modelaccess.String(value.raw, "host")
}

// BasePath returns the "basePath" field with exact presence semantics.
func (value Document) BasePath() model.Field[string] {
	return modelaccess.String(value.raw, "basePath")
}

// Schemes returns the "schemes" field with exact presence semantics.
func (value Document) Schemes() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "schemes", stringValue)
}

// Consumes returns the "consumes" field with exact presence semantics.
func (value Document) Consumes() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "consumes", stringValue)
}

// Produces returns the "produces" field with exact presence semantics.
func (value Document) Produces() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "produces", stringValue)
}

// Paths returns the "paths" field with exact presence semantics.
func (value Document) Paths() model.Field[Paths] {
	return modelaccess.Scalar(value.raw, "paths", wrapPaths)
}

// Definitions returns the "definitions" field with exact presence semantics.
func (value Document) Definitions() model.Field[Definitions] {
	return modelaccess.Scalar(value.raw, "definitions", wrapDefinitions)
}

// Parameters returns the "parameters" field with exact presence semantics.
func (value Document) Parameters() model.Field[ParametersDefinitions] {
	return modelaccess.Scalar(value.raw, "parameters", wrapParametersDefinitions)
}

// Responses returns the "responses" field with exact presence semantics.
func (value Document) Responses() model.Field[ResponsesDefinitions] {
	return modelaccess.Scalar(value.raw, "responses", wrapResponsesDefinitions)
}

// SecurityDefinitions returns the "securityDefinitions" field with exact presence semantics.
func (value Document) SecurityDefinitions() model.Field[SecurityDefinitions] {
	return modelaccess.Scalar(value.raw, "securityDefinitions", wrapSecurityDefinitions)
}

// Security returns the "security" field with exact presence semantics.
func (value Document) Security() model.Field[model.List[SecurityRequirement]] {
	return modelaccess.List(value.raw, "security", wrapSecurityRequirement)
}

// Tags returns the "tags" field with exact presence semantics.
func (value Document) Tags() model.Field[model.List[Tag]] {
	return modelaccess.List(value.raw, "tags", wrapTag)
}

// ExternalDocs returns the "externalDocs" field with exact presence semantics.
func (value Document) ExternalDocs() model.Field[ExternalDocumentation] {
	return modelaccess.Scalar(value.raw, "externalDocs", wrapExternalDocumentation)
}

// Contact is an immutable typed view of the Contact Object.
type Contact struct {
	raw jsonvalue.Value
}

func wrapContact(raw jsonvalue.Value) (Contact, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Contact{}, false
	}
	return Contact{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Contact) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Contact) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value Contact) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// URL returns the "url" field with exact presence semantics.
func (value Contact) URL() model.Field[string] {
	return modelaccess.String(value.raw, "url")
}

// Email returns the "email" field with exact presence semantics.
func (value Contact) Email() model.Field[string] {
	return modelaccess.String(value.raw, "email")
}

// Definitions is an immutable typed view of the Definitions Object.
type Definitions struct {
	raw jsonvalue.Value
}

func wrapDefinitions(raw jsonvalue.Value) (Definitions, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Definitions{}, false
	}
	return Definitions{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Definitions) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Definitions) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value Definitions) Entries() model.Map[model.Field[Schema]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, wrapSchema)
}

// Example is an immutable typed view of the Example Object.
type Example struct {
	raw jsonvalue.Value
}

func wrapExample(raw jsonvalue.Value) (Example, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Example{}, false
	}
	return Example{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Example) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Example) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value Example) Entries() model.Map[model.Field[jsonvalue.Value]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, rawValue)
}

// ExternalDocumentation is an immutable typed view of the External Documentation Object.
type ExternalDocumentation struct {
	raw jsonvalue.Value
}

func wrapExternalDocumentation(raw jsonvalue.Value) (ExternalDocumentation, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ExternalDocumentation{}, false
	}
	return ExternalDocumentation{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value ExternalDocumentation) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value ExternalDocumentation) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Description returns the "description" field with exact presence semantics.
func (value ExternalDocumentation) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// URL returns the "url" field with exact presence semantics.
func (value ExternalDocumentation) URL() model.Field[string] {
	return modelaccess.String(value.raw, "url")
}

// Header is an immutable typed view of the Header Object.
type Header struct {
	raw jsonvalue.Value
}

func wrapHeader(raw jsonvalue.Value) (Header, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Header{}, false
	}
	return Header{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Header) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Header) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Description returns the "description" field with exact presence semantics.
func (value Header) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Type returns the "type" field with exact presence semantics.
func (value Header) Type() model.Field[string] {
	return modelaccess.String(value.raw, "type")
}

// Format returns the "format" field with exact presence semantics.
func (value Header) Format() model.Field[string] {
	return modelaccess.String(value.raw, "format")
}

// Items returns the "items" field with exact presence semantics.
func (value Header) Items() model.Field[Items] {
	return modelaccess.Scalar(value.raw, "items", wrapItems)
}

// CollectionFormat returns the "collectionFormat" field with exact presence semantics.
func (value Header) CollectionFormat() model.Field[string] {
	return modelaccess.String(value.raw, "collectionFormat")
}

// Default returns the "default" field with exact presence semantics.
func (value Header) Default() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "default")
}

// Maximum returns the "maximum" field with exact presence semantics.
func (value Header) Maximum() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maximum", numberValue)
}

// ExclusiveMaximum returns the "exclusiveMaximum" field with exact presence semantics.
func (value Header) ExclusiveMaximum() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "exclusiveMaximum")
}

// Minimum returns the "minimum" field with exact presence semantics.
func (value Header) Minimum() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minimum", numberValue)
}

// ExclusiveMinimum returns the "exclusiveMinimum" field with exact presence semantics.
func (value Header) ExclusiveMinimum() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "exclusiveMinimum")
}

// MaxLength returns the "maxLength" field with exact presence semantics.
func (value Header) MaxLength() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maxLength", integerValue)
}

// MinLength returns the "minLength" field with exact presence semantics.
func (value Header) MinLength() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minLength", integerValue)
}

// Pattern returns the "pattern" field with exact presence semantics.
func (value Header) Pattern() model.Field[string] {
	return modelaccess.String(value.raw, "pattern")
}

// MaxItems returns the "maxItems" field with exact presence semantics.
func (value Header) MaxItems() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maxItems", integerValue)
}

// MinItems returns the "minItems" field with exact presence semantics.
func (value Header) MinItems() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minItems", integerValue)
}

// UniqueItems returns the "uniqueItems" field with exact presence semantics.
func (value Header) UniqueItems() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "uniqueItems")
}

// Enum returns the "enum" field with exact presence semantics.
func (value Header) Enum() model.Field[model.List[jsonvalue.Value]] {
	return modelaccess.List(value.raw, "enum", rawValue)
}

// MultipleOf returns the "multipleOf" field with exact presence semantics.
func (value Header) MultipleOf() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "multipleOf", numberValue)
}

// Headers is an immutable typed view of the Headers Object.
type Headers struct {
	raw jsonvalue.Value
}

func wrapHeaders(raw jsonvalue.Value) (Headers, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Headers{}, false
	}
	return Headers{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Headers) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Headers) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value Headers) Entries() model.Map[model.Field[Header]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, wrapHeader)
}

// Info is an immutable typed view of the Info Object.
type Info struct {
	raw jsonvalue.Value
}

func wrapInfo(raw jsonvalue.Value) (Info, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Info{}, false
	}
	return Info{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Info) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Info) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Title returns the "title" field with exact presence semantics.
func (value Info) Title() model.Field[string] {
	return modelaccess.String(value.raw, "title")
}

// Description returns the "description" field with exact presence semantics.
func (value Info) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// TermsOfService returns the "termsOfService" field with exact presence semantics.
func (value Info) TermsOfService() model.Field[string] {
	return modelaccess.String(value.raw, "termsOfService")
}

// Contact returns the "contact" field with exact presence semantics.
func (value Info) Contact() model.Field[Contact] {
	return modelaccess.Scalar(value.raw, "contact", wrapContact)
}

// License returns the "license" field with exact presence semantics.
func (value Info) License() model.Field[License] {
	return modelaccess.Scalar(value.raw, "license", wrapLicense)
}

// Version returns the "version" field with exact presence semantics.
func (value Info) Version() model.Field[string] {
	return modelaccess.String(value.raw, "version")
}

// Items is an immutable typed view of the Items Object.
type Items struct {
	raw jsonvalue.Value
}

func wrapItems(raw jsonvalue.Value) (Items, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Items{}, false
	}
	return Items{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Items) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Items) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Type returns the "type" field with exact presence semantics.
func (value Items) Type() model.Field[string] {
	return modelaccess.String(value.raw, "type")
}

// Format returns the "format" field with exact presence semantics.
func (value Items) Format() model.Field[string] {
	return modelaccess.String(value.raw, "format")
}

// Items returns the "items" field with exact presence semantics.
func (value Items) Items() model.Field[Items] {
	return modelaccess.Scalar(value.raw, "items", wrapItems)
}

// CollectionFormat returns the "collectionFormat" field with exact presence semantics.
func (value Items) CollectionFormat() model.Field[string] {
	return modelaccess.String(value.raw, "collectionFormat")
}

// Default returns the "default" field with exact presence semantics.
func (value Items) Default() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "default")
}

// Maximum returns the "maximum" field with exact presence semantics.
func (value Items) Maximum() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maximum", numberValue)
}

// ExclusiveMaximum returns the "exclusiveMaximum" field with exact presence semantics.
func (value Items) ExclusiveMaximum() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "exclusiveMaximum")
}

// Minimum returns the "minimum" field with exact presence semantics.
func (value Items) Minimum() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minimum", numberValue)
}

// ExclusiveMinimum returns the "exclusiveMinimum" field with exact presence semantics.
func (value Items) ExclusiveMinimum() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "exclusiveMinimum")
}

// MaxLength returns the "maxLength" field with exact presence semantics.
func (value Items) MaxLength() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maxLength", integerValue)
}

// MinLength returns the "minLength" field with exact presence semantics.
func (value Items) MinLength() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minLength", integerValue)
}

// Pattern returns the "pattern" field with exact presence semantics.
func (value Items) Pattern() model.Field[string] {
	return modelaccess.String(value.raw, "pattern")
}

// MaxItems returns the "maxItems" field with exact presence semantics.
func (value Items) MaxItems() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maxItems", integerValue)
}

// MinItems returns the "minItems" field with exact presence semantics.
func (value Items) MinItems() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minItems", integerValue)
}

// UniqueItems returns the "uniqueItems" field with exact presence semantics.
func (value Items) UniqueItems() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "uniqueItems")
}

// Enum returns the "enum" field with exact presence semantics.
func (value Items) Enum() model.Field[model.List[jsonvalue.Value]] {
	return modelaccess.List(value.raw, "enum", rawValue)
}

// MultipleOf returns the "multipleOf" field with exact presence semantics.
func (value Items) MultipleOf() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "multipleOf", numberValue)
}

// License is an immutable typed view of the License Object.
type License struct {
	raw jsonvalue.Value
}

func wrapLicense(raw jsonvalue.Value) (License, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return License{}, false
	}
	return License{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value License) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value License) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value License) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// URL returns the "url" field with exact presence semantics.
func (value License) URL() model.Field[string] {
	return modelaccess.String(value.raw, "url")
}

// Operation is an immutable typed view of the Operation Object.
type Operation struct {
	raw jsonvalue.Value
}

func wrapOperation(raw jsonvalue.Value) (Operation, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Operation{}, false
	}
	return Operation{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Operation) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Operation) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Tags returns the "tags" field with exact presence semantics.
func (value Operation) Tags() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "tags", stringValue)
}

// Summary returns the "summary" field with exact presence semantics.
func (value Operation) Summary() model.Field[string] {
	return modelaccess.String(value.raw, "summary")
}

// Description returns the "description" field with exact presence semantics.
func (value Operation) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// ExternalDocs returns the "externalDocs" field with exact presence semantics.
func (value Operation) ExternalDocs() model.Field[ExternalDocumentation] {
	return modelaccess.Scalar(value.raw, "externalDocs", wrapExternalDocumentation)
}

// OperationID returns the "operationId" field with exact presence semantics.
func (value Operation) OperationID() model.Field[string] {
	return modelaccess.String(value.raw, "operationId")
}

// Consumes returns the "consumes" field with exact presence semantics.
func (value Operation) Consumes() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "consumes", stringValue)
}

// Produces returns the "produces" field with exact presence semantics.
func (value Operation) Produces() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "produces", stringValue)
}

// Parameters returns the "parameters" field with exact presence semantics.
func (value Operation) Parameters() model.Field[model.List[ParameterOrReference]] {
	return modelaccess.List(value.raw, "parameters", wrapParameterOrReference)
}

// Responses returns the "responses" field with exact presence semantics.
func (value Operation) Responses() model.Field[Responses] {
	return modelaccess.Scalar(value.raw, "responses", wrapResponses)
}

// Schemes returns the "schemes" field with exact presence semantics.
func (value Operation) Schemes() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "schemes", stringValue)
}

// Deprecated returns the "deprecated" field with exact presence semantics.
func (value Operation) Deprecated() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "deprecated")
}

// Security returns the "security" field with exact presence semantics.
func (value Operation) Security() model.Field[model.List[SecurityRequirement]] {
	return modelaccess.List(value.raw, "security", wrapSecurityRequirement)
}

// Parameter is an immutable typed view of the Parameter Object.
type Parameter struct {
	raw jsonvalue.Value
}

func wrapParameter(raw jsonvalue.Value) (Parameter, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Parameter{}, false
	}
	return Parameter{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Parameter) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Parameter) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value Parameter) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// In returns the "in" field with exact presence semantics.
func (value Parameter) In() model.Field[string] {
	return modelaccess.String(value.raw, "in")
}

// Description returns the "description" field with exact presence semantics.
func (value Parameter) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Required returns the "required" field with exact presence semantics.
func (value Parameter) Required() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "required")
}

// Schema returns the "schema" field with exact presence semantics.
func (value Parameter) Schema() model.Field[Schema] {
	return modelaccess.Scalar(value.raw, "schema", wrapSchema)
}

// Type returns the "type" field with exact presence semantics.
func (value Parameter) Type() model.Field[string] {
	return modelaccess.String(value.raw, "type")
}

// Format returns the "format" field with exact presence semantics.
func (value Parameter) Format() model.Field[string] {
	return modelaccess.String(value.raw, "format")
}

// AllowEmptyValue returns the "allowEmptyValue" field with exact presence semantics.
func (value Parameter) AllowEmptyValue() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "allowEmptyValue")
}

// Items returns the "items" field with exact presence semantics.
func (value Parameter) Items() model.Field[Items] {
	return modelaccess.Scalar(value.raw, "items", wrapItems)
}

// CollectionFormat returns the "collectionFormat" field with exact presence semantics.
func (value Parameter) CollectionFormat() model.Field[string] {
	return modelaccess.String(value.raw, "collectionFormat")
}

// Default returns the "default" field with exact presence semantics.
func (value Parameter) Default() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "default")
}

// Maximum returns the "maximum" field with exact presence semantics.
func (value Parameter) Maximum() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maximum", numberValue)
}

// ExclusiveMaximum returns the "exclusiveMaximum" field with exact presence semantics.
func (value Parameter) ExclusiveMaximum() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "exclusiveMaximum")
}

// Minimum returns the "minimum" field with exact presence semantics.
func (value Parameter) Minimum() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minimum", numberValue)
}

// ExclusiveMinimum returns the "exclusiveMinimum" field with exact presence semantics.
func (value Parameter) ExclusiveMinimum() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "exclusiveMinimum")
}

// MaxLength returns the "maxLength" field with exact presence semantics.
func (value Parameter) MaxLength() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maxLength", integerValue)
}

// MinLength returns the "minLength" field with exact presence semantics.
func (value Parameter) MinLength() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minLength", integerValue)
}

// Pattern returns the "pattern" field with exact presence semantics.
func (value Parameter) Pattern() model.Field[string] {
	return modelaccess.String(value.raw, "pattern")
}

// MaxItems returns the "maxItems" field with exact presence semantics.
func (value Parameter) MaxItems() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "maxItems", integerValue)
}

// MinItems returns the "minItems" field with exact presence semantics.
func (value Parameter) MinItems() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "minItems", integerValue)
}

// UniqueItems returns the "uniqueItems" field with exact presence semantics.
func (value Parameter) UniqueItems() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "uniqueItems")
}

// Enum returns the "enum" field with exact presence semantics.
func (value Parameter) Enum() model.Field[model.List[jsonvalue.Value]] {
	return modelaccess.List(value.raw, "enum", rawValue)
}

// MultipleOf returns the "multipleOf" field with exact presence semantics.
func (value Parameter) MultipleOf() model.Field[jsonvalue.Value] {
	return modelaccess.Scalar(value.raw, "multipleOf", numberValue)
}

// ParametersDefinitions is an immutable typed view of the Parameters Definitions Object.
type ParametersDefinitions struct {
	raw jsonvalue.Value
}

func wrapParametersDefinitions(raw jsonvalue.Value) (ParametersDefinitions, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ParametersDefinitions{}, false
	}
	return ParametersDefinitions{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value ParametersDefinitions) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value ParametersDefinitions) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value ParametersDefinitions) Entries() model.Map[model.Field[Parameter]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, wrapParameter)
}

// PathItem is an immutable typed view of the Path Item Object.
type PathItem struct {
	raw jsonvalue.Value
}

func wrapPathItem(raw jsonvalue.Value) (PathItem, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return PathItem{}, false
	}
	return PathItem{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value PathItem) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value PathItem) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Ref returns the "$ref" field with exact presence semantics.
func (value PathItem) Ref() model.Field[string] {
	return modelaccess.String(value.raw, "$ref")
}

// Get returns the "get" field with exact presence semantics.
func (value PathItem) Get() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "get", wrapOperation)
}

// Put returns the "put" field with exact presence semantics.
func (value PathItem) Put() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "put", wrapOperation)
}

// Post returns the "post" field with exact presence semantics.
func (value PathItem) Post() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "post", wrapOperation)
}

// Delete returns the "delete" field with exact presence semantics.
func (value PathItem) Delete() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "delete", wrapOperation)
}

// Options returns the "options" field with exact presence semantics.
func (value PathItem) Options() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "options", wrapOperation)
}

// Head returns the "head" field with exact presence semantics.
func (value PathItem) Head() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "head", wrapOperation)
}

// Patch returns the "patch" field with exact presence semantics.
func (value PathItem) Patch() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "patch", wrapOperation)
}

// Parameters returns the "parameters" field with exact presence semantics.
func (value PathItem) Parameters() model.Field[model.List[ParameterOrReference]] {
	return modelaccess.List(value.raw, "parameters", wrapParameterOrReference)
}

// Paths is an immutable typed view of the Paths Object.
type Paths struct {
	raw jsonvalue.Value
}

func wrapPaths(raw jsonvalue.Value) (Paths, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Paths{}, false
	}
	return Paths{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Paths) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Paths) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value Paths) Entries() model.Map[model.Field[PathItem]] {
	return modelaccess.PatternEntries(value.raw, []string{}, pathPatternName, wrapPathItem)
}

// Reference is an immutable typed view of the Reference Object.
type Reference struct {
	raw jsonvalue.Value
}

func wrapReference(raw jsonvalue.Value) (Reference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Reference{}, false
	}
	return Reference{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Reference) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Reference) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Ref returns the "$ref" field with exact presence semantics.
func (value Reference) Ref() model.Field[string] {
	return modelaccess.String(value.raw, "$ref")
}

// Response is an immutable typed view of the Response Object.
type Response struct {
	raw jsonvalue.Value
}

func wrapResponse(raw jsonvalue.Value) (Response, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Response{}, false
	}
	return Response{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Response) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Response) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Description returns the "description" field with exact presence semantics.
func (value Response) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Schema returns the "schema" field with exact presence semantics.
func (value Response) Schema() model.Field[Schema] {
	return modelaccess.Scalar(value.raw, "schema", wrapSchema)
}

// Headers returns the "headers" field with exact presence semantics.
func (value Response) Headers() model.Field[Headers] {
	return modelaccess.Scalar(value.raw, "headers", wrapHeaders)
}

// Examples returns the "examples" field with exact presence semantics.
func (value Response) Examples() model.Field[Example] {
	return modelaccess.Scalar(value.raw, "examples", wrapExample)
}

// Responses is an immutable typed view of the Responses Object.
type Responses struct {
	raw jsonvalue.Value
}

func wrapResponses(raw jsonvalue.Value) (Responses, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Responses{}, false
	}
	return Responses{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Responses) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Responses) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Default returns the "default" field with exact presence semantics.
func (value Responses) Default() model.Field[ResponseOrReference] {
	return modelaccess.Scalar(value.raw, "default", wrapResponseOrReference)
}

// Entries returns typed patterned fields in source order.
func (value Responses) Entries() model.Map[model.Field[ResponseOrReference]] {
	return modelaccess.PatternEntries(value.raw, []string{"default"}, extensionAwarePatternName, wrapResponseOrReference)
}

// ResponsesDefinitions is an immutable typed view of the Responses Definitions Object.
type ResponsesDefinitions struct {
	raw jsonvalue.Value
}

func wrapResponsesDefinitions(raw jsonvalue.Value) (ResponsesDefinitions, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ResponsesDefinitions{}, false
	}
	return ResponsesDefinitions{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value ResponsesDefinitions) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value ResponsesDefinitions) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value ResponsesDefinitions) Entries() model.Map[model.Field[Response]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, wrapResponse)
}

// Schema is an immutable typed view of the Schema Object.
type Schema struct {
	raw jsonvalue.Value
}

func wrapSchema(raw jsonvalue.Value) (Schema, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Schema{}, false
	}
	return Schema{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Schema) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Schema) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Discriminator returns the "discriminator" field with exact presence semantics.
func (value Schema) Discriminator() model.Field[string] {
	return modelaccess.String(value.raw, "discriminator")
}

// ReadOnly returns the "readOnly" field with exact presence semantics.
func (value Schema) ReadOnly() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "readOnly")
}

// XML returns the "xml" field with exact presence semantics.
func (value Schema) XML() model.Field[XML] {
	return modelaccess.Scalar(value.raw, "xml", wrapXML)
}

// ExternalDocs returns the "externalDocs" field with exact presence semantics.
func (value Schema) ExternalDocs() model.Field[ExternalDocumentation] {
	return modelaccess.Scalar(value.raw, "externalDocs", wrapExternalDocumentation)
}

// Example returns the "example" field with exact presence semantics.
func (value Schema) Example() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "example")
}

// Scopes is an immutable typed view of the Scopes Object.
type Scopes struct {
	raw jsonvalue.Value
}

func wrapScopes(raw jsonvalue.Value) (Scopes, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Scopes{}, false
	}
	return Scopes{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Scopes) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Scopes) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value Scopes) Entries() model.Map[model.Field[string]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, stringValue)
}

// SecurityDefinitions is an immutable typed view of the Security Definitions Object.
type SecurityDefinitions struct {
	raw jsonvalue.Value
}

func wrapSecurityDefinitions(raw jsonvalue.Value) (SecurityDefinitions, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return SecurityDefinitions{}, false
	}
	return SecurityDefinitions{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value SecurityDefinitions) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value SecurityDefinitions) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value SecurityDefinitions) Entries() model.Map[model.Field[SecurityScheme]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, wrapSecurityScheme)
}

// SecurityRequirement is an immutable typed view of the Security Requirement Object.
type SecurityRequirement struct {
	raw jsonvalue.Value
}

func wrapSecurityRequirement(raw jsonvalue.Value) (SecurityRequirement, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return SecurityRequirement{}, false
	}
	return SecurityRequirement{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value SecurityRequirement) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value SecurityRequirement) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value SecurityRequirement) Entries() model.Map[model.Field[model.List[string]]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, func(raw jsonvalue.Value) (model.List[string], bool) { return modelaccess.ListValue(raw, stringValue) })
}

// SecurityScheme is an immutable typed view of the Security Scheme Object.
type SecurityScheme struct {
	raw jsonvalue.Value
}

func wrapSecurityScheme(raw jsonvalue.Value) (SecurityScheme, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return SecurityScheme{}, false
	}
	return SecurityScheme{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value SecurityScheme) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value SecurityScheme) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Type returns the "type" field with exact presence semantics.
func (value SecurityScheme) Type() model.Field[string] {
	return modelaccess.String(value.raw, "type")
}

// Description returns the "description" field with exact presence semantics.
func (value SecurityScheme) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Name returns the "name" field with exact presence semantics.
func (value SecurityScheme) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// In returns the "in" field with exact presence semantics.
func (value SecurityScheme) In() model.Field[string] {
	return modelaccess.String(value.raw, "in")
}

// Flow returns the "flow" field with exact presence semantics.
func (value SecurityScheme) Flow() model.Field[string] {
	return modelaccess.String(value.raw, "flow")
}

// AuthorizationURL returns the "authorizationUrl" field with exact presence semantics.
func (value SecurityScheme) AuthorizationURL() model.Field[string] {
	return modelaccess.String(value.raw, "authorizationUrl")
}

// TokenURL returns the "tokenUrl" field with exact presence semantics.
func (value SecurityScheme) TokenURL() model.Field[string] {
	return modelaccess.String(value.raw, "tokenUrl")
}

// Scopes returns the "scopes" field with exact presence semantics.
func (value SecurityScheme) Scopes() model.Field[Scopes] {
	return modelaccess.Scalar(value.raw, "scopes", wrapScopes)
}

// Tag is an immutable typed view of the Tag Object.
type Tag struct {
	raw jsonvalue.Value
}

func wrapTag(raw jsonvalue.Value) (Tag, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Tag{}, false
	}
	return Tag{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Tag) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Tag) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value Tag) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// Description returns the "description" field with exact presence semantics.
func (value Tag) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// ExternalDocs returns the "externalDocs" field with exact presence semantics.
func (value Tag) ExternalDocs() model.Field[ExternalDocumentation] {
	return modelaccess.Scalar(value.raw, "externalDocs", wrapExternalDocumentation)
}

// XML is an immutable typed view of the XML Object.
type XML struct {
	raw jsonvalue.Value
}

func wrapXML(raw jsonvalue.Value) (XML, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return XML{}, false
	}
	return XML{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value XML) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value XML) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value XML) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// Namespace returns the "namespace" field with exact presence semantics.
func (value XML) Namespace() model.Field[string] {
	return modelaccess.String(value.raw, "namespace")
}

// Prefix returns the "prefix" field with exact presence semantics.
func (value XML) Prefix() model.Field[string] {
	return modelaccess.String(value.raw, "prefix")
}

// Attribute returns the "attribute" field with exact presence semantics.
func (value XML) Attribute() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "attribute")
}

// Wrapped returns the "wrapped" field with exact presence semantics.
func (value XML) Wrapped() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "wrapped")
}

// ParameterOrReference preserves either a Parameter or Reference Object.
type ParameterOrReference struct {
	raw jsonvalue.Value
}

func wrapParameterOrReference(raw jsonvalue.Value) (ParameterOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ParameterOrReference{}, false
	}
	return ParameterOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value ParameterOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value ParameterOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value ParameterOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// Parameter returns the selected target object.
func (value ParameterOrReference) Parameter() (Parameter, bool) {
	if value.IsReference() {
		return Parameter{}, false
	}
	return wrapParameter(value.raw)
}

// ResponseOrReference preserves either a Response or Reference Object.
type ResponseOrReference struct {
	raw jsonvalue.Value
}

func wrapResponseOrReference(raw jsonvalue.Value) (ResponseOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ResponseOrReference{}, false
	}
	return ResponseOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value ResponseOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value ResponseOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value ResponseOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// Response returns the selected target object.
func (value ResponseOrReference) Response() (Response, bool) {
	if value.IsReference() {
		return Response{}, false
	}
	return wrapResponse(value.raw)
}
