unleash:
  integration: false
  dry-run: false
  workers: 2
  test-cpu: 2
  timeout-coefficient: 10
  threshold:
    efficacy: 90
    mutant-coverage: 75
mutants:
  arithmetic-base:
    enabled: true
  conditionals-boundary:
    enabled: true
  conditionals-negation:
    enabled: true
  increment-decrement:
    enabled: true
  invert-negatives:
    enabled: true
