// Code generated by nostoredcontext fixture. DO NOT EDIT.

package contextstore

import "context"

type generated struct {
	ctx context.Context // want `context/no-stored-context: struct field stores a context lifecycle`
}
