// Code generated by metric name fixture. DO NOT EDIT.

package metricnameconsumer

import (
	"labelmodel"
	"metricsink"
)

func RecordGenerated(name labelmodel.LabelName) {
	metricsink.Label(string(name)) // want `observability/dynamic-label-name: labelmodel.LabelName flows to metric label name metricsink.Label argument 1`
}
