// Code generated by nounsafe fixture. DO NOT EDIT.

package unsafeuse

import unsafealias "unsafe" // want `security/no-unsafe: production package imports unsafe`

func GeneratedPointer(value *int) unsafealias.Pointer {
	return unsafealias.Pointer(value)
}
