// Code generated by fixture. DO NOT EDIT.

package globalgoroutine

var generated = func() int {
	go work() // want `lifecycle/no-global-goroutine: package initializer starts a goroutine without caller-visible ownership`
	return 1
}()
