// Code generated by constructorgoroutine fixture. DO NOT EDIT.

package constructors

func NewGenerated() int {
	go work() // want `lifecycle/no-constructor-goroutine: constructor NewGenerated starts a goroutine without caller-visible ownership`
	return 1
}
