// Code generated by modelgen; DO NOT EDIT.

package oas31

import (
	"errors"
	"fmt"
	"strings"

	"github.com/faustbrian/golib/pkg/openapi/internal/modelaccess"
	"github.com/faustbrian/golib/pkg/openapi/jsonvalue"
	"github.com/faustbrian/golib/pkg/openapi/model"
	"github.com/faustbrian/golib/pkg/openapi/specversion"
)

// ErrInvalidDocument reports a root value that cannot select this OpenAPI dialect.
var ErrInvalidDocument = errors.New("invalid OpenAPI document")

// Version is the latest pinned patch used to generate this package.
const Version = "3.1.2"

// Decode selects this version-line model without discarding unknown or invalid nested fields.
func Decode(raw jsonvalue.Value) (Document, error) {
	document, ok := wrapDocument(raw)
	if !ok {
		return Document{}, fmt.Errorf("%w: root is not an object", ErrInvalidDocument)
	}
	selected, ok := modelaccess.String(raw, "openapi").Value()
	if !ok {
		return Document{}, fmt.Errorf("%w: specification version is missing or not a string", ErrInvalidDocument)
	}
	version, err := specversion.Parse(selected)
	if err != nil {
		return Document{}, fmt.Errorf("%w: %w", ErrInvalidDocument, err)
	}
	if version.Dialect() != specversion.DialectOAS31 {
		return Document{}, fmt.Errorf("%w: wrong specification dialect", ErrInvalidDocument)
	}
	return document, nil
}

func stringValue(raw jsonvalue.Value) (string, bool) {
	return raw.Text()
}

func booleanValue(raw jsonvalue.Value) (bool, bool) {
	return raw.Bool()
}

func rawValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	return raw, raw.Kind() != jsonvalue.InvalidKind
}

func integerValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	text, ok := raw.NumberText()
	return raw, ok && !strings.ContainsAny(text, ".eE")
}

func numberValue(raw jsonvalue.Value) (jsonvalue.Value, bool) {
	_, ok := raw.NumberText()
	return raw, ok
}

func anyPatternName(string) bool {
	return true
}

func extensionAwarePatternName(name string) bool {
	return !strings.HasPrefix(name, "x-")
}

func pathPatternName(name string) bool {
	return strings.HasPrefix(name, "/")
}

// Document is an immutable typed view of the OpenAPI Object.
type Document struct {
	raw jsonvalue.Value
}

func wrapDocument(raw jsonvalue.Value) (Document, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Document{}, false
	}
	return Document{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Document) Raw() jsonvalue.Value {
	return value.raw
}

// SpecificationVersion returns the exact selected patch revision.
func (value Document) SpecificationVersion() specversion.Version {
	selected, _ := modelaccess.String(value.raw, "openapi").Value()
	version, _ := specversion.Parse(selected)
	return version
}

// Extensions returns x- fields in source order.
func (value Document) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// OpenAPI returns the "openapi" field with exact presence semantics.
func (value Document) OpenAPI() model.Field[string] {
	return modelaccess.String(value.raw, "openapi")
}

// Info returns the "info" field with exact presence semantics.
func (value Document) Info() model.Field[Info] {
	return modelaccess.Scalar(value.raw, "info", wrapInfo)
}

// JsonSchemaDialect returns the "jsonSchemaDialect" field with exact presence semantics.
func (value Document) JsonSchemaDialect() model.Field[string] {
	return modelaccess.String(value.raw, "jsonSchemaDialect")
}

// Servers returns the "servers" field with exact presence semantics.
func (value Document) Servers() model.Field[model.List[Server]] {
	return modelaccess.List(value.raw, "servers", wrapServer)
}

// Paths returns the "paths" field with exact presence semantics.
func (value Document) Paths() model.Field[Paths] {
	return modelaccess.Scalar(value.raw, "paths", wrapPaths)
}

// Webhooks returns the "webhooks" field with exact presence semantics.
func (value Document) Webhooks() model.Field[model.Map[PathItem]] {
	return modelaccess.Map(value.raw, "webhooks", wrapPathItem)
}

// Components returns the "components" field with exact presence semantics.
func (value Document) Components() model.Field[Components] {
	return modelaccess.Scalar(value.raw, "components", wrapComponents)
}

// Security returns the "security" field with exact presence semantics.
func (value Document) Security() model.Field[model.List[SecurityRequirement]] {
	return modelaccess.List(value.raw, "security", wrapSecurityRequirement)
}

// Tags returns the "tags" field with exact presence semantics.
func (value Document) Tags() model.Field[model.List[Tag]] {
	return modelaccess.List(value.raw, "tags", wrapTag)
}

// ExternalDocs returns the "externalDocs" field with exact presence semantics.
func (value Document) ExternalDocs() model.Field[ExternalDocumentation] {
	return modelaccess.Scalar(value.raw, "externalDocs", wrapExternalDocumentation)
}

// Callback is an immutable typed view of the Callback Object.
type Callback struct {
	raw jsonvalue.Value
}

func wrapCallback(raw jsonvalue.Value) (Callback, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Callback{}, false
	}
	return Callback{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Callback) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Callback) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value Callback) Entries() model.Map[model.Field[PathItem]] {
	return modelaccess.PatternEntries(value.raw, []string{}, extensionAwarePatternName, wrapPathItem)
}

// Components is an immutable typed view of the Components Object.
type Components struct {
	raw jsonvalue.Value
}

func wrapComponents(raw jsonvalue.Value) (Components, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Components{}, false
	}
	return Components{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Components) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Components) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Schemas returns the "schemas" field with exact presence semantics.
func (value Components) Schemas() model.Field[model.Map[Schema]] {
	return modelaccess.Map(value.raw, "schemas", wrapSchema)
}

// Responses returns the "responses" field with exact presence semantics.
func (value Components) Responses() model.Field[model.Map[ResponseOrReference]] {
	return modelaccess.Map(value.raw, "responses", wrapResponseOrReference)
}

// Parameters returns the "parameters" field with exact presence semantics.
func (value Components) Parameters() model.Field[model.Map[ParameterOrReference]] {
	return modelaccess.Map(value.raw, "parameters", wrapParameterOrReference)
}

// Examples returns the "examples" field with exact presence semantics.
func (value Components) Examples() model.Field[model.Map[ExampleOrReference]] {
	return modelaccess.Map(value.raw, "examples", wrapExampleOrReference)
}

// RequestBodies returns the "requestBodies" field with exact presence semantics.
func (value Components) RequestBodies() model.Field[model.Map[RequestBodyOrReference]] {
	return modelaccess.Map(value.raw, "requestBodies", wrapRequestBodyOrReference)
}

// Headers returns the "headers" field with exact presence semantics.
func (value Components) Headers() model.Field[model.Map[HeaderOrReference]] {
	return modelaccess.Map(value.raw, "headers", wrapHeaderOrReference)
}

// SecuritySchemes returns the "securitySchemes" field with exact presence semantics.
func (value Components) SecuritySchemes() model.Field[model.Map[SecuritySchemeOrReference]] {
	return modelaccess.Map(value.raw, "securitySchemes", wrapSecuritySchemeOrReference)
}

// Links returns the "links" field with exact presence semantics.
func (value Components) Links() model.Field[model.Map[LinkOrReference]] {
	return modelaccess.Map(value.raw, "links", wrapLinkOrReference)
}

// Callbacks returns the "callbacks" field with exact presence semantics.
func (value Components) Callbacks() model.Field[model.Map[CallbackOrReference]] {
	return modelaccess.Map(value.raw, "callbacks", wrapCallbackOrReference)
}

// PathItems returns the "pathItems" field with exact presence semantics.
func (value Components) PathItems() model.Field[model.Map[PathItem]] {
	return modelaccess.Map(value.raw, "pathItems", wrapPathItem)
}

// Contact is an immutable typed view of the Contact Object.
type Contact struct {
	raw jsonvalue.Value
}

func wrapContact(raw jsonvalue.Value) (Contact, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Contact{}, false
	}
	return Contact{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Contact) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Contact) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value Contact) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// URL returns the "url" field with exact presence semantics.
func (value Contact) URL() model.Field[string] {
	return modelaccess.String(value.raw, "url")
}

// Email returns the "email" field with exact presence semantics.
func (value Contact) Email() model.Field[string] {
	return modelaccess.String(value.raw, "email")
}

// Discriminator is an immutable typed view of the Discriminator Object.
type Discriminator struct {
	raw jsonvalue.Value
}

func wrapDiscriminator(raw jsonvalue.Value) (Discriminator, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Discriminator{}, false
	}
	return Discriminator{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Discriminator) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Discriminator) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// PropertyName returns the "propertyName" field with exact presence semantics.
func (value Discriminator) PropertyName() model.Field[string] {
	return modelaccess.String(value.raw, "propertyName")
}

// Mapping returns the "mapping" field with exact presence semantics.
func (value Discriminator) Mapping() model.Field[model.Map[string]] {
	return modelaccess.Map(value.raw, "mapping", stringValue)
}

// Encoding is an immutable typed view of the Encoding Object.
type Encoding struct {
	raw jsonvalue.Value
}

func wrapEncoding(raw jsonvalue.Value) (Encoding, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Encoding{}, false
	}
	return Encoding{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Encoding) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Encoding) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// ContentType returns the "contentType" field with exact presence semantics.
func (value Encoding) ContentType() model.Field[string] {
	return modelaccess.String(value.raw, "contentType")
}

// Headers returns the "headers" field with exact presence semantics.
func (value Encoding) Headers() model.Field[model.Map[HeaderOrReference]] {
	return modelaccess.Map(value.raw, "headers", wrapHeaderOrReference)
}

// Style returns the "style" field with exact presence semantics.
func (value Encoding) Style() model.Field[string] {
	return modelaccess.String(value.raw, "style")
}

// Explode returns the "explode" field with exact presence semantics.
func (value Encoding) Explode() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "explode")
}

// AllowReserved returns the "allowReserved" field with exact presence semantics.
func (value Encoding) AllowReserved() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "allowReserved")
}

// Example is an immutable typed view of the Example Object.
type Example struct {
	raw jsonvalue.Value
}

func wrapExample(raw jsonvalue.Value) (Example, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Example{}, false
	}
	return Example{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Example) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Example) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Summary returns the "summary" field with exact presence semantics.
func (value Example) Summary() model.Field[string] {
	return modelaccess.String(value.raw, "summary")
}

// Description returns the "description" field with exact presence semantics.
func (value Example) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Value returns the "value" field with exact presence semantics.
func (value Example) Value() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "value")
}

// ExternalValue returns the "externalValue" field with exact presence semantics.
func (value Example) ExternalValue() model.Field[string] {
	return modelaccess.String(value.raw, "externalValue")
}

// ExternalDocumentation is an immutable typed view of the External Documentation Object.
type ExternalDocumentation struct {
	raw jsonvalue.Value
}

func wrapExternalDocumentation(raw jsonvalue.Value) (ExternalDocumentation, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ExternalDocumentation{}, false
	}
	return ExternalDocumentation{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value ExternalDocumentation) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value ExternalDocumentation) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Description returns the "description" field with exact presence semantics.
func (value ExternalDocumentation) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// URL returns the "url" field with exact presence semantics.
func (value ExternalDocumentation) URL() model.Field[string] {
	return modelaccess.String(value.raw, "url")
}

// Header is an immutable typed view of the Header Object.
type Header struct {
	raw jsonvalue.Value
}

func wrapHeader(raw jsonvalue.Value) (Header, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Header{}, false
	}
	return Header{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Header) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Header) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Description returns the "description" field with exact presence semantics.
func (value Header) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Required returns the "required" field with exact presence semantics.
func (value Header) Required() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "required")
}

// Deprecated returns the "deprecated" field with exact presence semantics.
func (value Header) Deprecated() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "deprecated")
}

// Style returns the "style" field with exact presence semantics.
func (value Header) Style() model.Field[string] {
	return modelaccess.String(value.raw, "style")
}

// Explode returns the "explode" field with exact presence semantics.
func (value Header) Explode() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "explode")
}

// Schema returns the "schema" field with exact presence semantics.
func (value Header) Schema() model.Field[Schema] {
	return modelaccess.Scalar(value.raw, "schema", wrapSchema)
}

// Example returns the "example" field with exact presence semantics.
func (value Header) Example() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "example")
}

// Examples returns the "examples" field with exact presence semantics.
func (value Header) Examples() model.Field[model.Map[ExampleOrReference]] {
	return modelaccess.Map(value.raw, "examples", wrapExampleOrReference)
}

// Content returns the "content" field with exact presence semantics.
func (value Header) Content() model.Field[model.Map[MediaType]] {
	return modelaccess.Map(value.raw, "content", wrapMediaType)
}

// Info is an immutable typed view of the Info Object.
type Info struct {
	raw jsonvalue.Value
}

func wrapInfo(raw jsonvalue.Value) (Info, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Info{}, false
	}
	return Info{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Info) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Info) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Title returns the "title" field with exact presence semantics.
func (value Info) Title() model.Field[string] {
	return modelaccess.String(value.raw, "title")
}

// Summary returns the "summary" field with exact presence semantics.
func (value Info) Summary() model.Field[string] {
	return modelaccess.String(value.raw, "summary")
}

// Description returns the "description" field with exact presence semantics.
func (value Info) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// TermsOfService returns the "termsOfService" field with exact presence semantics.
func (value Info) TermsOfService() model.Field[string] {
	return modelaccess.String(value.raw, "termsOfService")
}

// Contact returns the "contact" field with exact presence semantics.
func (value Info) Contact() model.Field[Contact] {
	return modelaccess.Scalar(value.raw, "contact", wrapContact)
}

// License returns the "license" field with exact presence semantics.
func (value Info) License() model.Field[License] {
	return modelaccess.Scalar(value.raw, "license", wrapLicense)
}

// Version returns the "version" field with exact presence semantics.
func (value Info) Version() model.Field[string] {
	return modelaccess.String(value.raw, "version")
}

// License is an immutable typed view of the License Object.
type License struct {
	raw jsonvalue.Value
}

func wrapLicense(raw jsonvalue.Value) (License, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return License{}, false
	}
	return License{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value License) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value License) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value License) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// IDentifier returns the "identifier" field with exact presence semantics.
func (value License) IDentifier() model.Field[string] {
	return modelaccess.String(value.raw, "identifier")
}

// URL returns the "url" field with exact presence semantics.
func (value License) URL() model.Field[string] {
	return modelaccess.String(value.raw, "url")
}

// Link is an immutable typed view of the Link Object.
type Link struct {
	raw jsonvalue.Value
}

func wrapLink(raw jsonvalue.Value) (Link, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Link{}, false
	}
	return Link{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Link) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Link) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// OperationRef returns the "operationRef" field with exact presence semantics.
func (value Link) OperationRef() model.Field[string] {
	return modelaccess.String(value.raw, "operationRef")
}

// OperationID returns the "operationId" field with exact presence semantics.
func (value Link) OperationID() model.Field[string] {
	return modelaccess.String(value.raw, "operationId")
}

// Parameters returns the "parameters" field with exact presence semantics.
func (value Link) Parameters() model.Field[model.Map[jsonvalue.Value]] {
	return modelaccess.Map(value.raw, "parameters", rawValue)
}

// RequestBody returns the "requestBody" field with exact presence semantics.
func (value Link) RequestBody() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "requestBody")
}

// Description returns the "description" field with exact presence semantics.
func (value Link) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Server returns the "server" field with exact presence semantics.
func (value Link) Server() model.Field[Server] {
	return modelaccess.Scalar(value.raw, "server", wrapServer)
}

// MediaType is an immutable typed view of the Media Type Object.
type MediaType struct {
	raw jsonvalue.Value
}

func wrapMediaType(raw jsonvalue.Value) (MediaType, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return MediaType{}, false
	}
	return MediaType{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value MediaType) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value MediaType) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Schema returns the "schema" field with exact presence semantics.
func (value MediaType) Schema() model.Field[Schema] {
	return modelaccess.Scalar(value.raw, "schema", wrapSchema)
}

// Example returns the "example" field with exact presence semantics.
func (value MediaType) Example() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "example")
}

// Examples returns the "examples" field with exact presence semantics.
func (value MediaType) Examples() model.Field[model.Map[ExampleOrReference]] {
	return modelaccess.Map(value.raw, "examples", wrapExampleOrReference)
}

// Encoding returns the "encoding" field with exact presence semantics.
func (value MediaType) Encoding() model.Field[model.Map[Encoding]] {
	return modelaccess.Map(value.raw, "encoding", wrapEncoding)
}

// OAuthFlow is an immutable typed view of the OAuth Flow Object.
type OAuthFlow struct {
	raw jsonvalue.Value
}

func wrapOAuthFlow(raw jsonvalue.Value) (OAuthFlow, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return OAuthFlow{}, false
	}
	return OAuthFlow{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value OAuthFlow) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value OAuthFlow) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// AuthorizationURL returns the "authorizationUrl" field with exact presence semantics.
func (value OAuthFlow) AuthorizationURL() model.Field[string] {
	return modelaccess.String(value.raw, "authorizationUrl")
}

// TokenURL returns the "tokenUrl" field with exact presence semantics.
func (value OAuthFlow) TokenURL() model.Field[string] {
	return modelaccess.String(value.raw, "tokenUrl")
}

// RefreshURL returns the "refreshUrl" field with exact presence semantics.
func (value OAuthFlow) RefreshURL() model.Field[string] {
	return modelaccess.String(value.raw, "refreshUrl")
}

// Scopes returns the "scopes" field with exact presence semantics.
func (value OAuthFlow) Scopes() model.Field[model.Map[string]] {
	return modelaccess.Map(value.raw, "scopes", stringValue)
}

// OAuthFlows is an immutable typed view of the OAuth Flows Object.
type OAuthFlows struct {
	raw jsonvalue.Value
}

func wrapOAuthFlows(raw jsonvalue.Value) (OAuthFlows, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return OAuthFlows{}, false
	}
	return OAuthFlows{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value OAuthFlows) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value OAuthFlows) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Implicit returns the "implicit" field with exact presence semantics.
func (value OAuthFlows) Implicit() model.Field[OAuthFlow] {
	return modelaccess.Scalar(value.raw, "implicit", wrapOAuthFlow)
}

// Password returns the "password" field with exact presence semantics.
func (value OAuthFlows) Password() model.Field[OAuthFlow] {
	return modelaccess.Scalar(value.raw, "password", wrapOAuthFlow)
}

// ClientCredentials returns the "clientCredentials" field with exact presence semantics.
func (value OAuthFlows) ClientCredentials() model.Field[OAuthFlow] {
	return modelaccess.Scalar(value.raw, "clientCredentials", wrapOAuthFlow)
}

// AuthorizationCode returns the "authorizationCode" field with exact presence semantics.
func (value OAuthFlows) AuthorizationCode() model.Field[OAuthFlow] {
	return modelaccess.Scalar(value.raw, "authorizationCode", wrapOAuthFlow)
}

// Operation is an immutable typed view of the Operation Object.
type Operation struct {
	raw jsonvalue.Value
}

func wrapOperation(raw jsonvalue.Value) (Operation, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Operation{}, false
	}
	return Operation{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Operation) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Operation) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Tags returns the "tags" field with exact presence semantics.
func (value Operation) Tags() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "tags", stringValue)
}

// Summary returns the "summary" field with exact presence semantics.
func (value Operation) Summary() model.Field[string] {
	return modelaccess.String(value.raw, "summary")
}

// Description returns the "description" field with exact presence semantics.
func (value Operation) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// ExternalDocs returns the "externalDocs" field with exact presence semantics.
func (value Operation) ExternalDocs() model.Field[ExternalDocumentation] {
	return modelaccess.Scalar(value.raw, "externalDocs", wrapExternalDocumentation)
}

// OperationID returns the "operationId" field with exact presence semantics.
func (value Operation) OperationID() model.Field[string] {
	return modelaccess.String(value.raw, "operationId")
}

// Parameters returns the "parameters" field with exact presence semantics.
func (value Operation) Parameters() model.Field[model.List[ParameterOrReference]] {
	return modelaccess.List(value.raw, "parameters", wrapParameterOrReference)
}

// RequestBody returns the "requestBody" field with exact presence semantics.
func (value Operation) RequestBody() model.Field[RequestBodyOrReference] {
	return modelaccess.Scalar(value.raw, "requestBody", wrapRequestBodyOrReference)
}

// Responses returns the "responses" field with exact presence semantics.
func (value Operation) Responses() model.Field[Responses] {
	return modelaccess.Scalar(value.raw, "responses", wrapResponses)
}

// Callbacks returns the "callbacks" field with exact presence semantics.
func (value Operation) Callbacks() model.Field[model.Map[CallbackOrReference]] {
	return modelaccess.Map(value.raw, "callbacks", wrapCallbackOrReference)
}

// Deprecated returns the "deprecated" field with exact presence semantics.
func (value Operation) Deprecated() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "deprecated")
}

// Security returns the "security" field with exact presence semantics.
func (value Operation) Security() model.Field[model.List[SecurityRequirement]] {
	return modelaccess.List(value.raw, "security", wrapSecurityRequirement)
}

// Servers returns the "servers" field with exact presence semantics.
func (value Operation) Servers() model.Field[model.List[Server]] {
	return modelaccess.List(value.raw, "servers", wrapServer)
}

// Parameter is an immutable typed view of the Parameter Object.
type Parameter struct {
	raw jsonvalue.Value
}

func wrapParameter(raw jsonvalue.Value) (Parameter, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Parameter{}, false
	}
	return Parameter{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Parameter) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Parameter) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value Parameter) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// In returns the "in" field with exact presence semantics.
func (value Parameter) In() model.Field[string] {
	return modelaccess.String(value.raw, "in")
}

// Description returns the "description" field with exact presence semantics.
func (value Parameter) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Required returns the "required" field with exact presence semantics.
func (value Parameter) Required() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "required")
}

// Deprecated returns the "deprecated" field with exact presence semantics.
func (value Parameter) Deprecated() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "deprecated")
}

// AllowEmptyValue returns the "allowEmptyValue" field with exact presence semantics.
func (value Parameter) AllowEmptyValue() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "allowEmptyValue")
}

// Style returns the "style" field with exact presence semantics.
func (value Parameter) Style() model.Field[string] {
	return modelaccess.String(value.raw, "style")
}

// Explode returns the "explode" field with exact presence semantics.
func (value Parameter) Explode() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "explode")
}

// AllowReserved returns the "allowReserved" field with exact presence semantics.
func (value Parameter) AllowReserved() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "allowReserved")
}

// Schema returns the "schema" field with exact presence semantics.
func (value Parameter) Schema() model.Field[Schema] {
	return modelaccess.Scalar(value.raw, "schema", wrapSchema)
}

// Example returns the "example" field with exact presence semantics.
func (value Parameter) Example() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "example")
}

// Examples returns the "examples" field with exact presence semantics.
func (value Parameter) Examples() model.Field[model.Map[ExampleOrReference]] {
	return modelaccess.Map(value.raw, "examples", wrapExampleOrReference)
}

// Content returns the "content" field with exact presence semantics.
func (value Parameter) Content() model.Field[model.Map[MediaType]] {
	return modelaccess.Map(value.raw, "content", wrapMediaType)
}

// PathItem is an immutable typed view of the Path Item Object.
type PathItem struct {
	raw jsonvalue.Value
}

func wrapPathItem(raw jsonvalue.Value) (PathItem, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return PathItem{}, false
	}
	return PathItem{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value PathItem) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value PathItem) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Ref returns the "$ref" field with exact presence semantics.
func (value PathItem) Ref() model.Field[string] {
	return modelaccess.String(value.raw, "$ref")
}

// Summary returns the "summary" field with exact presence semantics.
func (value PathItem) Summary() model.Field[string] {
	return modelaccess.String(value.raw, "summary")
}

// Description returns the "description" field with exact presence semantics.
func (value PathItem) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Get returns the "get" field with exact presence semantics.
func (value PathItem) Get() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "get", wrapOperation)
}

// Put returns the "put" field with exact presence semantics.
func (value PathItem) Put() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "put", wrapOperation)
}

// Post returns the "post" field with exact presence semantics.
func (value PathItem) Post() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "post", wrapOperation)
}

// Delete returns the "delete" field with exact presence semantics.
func (value PathItem) Delete() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "delete", wrapOperation)
}

// Options returns the "options" field with exact presence semantics.
func (value PathItem) Options() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "options", wrapOperation)
}

// Head returns the "head" field with exact presence semantics.
func (value PathItem) Head() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "head", wrapOperation)
}

// Patch returns the "patch" field with exact presence semantics.
func (value PathItem) Patch() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "patch", wrapOperation)
}

// Trace returns the "trace" field with exact presence semantics.
func (value PathItem) Trace() model.Field[Operation] {
	return modelaccess.Scalar(value.raw, "trace", wrapOperation)
}

// Servers returns the "servers" field with exact presence semantics.
func (value PathItem) Servers() model.Field[model.List[Server]] {
	return modelaccess.List(value.raw, "servers", wrapServer)
}

// Parameters returns the "parameters" field with exact presence semantics.
func (value PathItem) Parameters() model.Field[model.List[ParameterOrReference]] {
	return modelaccess.List(value.raw, "parameters", wrapParameterOrReference)
}

// Paths is an immutable typed view of the Paths Object.
type Paths struct {
	raw jsonvalue.Value
}

func wrapPaths(raw jsonvalue.Value) (Paths, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Paths{}, false
	}
	return Paths{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Paths) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Paths) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value Paths) Entries() model.Map[model.Field[PathItem]] {
	return modelaccess.PatternEntries(value.raw, []string{}, pathPatternName, wrapPathItem)
}

// Reference is an immutable typed view of the Reference Object.
type Reference struct {
	raw jsonvalue.Value
}

func wrapReference(raw jsonvalue.Value) (Reference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Reference{}, false
	}
	return Reference{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Reference) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Reference) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Ref returns the "$ref" field with exact presence semantics.
func (value Reference) Ref() model.Field[string] {
	return modelaccess.String(value.raw, "$ref")
}

// Summary returns the "summary" field with exact presence semantics.
func (value Reference) Summary() model.Field[string] {
	return modelaccess.String(value.raw, "summary")
}

// Description returns the "description" field with exact presence semantics.
func (value Reference) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// RequestBody is an immutable typed view of the Request Body Object.
type RequestBody struct {
	raw jsonvalue.Value
}

func wrapRequestBody(raw jsonvalue.Value) (RequestBody, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return RequestBody{}, false
	}
	return RequestBody{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value RequestBody) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value RequestBody) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Description returns the "description" field with exact presence semantics.
func (value RequestBody) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Content returns the "content" field with exact presence semantics.
func (value RequestBody) Content() model.Field[model.Map[MediaType]] {
	return modelaccess.Map(value.raw, "content", wrapMediaType)
}

// Required returns the "required" field with exact presence semantics.
func (value RequestBody) Required() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "required")
}

// Response is an immutable typed view of the Response Object.
type Response struct {
	raw jsonvalue.Value
}

func wrapResponse(raw jsonvalue.Value) (Response, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Response{}, false
	}
	return Response{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Response) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Response) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Description returns the "description" field with exact presence semantics.
func (value Response) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Headers returns the "headers" field with exact presence semantics.
func (value Response) Headers() model.Field[model.Map[HeaderOrReference]] {
	return modelaccess.Map(value.raw, "headers", wrapHeaderOrReference)
}

// Content returns the "content" field with exact presence semantics.
func (value Response) Content() model.Field[model.Map[MediaType]] {
	return modelaccess.Map(value.raw, "content", wrapMediaType)
}

// Links returns the "links" field with exact presence semantics.
func (value Response) Links() model.Field[model.Map[LinkOrReference]] {
	return modelaccess.Map(value.raw, "links", wrapLinkOrReference)
}

// Responses is an immutable typed view of the Responses Object.
type Responses struct {
	raw jsonvalue.Value
}

func wrapResponses(raw jsonvalue.Value) (Responses, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Responses{}, false
	}
	return Responses{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Responses) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Responses) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Default returns the "default" field with exact presence semantics.
func (value Responses) Default() model.Field[ResponseOrReference] {
	return modelaccess.Scalar(value.raw, "default", wrapResponseOrReference)
}

// Entries returns typed patterned fields in source order.
func (value Responses) Entries() model.Map[model.Field[ResponseOrReference]] {
	return modelaccess.PatternEntries(value.raw, []string{"default"}, extensionAwarePatternName, wrapResponseOrReference)
}

// Schema is an immutable typed view of the Schema Object.
type Schema struct {
	raw jsonvalue.Value
}

func wrapSchema(raw jsonvalue.Value) (Schema, bool) {
	if raw.Kind() != jsonvalue.ObjectKind && raw.Kind() != jsonvalue.BooleanKind {
		return Schema{}, false
	}
	return Schema{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Schema) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Schema) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Discriminator returns the "discriminator" field with exact presence semantics.
func (value Schema) Discriminator() model.Field[Discriminator] {
	return modelaccess.Scalar(value.raw, "discriminator", wrapDiscriminator)
}

// XML returns the "xml" field with exact presence semantics.
func (value Schema) XML() model.Field[XML] {
	return modelaccess.Scalar(value.raw, "xml", wrapXML)
}

// ExternalDocs returns the "externalDocs" field with exact presence semantics.
func (value Schema) ExternalDocs() model.Field[ExternalDocumentation] {
	return modelaccess.Scalar(value.raw, "externalDocs", wrapExternalDocumentation)
}

// Example returns the "example" field with exact presence semantics.
func (value Schema) Example() model.Field[jsonvalue.Value] {
	return modelaccess.Raw(value.raw, "example")
}

// SecurityRequirement is an immutable typed view of the Security Requirement Object.
type SecurityRequirement struct {
	raw jsonvalue.Value
}

func wrapSecurityRequirement(raw jsonvalue.Value) (SecurityRequirement, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return SecurityRequirement{}, false
	}
	return SecurityRequirement{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value SecurityRequirement) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value SecurityRequirement) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Entries returns typed patterned fields in source order.
func (value SecurityRequirement) Entries() model.Map[model.Field[model.List[string]]] {
	return modelaccess.PatternEntries(value.raw, []string{}, anyPatternName, func(raw jsonvalue.Value) (model.List[string], bool) { return modelaccess.ListValue(raw, stringValue) })
}

// SecurityScheme is an immutable typed view of the Security Scheme Object.
type SecurityScheme struct {
	raw jsonvalue.Value
}

func wrapSecurityScheme(raw jsonvalue.Value) (SecurityScheme, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return SecurityScheme{}, false
	}
	return SecurityScheme{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value SecurityScheme) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value SecurityScheme) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Type returns the "type" field with exact presence semantics.
func (value SecurityScheme) Type() model.Field[string] {
	return modelaccess.String(value.raw, "type")
}

// Description returns the "description" field with exact presence semantics.
func (value SecurityScheme) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Name returns the "name" field with exact presence semantics.
func (value SecurityScheme) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// In returns the "in" field with exact presence semantics.
func (value SecurityScheme) In() model.Field[string] {
	return modelaccess.String(value.raw, "in")
}

// Scheme returns the "scheme" field with exact presence semantics.
func (value SecurityScheme) Scheme() model.Field[string] {
	return modelaccess.String(value.raw, "scheme")
}

// BearerFormat returns the "bearerFormat" field with exact presence semantics.
func (value SecurityScheme) BearerFormat() model.Field[string] {
	return modelaccess.String(value.raw, "bearerFormat")
}

// Flows returns the "flows" field with exact presence semantics.
func (value SecurityScheme) Flows() model.Field[OAuthFlows] {
	return modelaccess.Scalar(value.raw, "flows", wrapOAuthFlows)
}

// OpenIDConnectURL returns the "openIdConnectUrl" field with exact presence semantics.
func (value SecurityScheme) OpenIDConnectURL() model.Field[string] {
	return modelaccess.String(value.raw, "openIdConnectUrl")
}

// Server is an immutable typed view of the Server Object.
type Server struct {
	raw jsonvalue.Value
}

func wrapServer(raw jsonvalue.Value) (Server, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Server{}, false
	}
	return Server{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Server) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Server) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// URL returns the "url" field with exact presence semantics.
func (value Server) URL() model.Field[string] {
	return modelaccess.String(value.raw, "url")
}

// Description returns the "description" field with exact presence semantics.
func (value Server) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Variables returns the "variables" field with exact presence semantics.
func (value Server) Variables() model.Field[model.Map[ServerVariable]] {
	return modelaccess.Map(value.raw, "variables", wrapServerVariable)
}

// ServerVariable is an immutable typed view of the Server Variable Object.
type ServerVariable struct {
	raw jsonvalue.Value
}

func wrapServerVariable(raw jsonvalue.Value) (ServerVariable, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ServerVariable{}, false
	}
	return ServerVariable{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value ServerVariable) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value ServerVariable) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Enum returns the "enum" field with exact presence semantics.
func (value ServerVariable) Enum() model.Field[model.List[string]] {
	return modelaccess.List(value.raw, "enum", stringValue)
}

// Default returns the "default" field with exact presence semantics.
func (value ServerVariable) Default() model.Field[string] {
	return modelaccess.String(value.raw, "default")
}

// Description returns the "description" field with exact presence semantics.
func (value ServerVariable) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// Tag is an immutable typed view of the Tag Object.
type Tag struct {
	raw jsonvalue.Value
}

func wrapTag(raw jsonvalue.Value) (Tag, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return Tag{}, false
	}
	return Tag{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value Tag) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value Tag) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value Tag) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// Description returns the "description" field with exact presence semantics.
func (value Tag) Description() model.Field[string] {
	return modelaccess.String(value.raw, "description")
}

// ExternalDocs returns the "externalDocs" field with exact presence semantics.
func (value Tag) ExternalDocs() model.Field[ExternalDocumentation] {
	return modelaccess.Scalar(value.raw, "externalDocs", wrapExternalDocumentation)
}

// XML is an immutable typed view of the XML Object.
type XML struct {
	raw jsonvalue.Value
}

func wrapXML(raw jsonvalue.Value) (XML, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return XML{}, false
	}
	return XML{raw: raw}, true
}

// Raw returns the complete immutable semantic representation.
func (value XML) Raw() jsonvalue.Value {
	return value.raw
}

// Extensions returns x- fields in source order.
func (value XML) Extensions() model.Map[jsonvalue.Value] {
	return modelaccess.Extensions(value.raw)
}

// Name returns the "name" field with exact presence semantics.
func (value XML) Name() model.Field[string] {
	return modelaccess.String(value.raw, "name")
}

// Namespace returns the "namespace" field with exact presence semantics.
func (value XML) Namespace() model.Field[string] {
	return modelaccess.String(value.raw, "namespace")
}

// Prefix returns the "prefix" field with exact presence semantics.
func (value XML) Prefix() model.Field[string] {
	return modelaccess.String(value.raw, "prefix")
}

// Attribute returns the "attribute" field with exact presence semantics.
func (value XML) Attribute() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "attribute")
}

// Wrapped returns the "wrapped" field with exact presence semantics.
func (value XML) Wrapped() model.Field[bool] {
	return modelaccess.Boolean(value.raw, "wrapped")
}

// CallbackOrReference preserves either a Callback or Reference Object.
type CallbackOrReference struct {
	raw jsonvalue.Value
}

func wrapCallbackOrReference(raw jsonvalue.Value) (CallbackOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return CallbackOrReference{}, false
	}
	return CallbackOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value CallbackOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value CallbackOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value CallbackOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// Callback returns the selected target object.
func (value CallbackOrReference) Callback() (Callback, bool) {
	if value.IsReference() {
		return Callback{}, false
	}
	return wrapCallback(value.raw)
}

// ExampleOrReference preserves either a Example or Reference Object.
type ExampleOrReference struct {
	raw jsonvalue.Value
}

func wrapExampleOrReference(raw jsonvalue.Value) (ExampleOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ExampleOrReference{}, false
	}
	return ExampleOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value ExampleOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value ExampleOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value ExampleOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// Example returns the selected target object.
func (value ExampleOrReference) Example() (Example, bool) {
	if value.IsReference() {
		return Example{}, false
	}
	return wrapExample(value.raw)
}

// HeaderOrReference preserves either a Header or Reference Object.
type HeaderOrReference struct {
	raw jsonvalue.Value
}

func wrapHeaderOrReference(raw jsonvalue.Value) (HeaderOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return HeaderOrReference{}, false
	}
	return HeaderOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value HeaderOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value HeaderOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value HeaderOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// Header returns the selected target object.
func (value HeaderOrReference) Header() (Header, bool) {
	if value.IsReference() {
		return Header{}, false
	}
	return wrapHeader(value.raw)
}

// LinkOrReference preserves either a Link or Reference Object.
type LinkOrReference struct {
	raw jsonvalue.Value
}

func wrapLinkOrReference(raw jsonvalue.Value) (LinkOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return LinkOrReference{}, false
	}
	return LinkOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value LinkOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value LinkOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value LinkOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// Link returns the selected target object.
func (value LinkOrReference) Link() (Link, bool) {
	if value.IsReference() {
		return Link{}, false
	}
	return wrapLink(value.raw)
}

// ParameterOrReference preserves either a Parameter or Reference Object.
type ParameterOrReference struct {
	raw jsonvalue.Value
}

func wrapParameterOrReference(raw jsonvalue.Value) (ParameterOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ParameterOrReference{}, false
	}
	return ParameterOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value ParameterOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value ParameterOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value ParameterOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// Parameter returns the selected target object.
func (value ParameterOrReference) Parameter() (Parameter, bool) {
	if value.IsReference() {
		return Parameter{}, false
	}
	return wrapParameter(value.raw)
}

// RequestBodyOrReference preserves either a RequestBody or Reference Object.
type RequestBodyOrReference struct {
	raw jsonvalue.Value
}

func wrapRequestBodyOrReference(raw jsonvalue.Value) (RequestBodyOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return RequestBodyOrReference{}, false
	}
	return RequestBodyOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value RequestBodyOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value RequestBodyOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value RequestBodyOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// RequestBody returns the selected target object.
func (value RequestBodyOrReference) RequestBody() (RequestBody, bool) {
	if value.IsReference() {
		return RequestBody{}, false
	}
	return wrapRequestBody(value.raw)
}

// ResponseOrReference preserves either a Response or Reference Object.
type ResponseOrReference struct {
	raw jsonvalue.Value
}

func wrapResponseOrReference(raw jsonvalue.Value) (ResponseOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return ResponseOrReference{}, false
	}
	return ResponseOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value ResponseOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value ResponseOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value ResponseOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// Response returns the selected target object.
func (value ResponseOrReference) Response() (Response, bool) {
	if value.IsReference() {
		return Response{}, false
	}
	return wrapResponse(value.raw)
}

// SecuritySchemeOrReference preserves either a SecurityScheme or Reference Object.
type SecuritySchemeOrReference struct {
	raw jsonvalue.Value
}

func wrapSecuritySchemeOrReference(raw jsonvalue.Value) (SecuritySchemeOrReference, bool) {
	if raw.Kind() != jsonvalue.ObjectKind {
		return SecuritySchemeOrReference{}, false
	}
	return SecuritySchemeOrReference{raw: raw}, true
}

// Raw returns the complete union representation.
func (value SecuritySchemeOrReference) Raw() jsonvalue.Value { return value.raw }

// IsReference reports whether $ref selects the Reference Object.
func (value SecuritySchemeOrReference) IsReference() bool {
	_, ok := modelaccess.String(value.raw, "$ref").Value()
	return ok
}

// Reference returns the selected Reference Object.
func (value SecuritySchemeOrReference) Reference() (Reference, bool) {
	if !value.IsReference() {
		return Reference{}, false
	}
	return wrapReference(value.raw)
}

// SecurityScheme returns the selected target object.
func (value SecuritySchemeOrReference) SecurityScheme() (SecurityScheme, bool) {
	if value.IsReference() {
		return SecurityScheme{}, false
	}
	return wrapSecurityScheme(value.raw)
}
