// Code generated by noprocesscontrol fixture. DO NOT EDIT.

package processuse

func GeneratedPanic() {
	panic("boom") // want `lifecycle/no-process-control: panic is restricted to approved entrypoints`
}
