// Code generated by forbiddenapi fixture. DO NOT EDIT.

package consumer

import "legacy"

func GeneratedForbidden() {
	legacy.Old() // want `api/forbidden-call: legacy.Old is forbidden; use modern.New`
}
