// Code generated by fanout fixture. DO NOT EDIT.

package fanout

func Generated(values []int) {
	for range values {
		go work() // want `lifecycle/unbounded-goroutine-fanout: goroutine launch is repeated without a proven limit of 8`
	}
}
