// Code generated by mutableglobal fixture. DO NOT EDIT.

package mutableglobals

var generatedState []int // want `safety/no-mutable-global: package variable generatedState holds shared mutable state`
