// Code generated by cleanupownership fixture. DO NOT EDIT.

package consumer

import "resourceapi"

func generatedCleanup() {
	_, _, _ = resourceapi.Open() // want `lifecycle/cleanup-ownership: cleanup result 2 from resourceapi.Open is discarded`
}
