<?php

declare(strict_types=1);

/**
 * Generate the frozen voku/portable-ascii replacement table used by the
 * Laravel-compatible slug profile.
 *
 * Usage:
 * php scripts/generate-table.php \
 *   --source=/path/to/voku/portable-ascii/src/voku/helper/data \
 *   --output=transliteration_table.go
 */

$options = getopt('', ['source:', 'output:']);
$source = $options['source'] ?? null;
$output = $options['output'] ?? null;

if (!is_string($source) || !is_dir($source)) {
    fwrite(STDERR, "a valid --source directory is required\n");
    exit(1);
}
if (!is_string($output) || trim($output) === '') {
    fwrite(STDERR, "--output is required\n");
    exit(1);
}

$mapFile = rtrim($source, DIRECTORY_SEPARATOR)
    .DIRECTORY_SEPARATOR
    .'ascii_by_languages.php';
if (!is_file($mapFile)) {
    fwrite(STDERR, "ascii_by_languages.php was not found\n");
    exit(1);
}

$contents = file_get_contents($mapFile);
if ($contents === false) {
    fwrite(STDERR, "unable to read {$mapFile}\n");
    exit(1);
}
$languageMaps = require $mapFile;
if (!is_array($languageMaps) || $languageMaps === []) {
    fwrite(STDERR, "invalid replacement map: {$mapFile}\n");
    exit(1);
}

$entries = [];
foreach ($languageMaps as $languageMap) {
    if (!is_array($languageMap)) {
        fwrite(STDERR, "invalid language replacement map: {$mapFile}\n");
        exit(1);
    }
    foreach ($languageMap as $character => $replacement) {
        if (!is_string($character) || !is_string($replacement)) {
            fwrite(STDERR, "invalid replacement entry: {$mapFile}\n");
            exit(1);
        }
        $entries[$character] = $replacement;
    }
}
$entriesByFirstByte = [];
foreach ($entries as $character => $replacement) {
    $entriesByFirstByte[ord($character[0])][] = [
        'source' => $character,
        'replacement' => $replacement,
    ];
}
ksort($entriesByFirstByte, SORT_NUMERIC);
foreach ($entriesByFirstByte as &$group) {
    usort(
        $group,
        static fn (array $left, array $right): int =>
            strlen($right['source']) <=> strlen($left['source'])
            ?: strcmp($left['source'], $right['source']),
    );
}
unset($group);

$goStringLiteral = static function (string $value): string {
    $encoded = json_encode(
        $value,
        JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR,
    );

    return (string) preg_replace_callback(
        '/\p{Cf}/u',
        static function (array $matches): string {
            $codePoint = mb_ord($matches[0]);

            return $codePoint <= 0xFFFF
                ? sprintf('\\u%04x', $codePoint)
                : sprintf('\\U%08x', $codePoint);
        },
        $encoded,
    );
};

$lines = [
    '// Code generated by scripts/generate-table.php; DO NOT EDIT.',
    '//',
    '// Source: voku/portable-ascii 2.1.1',
    '// Commit: 8e1051fe39379367aecf014f41744ce7539a856f',
    '// License: MIT',
    '// Source-map SHA-256: '.hash('sha256', $contents),
    '',
    'package slug',
    '',
    'type laravelReplacement struct {',
    "\tsource string",
    "\tvalue  string",
    '}',
    '',
    'var laravelEnglishReplacements = map[byte][]laravelReplacement{',
];
foreach ($entriesByFirstByte as $firstByte => $group) {
    $lines[] = sprintf("\t0x%02X: {", $firstByte);
    foreach ($group as $entry) {
        $lines[] = sprintf(
            "\t\t{source: %s, value: %s},",
            $goStringLiteral($entry['source']),
            $goStringLiteral($entry['replacement']),
        );
    }
    $lines[] = "\t},";
}
$lines[] = '}';
$lines[] = '';

if (file_put_contents($output, implode("\n", $lines)) === false) {
    fwrite(STDERR, "unable to write {$output}\n");
    exit(1);
}
